/*
 * Copyright     :  Copyright (c) Huawei Technologies Co., Ltd. 2021. All rights reserved.
 * File name     :  mpi_trace_reg_addr_define.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1.0
 * Date          :  2018/9/28
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  xxx 2021/09/03 17:07:47 Create file
 */

#ifndef __MPI_TRACE_REG_ADDR_DEFINE_H__
#define __MPI_TRACE_REG_ADDR_DEFINE_H__

/////////////////////////////////////////////
////    global parameters, begin         ////
/////////////////////////////////////////////
#define    MPI_TRACE_REG_BASE_ADDR                    0x14800

////             offset address for MPI_TRACE_REG registers
#define MPI_TRACE_REG_MPI_RDY_NUM_OFFSET 0x0
#define MPI_TRACE_REG_RDY_LAST_NUM_MASK 0xFF0000
#define MPI_TRACE_REG_RDY_LAST_NUM_SHIFT 16
#define MPI_TRACE_REG_RDY_LAST_NUM_LEN 8
#define MPI_TRACE_REG_RDY_LAST_NUM_RESETVAL 0x00
#define MPI_TRACE_REG_RDY_DELAY_NUM_MASK 0xFF
#define MPI_TRACE_REG_RDY_DELAY_NUM_SHIFT 0
#define MPI_TRACE_REG_RDY_DELAY_NUM_LEN 8
#define MPI_TRACE_REG_RDY_DELAY_NUM_RESETVAL 0x08

#define MPI_TRACE_REG_TRACE_EN_OFFSET 0x4
#define MPI_TRACE_REG_CSR_TRACE_EN_MASK 0x1
#define MPI_TRACE_REG_CSR_TRACE_EN_SHIFT 0
#define MPI_TRACE_REG_CSR_TRACE_EN_LEN 1
#define MPI_TRACE_REG_CSR_TRACE_EN_RESETVAL 0x0

#define MPI_TRACE_REG_TRACE_MODE_OFFSET 0x8
#define MPI_TRACE_REG_CSR_TRACE_MODE_MASK 0x1
#define MPI_TRACE_REG_CSR_TRACE_MODE_SHIFT 0
#define MPI_TRACE_REG_CSR_TRACE_MODE_LEN 1
#define MPI_TRACE_REG_CSR_TRACE_MODE_RESETVAL 0x0

#define MPI_TRACE_REG_TRACE_CH_SEL_OFFSET 0xC
#define MPI_TRACE_REG_CSR_TRACE_CH_SEL_MASK 0xF
#define MPI_TRACE_REG_CSR_TRACE_CH_SEL_SHIFT 0
#define MPI_TRACE_REG_CSR_TRACE_CH_SEL_LEN 4
#define MPI_TRACE_REG_CSR_TRACE_CH_SEL_RESETVAL 0xF

#define MPI_TRACE_REG_TRACE_CNT_OFFSET 0x10
#define MPI_TRACE_REG_CSR_TRACE_CNT_MASK 0x7FF
#define MPI_TRACE_REG_CSR_TRACE_CNT_SHIFT 0
#define MPI_TRACE_REG_CSR_TRACE_CNT_LEN 11
#define MPI_TRACE_REG_CSR_TRACE_CNT_RESETVAL 0x000

#define MPI_TRACE_REG_TRACE_WADDR_OFFSET 0x14
#define MPI_TRACE_REG_CSR_TRACE_WADDR_MASK 0x3FF
#define MPI_TRACE_REG_CSR_TRACE_WADDR_SHIFT 0
#define MPI_TRACE_REG_CSR_TRACE_WADDR_LEN 10
#define MPI_TRACE_REG_CSR_TRACE_WADDR_RESETVAL 0x000

#define MPI_TRACE_REG_MUX_DBG_CFG_OFFSET 0x200
#define MPI_TRACE_REG_DBG_MUX_SET_ID3_MASK 0xFE000000
#define MPI_TRACE_REG_DBG_MUX_SET_ID3_SHIFT 25
#define MPI_TRACE_REG_DBG_MUX_SET_ID3_LEN 7
#define MPI_TRACE_REG_DBG_MUX_SET_ID3_RESETVAL 0x00
#define MPI_TRACE_REG_DBG_MUX_ENABLE3_MASK 0x1000000
#define MPI_TRACE_REG_DBG_MUX_ENABLE3_SHIFT 24
#define MPI_TRACE_REG_DBG_MUX_ENABLE3_LEN 1
#define MPI_TRACE_REG_DBG_MUX_ENABLE3_RESETVAL 0x0
#define MPI_TRACE_REG_DBG_MUX_SET_ID2_MASK 0xFE0000
#define MPI_TRACE_REG_DBG_MUX_SET_ID2_SHIFT 17
#define MPI_TRACE_REG_DBG_MUX_SET_ID2_LEN 7
#define MPI_TRACE_REG_DBG_MUX_SET_ID2_RESETVAL 0x00
#define MPI_TRACE_REG_DBG_MUX_ENABLE2_MASK 0x10000
#define MPI_TRACE_REG_DBG_MUX_ENABLE2_SHIFT 16
#define MPI_TRACE_REG_DBG_MUX_ENABLE2_LEN 1
#define MPI_TRACE_REG_DBG_MUX_ENABLE2_RESETVAL 0x0
#define MPI_TRACE_REG_DBG_MUX_SET_ID1_MASK 0xFE00
#define MPI_TRACE_REG_DBG_MUX_SET_ID1_SHIFT 9
#define MPI_TRACE_REG_DBG_MUX_SET_ID1_LEN 7
#define MPI_TRACE_REG_DBG_MUX_SET_ID1_RESETVAL 0x00
#define MPI_TRACE_REG_DBG_MUX_ENABLE1_MASK 0x100
#define MPI_TRACE_REG_DBG_MUX_ENABLE1_SHIFT 8
#define MPI_TRACE_REG_DBG_MUX_ENABLE1_LEN 1
#define MPI_TRACE_REG_DBG_MUX_ENABLE1_RESETVAL 0x0
#define MPI_TRACE_REG_DBG_MUX_SET_ID0_MASK 0xFE
#define MPI_TRACE_REG_DBG_MUX_SET_ID0_SHIFT 1
#define MPI_TRACE_REG_DBG_MUX_SET_ID0_LEN 7
#define MPI_TRACE_REG_DBG_MUX_SET_ID0_RESETVAL 0x00
#define MPI_TRACE_REG_DBG_MUX_ENABLE0_MASK 0x1
#define MPI_TRACE_REG_DBG_MUX_ENABLE0_SHIFT 0
#define MPI_TRACE_REG_DBG_MUX_ENABLE0_LEN 1
#define MPI_TRACE_REG_DBG_MUX_ENABLE0_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_0_OFFSET 0x204
#define MPI_TRACE_REG_AGGR_SET_ID3_0_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_0_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_0_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_0_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_0_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_0_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_0_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_0_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_0_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_0_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_0_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_0_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_0_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_0_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_0_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_0_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_0_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_0_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_0_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_0_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_0_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_0_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_0_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_0_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_0_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_0_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_0_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_0_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_0_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_0_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_0_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_0_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_1_OFFSET 0x208
#define MPI_TRACE_REG_AGGR_SET_ID3_1_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_1_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_1_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_1_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_1_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_1_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_1_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_1_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_1_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_1_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_1_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_1_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_1_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_1_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_1_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_1_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_1_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_1_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_1_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_1_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_1_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_1_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_1_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_1_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_1_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_1_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_1_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_1_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_1_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_1_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_1_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_1_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_2_OFFSET 0x20C
#define MPI_TRACE_REG_AGGR_SET_ID3_2_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_2_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_2_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_2_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_2_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_2_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_2_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_2_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_2_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_2_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_2_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_2_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_2_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_2_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_2_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_2_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_2_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_2_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_2_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_2_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_2_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_2_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_2_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_2_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_2_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_2_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_2_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_2_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_2_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_2_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_2_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_2_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_3_OFFSET 0x210
#define MPI_TRACE_REG_AGGR_SET_ID3_3_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_3_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_3_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_3_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_3_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_3_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_3_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_3_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_3_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_3_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_3_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_3_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_3_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_3_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_3_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_3_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_3_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_3_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_3_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_3_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_3_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_3_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_3_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_3_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_3_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_3_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_3_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_3_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_3_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_3_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_3_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_3_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_4_OFFSET 0x214
#define MPI_TRACE_REG_AGGR_SET_ID3_4_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_4_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_4_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_4_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_4_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_4_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_4_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_4_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_4_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_4_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_4_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_4_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_4_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_4_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_4_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_4_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_4_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_4_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_4_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_4_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_4_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_4_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_4_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_4_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_4_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_4_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_4_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_4_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_4_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_4_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_4_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_4_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_5_OFFSET 0x218
#define MPI_TRACE_REG_AGGR_SET_ID3_5_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_5_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_5_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_5_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_5_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_5_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_5_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_5_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_5_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_5_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_5_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_5_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_5_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_5_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_5_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_5_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_5_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_5_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_5_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_5_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_5_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_5_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_5_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_5_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_5_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_5_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_5_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_5_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_5_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_5_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_5_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_5_RESETVAL 0x0

#define MPI_TRACE_REG_AGGR_DBG_CFG_6_OFFSET 0x21C
#define MPI_TRACE_REG_AGGR_SET_ID3_6_MASK 0xFE000000
#define MPI_TRACE_REG_AGGR_SET_ID3_6_SHIFT 25
#define MPI_TRACE_REG_AGGR_SET_ID3_6_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID3_6_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE3_6_MASK 0x1000000
#define MPI_TRACE_REG_AGGR_ENABLE3_6_SHIFT 24
#define MPI_TRACE_REG_AGGR_ENABLE3_6_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE3_6_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID2_6_MASK 0xFE0000
#define MPI_TRACE_REG_AGGR_SET_ID2_6_SHIFT 17
#define MPI_TRACE_REG_AGGR_SET_ID2_6_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID2_6_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE2_6_MASK 0x10000
#define MPI_TRACE_REG_AGGR_ENABLE2_6_SHIFT 16
#define MPI_TRACE_REG_AGGR_ENABLE2_6_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE2_6_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID1_6_MASK 0xFE00
#define MPI_TRACE_REG_AGGR_SET_ID1_6_SHIFT 9
#define MPI_TRACE_REG_AGGR_SET_ID1_6_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID1_6_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE1_6_MASK 0x100
#define MPI_TRACE_REG_AGGR_ENABLE1_6_SHIFT 8
#define MPI_TRACE_REG_AGGR_ENABLE1_6_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE1_6_RESETVAL 0x0
#define MPI_TRACE_REG_AGGR_SET_ID0_6_MASK 0xFE
#define MPI_TRACE_REG_AGGR_SET_ID0_6_SHIFT 1
#define MPI_TRACE_REG_AGGR_SET_ID0_6_LEN 7
#define MPI_TRACE_REG_AGGR_SET_ID0_6_RESETVAL 0x00
#define MPI_TRACE_REG_AGGR_ENABLE0_6_MASK 0x1
#define MPI_TRACE_REG_AGGR_ENABLE0_6_SHIFT 0
#define MPI_TRACE_REG_AGGR_ENABLE0_6_LEN 1
#define MPI_TRACE_REG_AGGR_ENABLE0_6_RESETVAL 0x0


#endif // __MPI_TRACE_REG_ADDR_DEFINE_H__
