//******************************************************************************
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co., Ltd.
// File name     :  cmdlst_reg_offset_field.h
// Author        :  AnthonySixta
// Version       :  1.0
// Date          :  2018-06-30
// Description   :  Define all registers/tables for HiStarISP
// Others        :  Generated automatically by nManager V4.0
// History       :  AnthonySixta 2018-06-30 Create file
//******************************************************************************

#ifndef __CMDLST_REG_OFFSET_FIELD_CS_H__
#define __CMDLST_REG_OFFSET_FIELD_CS_H__

#define CMDLST_IP_ID_LEN    32
#define CMDLST_IP_ID_OFFSET 0

#define CMDLST_IP_VERSION_LEN    32
#define CMDLST_IP_VERSION_OFFSET 0

#define CMDLST_RESERVED_0_LEN              29
#define CMDLST_RESERVED_0_OFFSET           3
#define CMDLST_SLOWDOWN_NRT_CHANNEL_LEN    2
#define CMDLST_SLOWDOWN_NRT_CHANNEL_OFFSET 1
#define CMDLST_PREFETCH_LEN                1
#define CMDLST_PREFETCH_OFFSET             0

#define CMDLST_RESERVED_3_LEN           19
#define CMDLST_RESERVED_3_OFFSET        13
#define CMDLST_DBG_ARB_FSM_LEN          1
#define CMDLST_DBG_ARB_FSM_OFFSET       12
#define CMDLST_RESERVED_2_LEN           2
#define CMDLST_RESERVED_2_OFFSET        10
#define CMDLST_DBG_VP_WR_FSM_LEN        2
#define CMDLST_DBG_VP_WR_FSM_OFFSET     8
#define CMDLST_RESERVED_1_LEN           1
#define CMDLST_RESERVED_1_OFFSET        7
#define CMDLST_DBG_LB_MASTER_FSM_LEN    3
#define CMDLST_DBG_LB_MASTER_FSM_OFFSET 4
#define CMDLST_RESERVED_0_LEN           1
#define CMDLST_RESERVED_0_OFFSET        3
#define CMDLST_DBG_FIFO_NB_ELEM_LEN     3
#define CMDLST_DBG_FIFO_NB_ELEM_OFFSET  0

#define CMDLST_DBG_HW_START_LEN    16
#define CMDLST_DBG_HW_START_OFFSET 16
#define CMDLST_DBG_SW_START_LEN    16
#define CMDLST_DBG_SW_START_OFFSET 0

#define CMDLST_RESERVED_7_LEN      1
#define CMDLST_RESERVED_7_OFFSET   31
#define CMDLST_DBG_FSM_CH_7_LEN    3
#define CMDLST_DBG_FSM_CH_7_OFFSET 28
#define CMDLST_RESERVED_6_LEN      1
#define CMDLST_RESERVED_6_OFFSET   27
#define CMDLST_DBG_FSM_CH_6_LEN    3
#define CMDLST_DBG_FSM_CH_6_OFFSET 24
#define CMDLST_RESERVED_5_LEN      1
#define CMDLST_RESERVED_5_OFFSET   23
#define CMDLST_DBG_FSM_CH_5_LEN    3
#define CMDLST_DBG_FSM_CH_5_OFFSET 20
#define CMDLST_RESERVED_4_LEN      1
#define CMDLST_RESERVED_4_OFFSET   19
#define CMDLST_DBG_FSM_CH_4_LEN    3
#define CMDLST_DBG_FSM_CH_4_OFFSET 16
#define CMDLST_RESERVED_3_LEN      1
#define CMDLST_RESERVED_3_OFFSET   15
#define CMDLST_DBG_FSM_CH_3_LEN    3
#define CMDLST_DBG_FSM_CH_3_OFFSET 12
#define CMDLST_RESERVED_2_LEN      1
#define CMDLST_RESERVED_2_OFFSET   11
#define CMDLST_DBG_FSM_CH_2_LEN    3
#define CMDLST_DBG_FSM_CH_2_OFFSET 8
#define CMDLST_RESERVED_1_LEN      1
#define CMDLST_RESERVED_1_OFFSET   7
#define CMDLST_DBG_FSM_CH_1_LEN    3
#define CMDLST_DBG_FSM_CH_1_OFFSET 4
#define CMDLST_RESERVED_0_LEN      1
#define CMDLST_RESERVED_0_OFFSET   3
#define CMDLST_DBG_FSM_CH_0_LEN    3
#define CMDLST_DBG_FSM_CH_0_OFFSET 0

#define CMDLST_RESERVED_7_LEN       1
#define CMDLST_RESERVED_7_OFFSET    31
#define CMDLST_DBG_FSM_CH_15_LEN    3
#define CMDLST_DBG_FSM_CH_15_OFFSET 28
#define CMDLST_RESERVED_6_LEN       1
#define CMDLST_RESERVED_6_OFFSET    27
#define CMDLST_DBG_FSM_CH_14_LEN    3
#define CMDLST_DBG_FSM_CH_14_OFFSET 24
#define CMDLST_RESERVED_5_LEN       1
#define CMDLST_RESERVED_5_OFFSET    23
#define CMDLST_DBG_FSM_CH_13_LEN    3
#define CMDLST_DBG_FSM_CH_13_OFFSET 20
#define CMDLST_RESERVED_4_LEN       1
#define CMDLST_RESERVED_4_OFFSET    19
#define CMDLST_DBG_FSM_CH_12_LEN    3
#define CMDLST_DBG_FSM_CH_12_OFFSET 16
#define CMDLST_RESERVED_3_LEN       1
#define CMDLST_RESERVED_3_OFFSET    15
#define CMDLST_DBG_FSM_CH_11_LEN    3
#define CMDLST_DBG_FSM_CH_11_OFFSET 12
#define CMDLST_RESERVED_2_LEN       1
#define CMDLST_RESERVED_2_OFFSET    11
#define CMDLST_DBG_FSM_CH_10_LEN    3
#define CMDLST_DBG_FSM_CH_10_OFFSET 8
#define CMDLST_RESERVED_1_LEN       1
#define CMDLST_RESERVED_1_OFFSET    7
#define CMDLST_DBG_FSM_CH_9_LEN     3
#define CMDLST_DBG_FSM_CH_9_OFFSET  4
#define CMDLST_RESERVED_0_LEN       1
#define CMDLST_RESERVED_0_OFFSET    3
#define CMDLST_DBG_FSM_CH_8_LEN     3
#define CMDLST_DBG_FSM_CH_8_OFFSET  0

#define CMDLST_RESERVED_0_LEN      11
#define CMDLST_RESERVED_0_OFFSET   21
#define CMDLST_LAST_LB_ADDR_LEN    21
#define CMDLST_LAST_LB_ADDR_OFFSET 0

#define CMDLST_RESERVED_0_LEN        29
#define CMDLST_RESERVED_0_OFFSET     3
#define CMDLST_VCD_OUT_SELECT_LEN    3
#define CMDLST_VCD_OUT_SELECT_OFFSET 0

#define CMDLST_RESERVED_0_0_LEN                 23
#define CMDLST_RESERVED_0_0_OFFSET              9
#define CMDLST_NRT_CHANNEL_0_LEN                1
#define CMDLST_NRT_CHANNEL_0_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_0_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_0_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_0_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_0_OFFSET        0

#define CMDLST_RESERVED_0_1_LEN                 23
#define CMDLST_RESERVED_0_1_OFFSET              9
#define CMDLST_NRT_CHANNEL_1_LEN                1
#define CMDLST_NRT_CHANNEL_1_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_1_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_1_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_1_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_1_OFFSET        0

#define CMDLST_RESERVED_0_2_LEN                 23
#define CMDLST_RESERVED_0_2_OFFSET              9
#define CMDLST_NRT_CHANNEL_2_LEN                1
#define CMDLST_NRT_CHANNEL_2_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_2_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_2_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_2_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_2_OFFSET        0

#define CMDLST_RESERVED_0_3_LEN                 23
#define CMDLST_RESERVED_0_3_OFFSET              9
#define CMDLST_NRT_CHANNEL_3_LEN                1
#define CMDLST_NRT_CHANNEL_3_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_3_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_3_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_3_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_3_OFFSET        0

#define CMDLST_RESERVED_0_4_LEN                 23
#define CMDLST_RESERVED_0_4_OFFSET              9
#define CMDLST_NRT_CHANNEL_4_LEN                1
#define CMDLST_NRT_CHANNEL_4_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_4_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_4_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_4_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_4_OFFSET        0

#define CMDLST_RESERVED_0_5_LEN                 23
#define CMDLST_RESERVED_0_5_OFFSET              9
#define CMDLST_NRT_CHANNEL_5_LEN                1
#define CMDLST_NRT_CHANNEL_5_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_5_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_5_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_5_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_5_OFFSET        0

#define CMDLST_RESERVED_0_6_LEN                 23
#define CMDLST_RESERVED_0_6_OFFSET              9
#define CMDLST_NRT_CHANNEL_6_LEN                1
#define CMDLST_NRT_CHANNEL_6_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_6_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_6_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_6_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_6_OFFSET        0

#define CMDLST_RESERVED_0_7_LEN                 23
#define CMDLST_RESERVED_0_7_OFFSET              9
#define CMDLST_NRT_CHANNEL_7_LEN                1
#define CMDLST_NRT_CHANNEL_7_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_7_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_7_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_7_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_7_OFFSET        0

#define CMDLST_RESERVED_0_8_LEN                 23
#define CMDLST_RESERVED_0_8_OFFSET              9
#define CMDLST_NRT_CHANNEL_8_LEN                1
#define CMDLST_NRT_CHANNEL_8_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_8_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_8_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_8_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_8_OFFSET        0

#define CMDLST_RESERVED_0_9_LEN                 23
#define CMDLST_RESERVED_0_9_OFFSET              9
#define CMDLST_NRT_CHANNEL_9_LEN                1
#define CMDLST_NRT_CHANNEL_9_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_9_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_9_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_9_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_9_OFFSET        0

#define CMDLST_RESERVED_0_10_LEN                 23
#define CMDLST_RESERVED_0_10_OFFSET              9
#define CMDLST_NRT_CHANNEL_10_LEN                1
#define CMDLST_NRT_CHANNEL_10_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_10_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_10_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_10_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_10_OFFSET        0

#define CMDLST_RESERVED_0_11_LEN                 23
#define CMDLST_RESERVED_0_11_OFFSET              9
#define CMDLST_NRT_CHANNEL_11_LEN                1
#define CMDLST_NRT_CHANNEL_11_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_11_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_11_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_11_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_11_OFFSET        0

#define CMDLST_RESERVED_0_12_LEN                 23
#define CMDLST_RESERVED_0_12_OFFSET              9
#define CMDLST_NRT_CHANNEL_12_LEN                1
#define CMDLST_NRT_CHANNEL_12_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_12_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_12_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_12_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_12_OFFSET        0

#define CMDLST_RESERVED_0_13_LEN                 23
#define CMDLST_RESERVED_0_13_OFFSET              9
#define CMDLST_NRT_CHANNEL_13_LEN                1
#define CMDLST_NRT_CHANNEL_13_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_13_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_13_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_13_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_13_OFFSET        0

#define CMDLST_RESERVED_0_14_LEN                 23
#define CMDLST_RESERVED_0_14_OFFSET              9
#define CMDLST_NRT_CHANNEL_14_LEN                1
#define CMDLST_NRT_CHANNEL_14_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_14_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_14_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_14_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_14_OFFSET        0

#define CMDLST_SW_PRIORITY_0_LEN          1
#define CMDLST_SW_PRIORITY_0_OFFSET       31
#define CMDLST_SW_RESOURCE_0_LEN          23
#define CMDLST_SW_RESOURCE_0_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_0_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_0_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_0_LEN      4
#define CMDLST_SW_LINK_CHANNEL_0_OFFSET   0

#define CMDLST_SW_PRIORITY_1_LEN          1
#define CMDLST_SW_PRIORITY_1_OFFSET       31
#define CMDLST_SW_RESOURCE_1_LEN          23
#define CMDLST_SW_RESOURCE_1_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_1_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_1_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_1_LEN      4
#define CMDLST_SW_LINK_CHANNEL_1_OFFSET   0

#define CMDLST_SW_PRIORITY_2_LEN          1
#define CMDLST_SW_PRIORITY_2_OFFSET       31
#define CMDLST_SW_RESOURCE_2_LEN          23
#define CMDLST_SW_RESOURCE_2_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_2_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_2_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_2_LEN      4
#define CMDLST_SW_LINK_CHANNEL_2_OFFSET   0

#define CMDLST_SW_PRIORITY_3_LEN          1
#define CMDLST_SW_PRIORITY_3_OFFSET       31
#define CMDLST_SW_RESOURCE_3_LEN          23
#define CMDLST_SW_RESOURCE_3_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_3_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_3_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_3_LEN      4
#define CMDLST_SW_LINK_CHANNEL_3_OFFSET   0

#define CMDLST_SW_PRIORITY_4_LEN          1
#define CMDLST_SW_PRIORITY_4_OFFSET       31
#define CMDLST_SW_RESOURCE_4_LEN          23
#define CMDLST_SW_RESOURCE_4_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_4_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_4_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_4_LEN      4
#define CMDLST_SW_LINK_CHANNEL_4_OFFSET   0

#define CMDLST_SW_PRIORITY_5_LEN          1
#define CMDLST_SW_PRIORITY_5_OFFSET       31
#define CMDLST_SW_RESOURCE_5_LEN          23
#define CMDLST_SW_RESOURCE_5_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_5_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_5_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_5_LEN      4
#define CMDLST_SW_LINK_CHANNEL_5_OFFSET   0

#define CMDLST_SW_PRIORITY_6_LEN          1
#define CMDLST_SW_PRIORITY_6_OFFSET       31
#define CMDLST_SW_RESOURCE_6_LEN          23
#define CMDLST_SW_RESOURCE_6_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_6_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_6_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_6_LEN      4
#define CMDLST_SW_LINK_CHANNEL_6_OFFSET   0

#define CMDLST_SW_PRIORITY_7_LEN          1
#define CMDLST_SW_PRIORITY_7_OFFSET       31
#define CMDLST_SW_RESOURCE_7_LEN          23
#define CMDLST_SW_RESOURCE_7_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_7_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_7_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_7_LEN      4
#define CMDLST_SW_LINK_CHANNEL_7_OFFSET   0

#define CMDLST_SW_PRIORITY_8_LEN          1
#define CMDLST_SW_PRIORITY_8_OFFSET       31
#define CMDLST_SW_RESOURCE_8_LEN          23
#define CMDLST_SW_RESOURCE_8_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_8_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_8_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_8_LEN      4
#define CMDLST_SW_LINK_CHANNEL_8_OFFSET   0

#define CMDLST_SW_PRIORITY_9_LEN          1
#define CMDLST_SW_PRIORITY_9_OFFSET       31
#define CMDLST_SW_RESOURCE_9_LEN          23
#define CMDLST_SW_RESOURCE_9_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_9_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_9_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_9_LEN      4
#define CMDLST_SW_LINK_CHANNEL_9_OFFSET   0

#define CMDLST_SW_PRIORITY_10_LEN          1
#define CMDLST_SW_PRIORITY_10_OFFSET       31
#define CMDLST_SW_RESOURCE_10_LEN          23
#define CMDLST_SW_RESOURCE_10_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_10_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_10_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_10_LEN      4
#define CMDLST_SW_LINK_CHANNEL_10_OFFSET   0

#define CMDLST_SW_PRIORITY_11_LEN          1
#define CMDLST_SW_PRIORITY_11_OFFSET       31
#define CMDLST_SW_RESOURCE_11_LEN          23
#define CMDLST_SW_RESOURCE_11_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_11_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_11_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_11_LEN      4
#define CMDLST_SW_LINK_CHANNEL_11_OFFSET   0

#define CMDLST_SW_PRIORITY_12_LEN          1
#define CMDLST_SW_PRIORITY_12_OFFSET       31
#define CMDLST_SW_RESOURCE_12_LEN          23
#define CMDLST_SW_RESOURCE_12_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_12_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_12_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_12_LEN      4
#define CMDLST_SW_LINK_CHANNEL_12_OFFSET   0

#define CMDLST_SW_PRIORITY_13_LEN          1
#define CMDLST_SW_PRIORITY_13_OFFSET       31
#define CMDLST_SW_RESOURCE_13_LEN          23
#define CMDLST_SW_RESOURCE_13_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_13_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_13_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_13_LEN      4
#define CMDLST_SW_LINK_CHANNEL_13_OFFSET   0

#define CMDLST_SW_PRIORITY_14_LEN          1
#define CMDLST_SW_PRIORITY_14_OFFSET       31
#define CMDLST_SW_RESOURCE_14_LEN          23
#define CMDLST_SW_RESOURCE_14_OFFSET       8
#define CMDLST_SW_LINK_TOKEN_NBR_14_LEN    4
#define CMDLST_SW_LINK_TOKEN_NBR_14_OFFSET 4
#define CMDLST_SW_LINK_CHANNEL_14_LEN      4
#define CMDLST_SW_LINK_CHANNEL_14_OFFSET   0

#define CMDLST_RESERVED_SW_2_0_LEN         6
#define CMDLST_RESERVED_SW_2_0_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_0_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_0_OFFSET    24
#define CMDLST_RESERVED_SW_1_0_LEN         3
#define CMDLST_RESERVED_SW_1_0_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_0_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_0_OFFSET 2
#define CMDLST_RESERVED_SW_0_0_LEN         2
#define CMDLST_RESERVED_SW_0_0_OFFSET      0

#define CMDLST_RESERVED_SW_2_1_LEN         6
#define CMDLST_RESERVED_SW_2_1_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_1_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_1_OFFSET    24
#define CMDLST_RESERVED_SW_1_1_LEN         3
#define CMDLST_RESERVED_SW_1_1_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_1_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_1_OFFSET 2
#define CMDLST_RESERVED_SW_0_1_LEN         2
#define CMDLST_RESERVED_SW_0_1_OFFSET      0

#define CMDLST_RESERVED_SW_2_2_LEN         6
#define CMDLST_RESERVED_SW_2_2_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_2_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_2_OFFSET    24
#define CMDLST_RESERVED_SW_1_2_LEN         3
#define CMDLST_RESERVED_SW_1_2_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_2_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_2_OFFSET 2
#define CMDLST_RESERVED_SW_0_2_LEN         2
#define CMDLST_RESERVED_SW_0_2_OFFSET      0

#define CMDLST_RESERVED_SW_2_3_LEN         6
#define CMDLST_RESERVED_SW_2_3_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_3_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_3_OFFSET    24
#define CMDLST_RESERVED_SW_1_3_LEN         3
#define CMDLST_RESERVED_SW_1_3_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_3_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_3_OFFSET 2
#define CMDLST_RESERVED_SW_0_3_LEN         2
#define CMDLST_RESERVED_SW_0_3_OFFSET      0

#define CMDLST_RESERVED_SW_2_4_LEN         6
#define CMDLST_RESERVED_SW_2_4_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_4_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_4_OFFSET    24
#define CMDLST_RESERVED_SW_1_4_LEN         3
#define CMDLST_RESERVED_SW_1_4_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_4_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_4_OFFSET 2
#define CMDLST_RESERVED_SW_0_4_LEN         2
#define CMDLST_RESERVED_SW_0_4_OFFSET      0

#define CMDLST_RESERVED_SW_2_5_LEN         6
#define CMDLST_RESERVED_SW_2_5_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_5_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_5_OFFSET    24
#define CMDLST_RESERVED_SW_1_5_LEN         3
#define CMDLST_RESERVED_SW_1_5_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_5_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_5_OFFSET 2
#define CMDLST_RESERVED_SW_0_5_LEN         2
#define CMDLST_RESERVED_SW_0_5_OFFSET      0

#define CMDLST_RESERVED_SW_2_6_LEN         6
#define CMDLST_RESERVED_SW_2_6_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_6_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_6_OFFSET    24
#define CMDLST_RESERVED_SW_1_6_LEN         3
#define CMDLST_RESERVED_SW_1_6_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_6_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_6_OFFSET 2
#define CMDLST_RESERVED_SW_0_6_LEN         2
#define CMDLST_RESERVED_SW_0_6_OFFSET      0

#define CMDLST_RESERVED_SW_2_7_LEN         6
#define CMDLST_RESERVED_SW_2_7_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_7_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_7_OFFSET    24
#define CMDLST_RESERVED_SW_1_7_LEN         3
#define CMDLST_RESERVED_SW_1_7_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_7_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_7_OFFSET 2
#define CMDLST_RESERVED_SW_0_7_LEN         2
#define CMDLST_RESERVED_SW_0_7_OFFSET      0

#define CMDLST_RESERVED_SW_2_8_LEN         6
#define CMDLST_RESERVED_SW_2_8_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_8_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_8_OFFSET    24
#define CMDLST_RESERVED_SW_1_8_LEN         3
#define CMDLST_RESERVED_SW_1_8_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_8_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_8_OFFSET 2
#define CMDLST_RESERVED_SW_0_8_LEN         2
#define CMDLST_RESERVED_SW_0_8_OFFSET      0

#define CMDLST_RESERVED_SW_2_9_LEN         6
#define CMDLST_RESERVED_SW_2_9_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_9_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_9_OFFSET    24
#define CMDLST_RESERVED_SW_1_9_LEN         3
#define CMDLST_RESERVED_SW_1_9_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_9_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_9_OFFSET 2
#define CMDLST_RESERVED_SW_0_9_LEN         2
#define CMDLST_RESERVED_SW_0_9_OFFSET      0

#define CMDLST_RESERVED_SW_2_10_LEN         6
#define CMDLST_RESERVED_SW_2_10_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_10_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_10_OFFSET    24
#define CMDLST_RESERVED_SW_1_10_LEN         3
#define CMDLST_RESERVED_SW_1_10_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_10_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_10_OFFSET 2
#define CMDLST_RESERVED_SW_0_10_LEN         2
#define CMDLST_RESERVED_SW_0_10_OFFSET      0

#define CMDLST_RESERVED_SW_2_11_LEN         6
#define CMDLST_RESERVED_SW_2_11_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_11_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_11_OFFSET    24
#define CMDLST_RESERVED_SW_1_11_LEN         3
#define CMDLST_RESERVED_SW_1_11_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_11_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_11_OFFSET 2
#define CMDLST_RESERVED_SW_0_11_LEN         2
#define CMDLST_RESERVED_SW_0_11_OFFSET      0

#define CMDLST_RESERVED_SW_2_12_LEN         6
#define CMDLST_RESERVED_SW_2_12_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_12_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_12_OFFSET    24
#define CMDLST_RESERVED_SW_1_12_LEN         3
#define CMDLST_RESERVED_SW_1_12_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_12_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_12_OFFSET 2
#define CMDLST_RESERVED_SW_0_12_LEN         2
#define CMDLST_RESERVED_SW_0_12_OFFSET      0

#define CMDLST_RESERVED_SW_2_13_LEN         6
#define CMDLST_RESERVED_SW_2_13_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_13_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_13_OFFSET    24
#define CMDLST_RESERVED_SW_1_13_LEN         3
#define CMDLST_RESERVED_SW_1_13_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_13_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_13_OFFSET 2
#define CMDLST_RESERVED_SW_0_13_LEN         2
#define CMDLST_RESERVED_SW_0_13_OFFSET      0

#define CMDLST_RESERVED_SW_2_14_LEN         6
#define CMDLST_RESERVED_SW_2_14_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_14_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_14_OFFSET    24
#define CMDLST_RESERVED_SW_1_14_LEN         3
#define CMDLST_RESERVED_SW_1_14_OFFSET      21
#define CMDLST_SW_CVDR_RD_ADDRESS_14_LEN    19
#define CMDLST_SW_CVDR_RD_ADDRESS_14_OFFSET 2
#define CMDLST_RESERVED_SW_0_14_LEN         2
#define CMDLST_RESERVED_SW_0_14_OFFSET      0

#define CMDLST_VPRD_LAST_PAGE_0_LEN          19
#define CMDLST_VPRD_LAST_PAGE_0_OFFSET       13
#define CMDLST_RESERVED_0_0_LEN              3
#define CMDLST_RESERVED_0_0_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_0_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_0_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_0_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_0_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_0_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_0_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_1_LEN          19
#define CMDLST_VPRD_LAST_PAGE_1_OFFSET       13
#define CMDLST_RESERVED_0_1_LEN              3
#define CMDLST_RESERVED_0_1_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_1_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_1_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_1_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_1_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_1_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_1_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_2_LEN          19
#define CMDLST_VPRD_LAST_PAGE_2_OFFSET       13
#define CMDLST_RESERVED_0_2_LEN              3
#define CMDLST_RESERVED_0_2_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_2_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_2_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_2_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_2_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_2_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_2_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_3_LEN          19
#define CMDLST_VPRD_LAST_PAGE_3_OFFSET       13
#define CMDLST_RESERVED_0_3_LEN              3
#define CMDLST_RESERVED_0_3_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_3_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_3_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_3_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_3_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_3_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_3_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_4_LEN          19
#define CMDLST_VPRD_LAST_PAGE_4_OFFSET       13
#define CMDLST_RESERVED_0_4_LEN              3
#define CMDLST_RESERVED_0_4_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_4_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_4_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_4_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_4_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_4_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_4_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_5_LEN          19
#define CMDLST_VPRD_LAST_PAGE_5_OFFSET       13
#define CMDLST_RESERVED_0_5_LEN              3
#define CMDLST_RESERVED_0_5_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_5_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_5_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_5_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_5_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_5_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_5_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_6_LEN          19
#define CMDLST_VPRD_LAST_PAGE_6_OFFSET       13
#define CMDLST_RESERVED_0_6_LEN              3
#define CMDLST_RESERVED_0_6_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_6_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_6_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_6_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_6_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_6_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_6_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_7_LEN          19
#define CMDLST_VPRD_LAST_PAGE_7_OFFSET       13
#define CMDLST_RESERVED_0_7_LEN              3
#define CMDLST_RESERVED_0_7_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_7_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_7_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_7_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_7_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_7_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_7_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_8_LEN          19
#define CMDLST_VPRD_LAST_PAGE_8_OFFSET       13
#define CMDLST_RESERVED_0_8_LEN              3
#define CMDLST_RESERVED_0_8_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_8_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_8_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_8_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_8_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_8_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_8_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_9_LEN          19
#define CMDLST_VPRD_LAST_PAGE_9_OFFSET       13
#define CMDLST_RESERVED_0_9_LEN              3
#define CMDLST_RESERVED_0_9_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_9_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_9_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_9_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_9_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_9_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_9_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_10_LEN          19
#define CMDLST_VPRD_LAST_PAGE_10_OFFSET       13
#define CMDLST_RESERVED_0_10_LEN              3
#define CMDLST_RESERVED_0_10_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_10_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_10_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_10_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_10_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_10_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_10_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_11_LEN          19
#define CMDLST_VPRD_LAST_PAGE_11_OFFSET       13
#define CMDLST_RESERVED_0_11_LEN              3
#define CMDLST_RESERVED_0_11_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_11_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_11_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_11_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_11_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_11_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_11_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_12_LEN          19
#define CMDLST_VPRD_LAST_PAGE_12_OFFSET       13
#define CMDLST_RESERVED_0_12_LEN              3
#define CMDLST_RESERVED_0_12_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_12_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_12_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_12_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_12_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_12_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_12_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_13_LEN          19
#define CMDLST_VPRD_LAST_PAGE_13_OFFSET       13
#define CMDLST_RESERVED_0_13_LEN              3
#define CMDLST_RESERVED_0_13_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_13_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_13_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_13_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_13_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_13_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_13_OFFSET    0

#define CMDLST_VPRD_LAST_PAGE_14_LEN          19
#define CMDLST_VPRD_LAST_PAGE_14_OFFSET       13
#define CMDLST_RESERVED_0_14_LEN              3
#define CMDLST_RESERVED_0_14_OFFSET           10
#define CMDLST_VPRD_ALLOCATED_DU_14_LEN       5
#define CMDLST_VPRD_ALLOCATED_DU_14_OFFSET    5
#define CMDLST_VPRD_PIXEL_EXPANSION_14_LEN    1
#define CMDLST_VPRD_PIXEL_EXPANSION_14_OFFSET 4
#define CMDLST_VPRD_PIXEL_FORMAT_14_LEN       4
#define CMDLST_VPRD_PIXEL_FORMAT_14_OFFSET    0

#define CMDLST_RESERVED_1_1_0_LEN                8
#define CMDLST_RESERVED_1_1_0_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_0_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_0_OFFSET 16
#define CMDLST_RESERVED_1_0_0_LEN                3
#define CMDLST_RESERVED_1_0_0_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_0_LEN              13
#define CMDLST_VPRD_LINE_SIZE_0_OFFSET           0

#define CMDLST_RESERVED_1_1_1_LEN                8
#define CMDLST_RESERVED_1_1_1_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_1_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_1_OFFSET 16
#define CMDLST_RESERVED_1_0_1_LEN                3
#define CMDLST_RESERVED_1_0_1_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_1_LEN              13
#define CMDLST_VPRD_LINE_SIZE_1_OFFSET           0

#define CMDLST_RESERVED_1_1_2_LEN                8
#define CMDLST_RESERVED_1_1_2_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_2_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_2_OFFSET 16
#define CMDLST_RESERVED_1_0_2_LEN                3
#define CMDLST_RESERVED_1_0_2_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_2_LEN              13
#define CMDLST_VPRD_LINE_SIZE_2_OFFSET           0

#define CMDLST_RESERVED_1_1_3_LEN                8
#define CMDLST_RESERVED_1_1_3_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_3_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_3_OFFSET 16
#define CMDLST_RESERVED_1_0_3_LEN                3
#define CMDLST_RESERVED_1_0_3_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_3_LEN              13
#define CMDLST_VPRD_LINE_SIZE_3_OFFSET           0

#define CMDLST_RESERVED_1_1_4_LEN                8
#define CMDLST_RESERVED_1_1_4_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_4_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_4_OFFSET 16
#define CMDLST_RESERVED_1_0_4_LEN                3
#define CMDLST_RESERVED_1_0_4_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_4_LEN              13
#define CMDLST_VPRD_LINE_SIZE_4_OFFSET           0

#define CMDLST_RESERVED_1_1_5_LEN                8
#define CMDLST_RESERVED_1_1_5_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_5_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_5_OFFSET 16
#define CMDLST_RESERVED_1_0_5_LEN                3
#define CMDLST_RESERVED_1_0_5_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_5_LEN              13
#define CMDLST_VPRD_LINE_SIZE_5_OFFSET           0

#define CMDLST_RESERVED_1_1_6_LEN                8
#define CMDLST_RESERVED_1_1_6_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_6_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_6_OFFSET 16
#define CMDLST_RESERVED_1_0_6_LEN                3
#define CMDLST_RESERVED_1_0_6_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_6_LEN              13
#define CMDLST_VPRD_LINE_SIZE_6_OFFSET           0

#define CMDLST_RESERVED_1_1_7_LEN                8
#define CMDLST_RESERVED_1_1_7_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_7_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_7_OFFSET 16
#define CMDLST_RESERVED_1_0_7_LEN                3
#define CMDLST_RESERVED_1_0_7_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_7_LEN              13
#define CMDLST_VPRD_LINE_SIZE_7_OFFSET           0

#define CMDLST_RESERVED_1_1_8_LEN                8
#define CMDLST_RESERVED_1_1_8_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_8_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_8_OFFSET 16
#define CMDLST_RESERVED_1_0_8_LEN                3
#define CMDLST_RESERVED_1_0_8_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_8_LEN              13
#define CMDLST_VPRD_LINE_SIZE_8_OFFSET           0

#define CMDLST_RESERVED_1_1_9_LEN                8
#define CMDLST_RESERVED_1_1_9_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_9_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_9_OFFSET 16
#define CMDLST_RESERVED_1_0_9_LEN                3
#define CMDLST_RESERVED_1_0_9_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_9_LEN              13
#define CMDLST_VPRD_LINE_SIZE_9_OFFSET           0

#define CMDLST_RESERVED_1_1_10_LEN                8
#define CMDLST_RESERVED_1_1_10_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_10_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_10_OFFSET 16
#define CMDLST_RESERVED_1_0_10_LEN                3
#define CMDLST_RESERVED_1_0_10_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_10_LEN              13
#define CMDLST_VPRD_LINE_SIZE_10_OFFSET           0

#define CMDLST_RESERVED_1_1_11_LEN                8
#define CMDLST_RESERVED_1_1_11_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_11_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_11_OFFSET 16
#define CMDLST_RESERVED_1_0_11_LEN                3
#define CMDLST_RESERVED_1_0_11_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_11_LEN              13
#define CMDLST_VPRD_LINE_SIZE_11_OFFSET           0

#define CMDLST_RESERVED_1_1_12_LEN                8
#define CMDLST_RESERVED_1_1_12_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_12_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_12_OFFSET 16
#define CMDLST_RESERVED_1_0_12_LEN                3
#define CMDLST_RESERVED_1_0_12_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_12_LEN              13
#define CMDLST_VPRD_LINE_SIZE_12_OFFSET           0

#define CMDLST_RESERVED_1_1_13_LEN                8
#define CMDLST_RESERVED_1_1_13_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_13_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_13_OFFSET 16
#define CMDLST_RESERVED_1_0_13_LEN                3
#define CMDLST_RESERVED_1_0_13_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_13_LEN              13
#define CMDLST_VPRD_LINE_SIZE_13_OFFSET           0

#define CMDLST_RESERVED_1_1_14_LEN                8
#define CMDLST_RESERVED_1_1_14_OFFSET             24
#define CMDLST_VPRD_HORIZONTAL_BLANKING_14_LEN    8
#define CMDLST_VPRD_HORIZONTAL_BLANKING_14_OFFSET 16
#define CMDLST_RESERVED_1_0_14_LEN                3
#define CMDLST_RESERVED_1_0_14_OFFSET             13
#define CMDLST_VPRD_LINE_SIZE_14_LEN              13
#define CMDLST_VPRD_LINE_SIZE_14_OFFSET           0

#define CMDLST_RESERVED_2_1_0_LEN              8
#define CMDLST_RESERVED_2_1_0_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_0_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_0_OFFSET 16
#define CMDLST_RESERVED_2_0_0_LEN              3
#define CMDLST_RESERVED_2_0_0_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_0_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_0_OFFSET        0

#define CMDLST_RESERVED_2_1_1_LEN              8
#define CMDLST_RESERVED_2_1_1_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_1_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_1_OFFSET 16
#define CMDLST_RESERVED_2_0_1_LEN              3
#define CMDLST_RESERVED_2_0_1_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_1_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_1_OFFSET        0

#define CMDLST_RESERVED_2_1_2_LEN              8
#define CMDLST_RESERVED_2_1_2_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_2_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_2_OFFSET 16
#define CMDLST_RESERVED_2_0_2_LEN              3
#define CMDLST_RESERVED_2_0_2_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_2_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_2_OFFSET        0

#define CMDLST_RESERVED_2_1_3_LEN              8
#define CMDLST_RESERVED_2_1_3_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_3_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_3_OFFSET 16
#define CMDLST_RESERVED_2_0_3_LEN              3
#define CMDLST_RESERVED_2_0_3_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_3_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_3_OFFSET        0

#define CMDLST_RESERVED_2_1_4_LEN              8
#define CMDLST_RESERVED_2_1_4_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_4_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_4_OFFSET 16
#define CMDLST_RESERVED_2_0_4_LEN              3
#define CMDLST_RESERVED_2_0_4_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_4_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_4_OFFSET        0

#define CMDLST_RESERVED_2_1_5_LEN              8
#define CMDLST_RESERVED_2_1_5_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_5_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_5_OFFSET 16
#define CMDLST_RESERVED_2_0_5_LEN              3
#define CMDLST_RESERVED_2_0_5_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_5_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_5_OFFSET        0

#define CMDLST_RESERVED_2_1_6_LEN              8
#define CMDLST_RESERVED_2_1_6_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_6_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_6_OFFSET 16
#define CMDLST_RESERVED_2_0_6_LEN              3
#define CMDLST_RESERVED_2_0_6_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_6_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_6_OFFSET        0

#define CMDLST_RESERVED_2_1_7_LEN              8
#define CMDLST_RESERVED_2_1_7_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_7_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_7_OFFSET 16
#define CMDLST_RESERVED_2_0_7_LEN              3
#define CMDLST_RESERVED_2_0_7_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_7_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_7_OFFSET        0

#define CMDLST_RESERVED_2_1_8_LEN              8
#define CMDLST_RESERVED_2_1_8_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_8_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_8_OFFSET 16
#define CMDLST_RESERVED_2_0_8_LEN              3
#define CMDLST_RESERVED_2_0_8_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_8_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_8_OFFSET        0

#define CMDLST_RESERVED_2_1_9_LEN              8
#define CMDLST_RESERVED_2_1_9_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_9_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_9_OFFSET 16
#define CMDLST_RESERVED_2_0_9_LEN              3
#define CMDLST_RESERVED_2_0_9_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_9_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_9_OFFSET        0

#define CMDLST_RESERVED_2_1_10_LEN              8
#define CMDLST_RESERVED_2_1_10_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_10_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_10_OFFSET 16
#define CMDLST_RESERVED_2_0_10_LEN              3
#define CMDLST_RESERVED_2_0_10_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_10_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_10_OFFSET        0

#define CMDLST_RESERVED_2_1_11_LEN              8
#define CMDLST_RESERVED_2_1_11_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_11_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_11_OFFSET 16
#define CMDLST_RESERVED_2_0_11_LEN              3
#define CMDLST_RESERVED_2_0_11_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_11_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_11_OFFSET        0

#define CMDLST_RESERVED_2_1_12_LEN              8
#define CMDLST_RESERVED_2_1_12_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_12_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_12_OFFSET 16
#define CMDLST_RESERVED_2_0_12_LEN              3
#define CMDLST_RESERVED_2_0_12_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_12_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_12_OFFSET        0

#define CMDLST_RESERVED_2_1_13_LEN              8
#define CMDLST_RESERVED_2_1_13_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_13_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_13_OFFSET 16
#define CMDLST_RESERVED_2_0_13_LEN              3
#define CMDLST_RESERVED_2_0_13_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_13_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_13_OFFSET        0

#define CMDLST_RESERVED_2_1_14_LEN              8
#define CMDLST_RESERVED_2_1_14_OFFSET           24
#define CMDLST_VPRD_VERTICAL_BLANKING_14_LEN    8
#define CMDLST_VPRD_VERTICAL_BLANKING_14_OFFSET 16
#define CMDLST_RESERVED_2_0_14_LEN              3
#define CMDLST_RESERVED_2_0_14_OFFSET           13
#define CMDLST_VPRD_FRAME_SIZE_14_LEN           13
#define CMDLST_VPRD_FRAME_SIZE_14_OFFSET        0

#define CMDLST_VPRD_AXI_FRAME_START_0_0_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_0_OFFSET 2
#define CMDLST_RESERVED_3_0_0_LEN              2
#define CMDLST_RESERVED_3_0_0_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_1_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_1_OFFSET 2
#define CMDLST_RESERVED_3_0_1_LEN              2
#define CMDLST_RESERVED_3_0_1_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_2_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_2_OFFSET 2
#define CMDLST_RESERVED_3_0_2_LEN              2
#define CMDLST_RESERVED_3_0_2_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_3_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_3_OFFSET 2
#define CMDLST_RESERVED_3_0_3_LEN              2
#define CMDLST_RESERVED_3_0_3_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_4_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_4_OFFSET 2
#define CMDLST_RESERVED_3_0_4_LEN              2
#define CMDLST_RESERVED_3_0_4_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_5_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_5_OFFSET 2
#define CMDLST_RESERVED_3_0_5_LEN              2
#define CMDLST_RESERVED_3_0_5_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_6_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_6_OFFSET 2
#define CMDLST_RESERVED_3_0_6_LEN              2
#define CMDLST_RESERVED_3_0_6_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_7_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_7_OFFSET 2
#define CMDLST_RESERVED_3_0_7_LEN              2
#define CMDLST_RESERVED_3_0_7_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_8_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_8_OFFSET 2
#define CMDLST_RESERVED_3_0_8_LEN              2
#define CMDLST_RESERVED_3_0_8_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_9_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_9_OFFSET 2
#define CMDLST_RESERVED_3_0_9_LEN              2
#define CMDLST_RESERVED_3_0_9_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_10_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_10_OFFSET 2
#define CMDLST_RESERVED_3_0_10_LEN              2
#define CMDLST_RESERVED_3_0_10_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_11_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_11_OFFSET 2
#define CMDLST_RESERVED_3_0_11_LEN              2
#define CMDLST_RESERVED_3_0_11_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_12_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_12_OFFSET 2
#define CMDLST_RESERVED_3_0_12_LEN              2
#define CMDLST_RESERVED_3_0_12_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_13_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_13_OFFSET 2
#define CMDLST_RESERVED_3_0_13_LEN              2
#define CMDLST_RESERVED_3_0_13_OFFSET           0

#define CMDLST_VPRD_AXI_FRAME_START_0_14_LEN    30
#define CMDLST_VPRD_AXI_FRAME_START_0_14_OFFSET 2
#define CMDLST_RESERVED_3_0_14_LEN              2
#define CMDLST_RESERVED_3_0_14_OFFSET           0

#define CMDLST_RESERVED_0_0_LEN    31
#define CMDLST_RESERVED_0_0_OFFSET 1
#define CMDLST_BRANCHING_0_LEN     1
#define CMDLST_BRANCHING_0_OFFSET  0

#define CMDLST_RESERVED_0_1_LEN    31
#define CMDLST_RESERVED_0_1_OFFSET 1
#define CMDLST_BRANCHING_1_LEN     1
#define CMDLST_BRANCHING_1_OFFSET  0

#define CMDLST_RESERVED_0_2_LEN    31
#define CMDLST_RESERVED_0_2_OFFSET 1
#define CMDLST_BRANCHING_2_LEN     1
#define CMDLST_BRANCHING_2_OFFSET  0

#define CMDLST_RESERVED_0_3_LEN    31
#define CMDLST_RESERVED_0_3_OFFSET 1
#define CMDLST_BRANCHING_3_LEN     1
#define CMDLST_BRANCHING_3_OFFSET  0

#define CMDLST_RESERVED_0_4_LEN    31
#define CMDLST_RESERVED_0_4_OFFSET 1
#define CMDLST_BRANCHING_4_LEN     1
#define CMDLST_BRANCHING_4_OFFSET  0

#define CMDLST_RESERVED_0_5_LEN    31
#define CMDLST_RESERVED_0_5_OFFSET 1
#define CMDLST_BRANCHING_5_LEN     1
#define CMDLST_BRANCHING_5_OFFSET  0

#define CMDLST_RESERVED_0_6_LEN    31
#define CMDLST_RESERVED_0_6_OFFSET 1
#define CMDLST_BRANCHING_6_LEN     1
#define CMDLST_BRANCHING_6_OFFSET  0

#define CMDLST_RESERVED_0_7_LEN    31
#define CMDLST_RESERVED_0_7_OFFSET 1
#define CMDLST_BRANCHING_7_LEN     1
#define CMDLST_BRANCHING_7_OFFSET  0

#define CMDLST_RESERVED_0_8_LEN    31
#define CMDLST_RESERVED_0_8_OFFSET 1
#define CMDLST_BRANCHING_8_LEN     1
#define CMDLST_BRANCHING_8_OFFSET  0

#define CMDLST_RESERVED_0_9_LEN    31
#define CMDLST_RESERVED_0_9_OFFSET 1
#define CMDLST_BRANCHING_9_LEN     1
#define CMDLST_BRANCHING_9_OFFSET  0

#define CMDLST_RESERVED_0_10_LEN    31
#define CMDLST_RESERVED_0_10_OFFSET 1
#define CMDLST_BRANCHING_10_LEN     1
#define CMDLST_BRANCHING_10_OFFSET  0

#define CMDLST_RESERVED_0_11_LEN    31
#define CMDLST_RESERVED_0_11_OFFSET 1
#define CMDLST_BRANCHING_11_LEN     1
#define CMDLST_BRANCHING_11_OFFSET  0

#define CMDLST_RESERVED_0_12_LEN    31
#define CMDLST_RESERVED_0_12_OFFSET 1
#define CMDLST_BRANCHING_12_LEN     1
#define CMDLST_BRANCHING_12_OFFSET  0

#define CMDLST_RESERVED_0_13_LEN    31
#define CMDLST_RESERVED_0_13_OFFSET 1
#define CMDLST_BRANCHING_13_LEN     1
#define CMDLST_BRANCHING_13_OFFSET  0

#define CMDLST_RESERVED_0_14_LEN    31
#define CMDLST_RESERVED_0_14_OFFSET 1
#define CMDLST_BRANCHING_14_LEN     1
#define CMDLST_BRANCHING_14_OFFSET  0

#define CMDLST_SHADOWED_RD_DATA_3_0_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_0_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_1_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_1_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_2_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_2_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_3_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_3_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_4_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_4_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_5_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_5_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_6_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_6_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_7_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_7_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_8_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_8_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_9_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_9_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_10_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_10_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_11_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_11_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_12_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_12_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_13_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_13_OFFSET 0

#define CMDLST_SHADOWED_RD_DATA_3_14_LEN    32
#define CMDLST_SHADOWED_RD_DATA_3_14_OFFSET 0

#define CMDLST_HW_PRIORITY_0_LEN          1
#define CMDLST_HW_PRIORITY_0_OFFSET       31
#define CMDLST_HW_RESOURCE_0_LEN          23
#define CMDLST_HW_RESOURCE_0_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_0_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_0_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_0_LEN      4
#define CMDLST_HW_LINK_CHANNEL_0_OFFSET   0

#define CMDLST_HW_PRIORITY_1_LEN          1
#define CMDLST_HW_PRIORITY_1_OFFSET       31
#define CMDLST_HW_RESOURCE_1_LEN          23
#define CMDLST_HW_RESOURCE_1_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_1_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_1_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_1_LEN      4
#define CMDLST_HW_LINK_CHANNEL_1_OFFSET   0

#define CMDLST_HW_PRIORITY_2_LEN          1
#define CMDLST_HW_PRIORITY_2_OFFSET       31
#define CMDLST_HW_RESOURCE_2_LEN          23
#define CMDLST_HW_RESOURCE_2_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_2_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_2_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_2_LEN      4
#define CMDLST_HW_LINK_CHANNEL_2_OFFSET   0

#define CMDLST_HW_PRIORITY_3_LEN          1
#define CMDLST_HW_PRIORITY_3_OFFSET       31
#define CMDLST_HW_RESOURCE_3_LEN          23
#define CMDLST_HW_RESOURCE_3_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_3_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_3_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_3_LEN      4
#define CMDLST_HW_LINK_CHANNEL_3_OFFSET   0

#define CMDLST_HW_PRIORITY_4_LEN          1
#define CMDLST_HW_PRIORITY_4_OFFSET       31
#define CMDLST_HW_RESOURCE_4_LEN          23
#define CMDLST_HW_RESOURCE_4_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_4_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_4_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_4_LEN      4
#define CMDLST_HW_LINK_CHANNEL_4_OFFSET   0

#define CMDLST_HW_PRIORITY_5_LEN          1
#define CMDLST_HW_PRIORITY_5_OFFSET       31
#define CMDLST_HW_RESOURCE_5_LEN          23
#define CMDLST_HW_RESOURCE_5_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_5_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_5_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_5_LEN      4
#define CMDLST_HW_LINK_CHANNEL_5_OFFSET   0

#define CMDLST_HW_PRIORITY_6_LEN          1
#define CMDLST_HW_PRIORITY_6_OFFSET       31
#define CMDLST_HW_RESOURCE_6_LEN          23
#define CMDLST_HW_RESOURCE_6_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_6_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_6_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_6_LEN      4
#define CMDLST_HW_LINK_CHANNEL_6_OFFSET   0

#define CMDLST_HW_PRIORITY_7_LEN          1
#define CMDLST_HW_PRIORITY_7_OFFSET       31
#define CMDLST_HW_RESOURCE_7_LEN          23
#define CMDLST_HW_RESOURCE_7_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_7_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_7_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_7_LEN      4
#define CMDLST_HW_LINK_CHANNEL_7_OFFSET   0

#define CMDLST_HW_PRIORITY_8_LEN          1
#define CMDLST_HW_PRIORITY_8_OFFSET       31
#define CMDLST_HW_RESOURCE_8_LEN          23
#define CMDLST_HW_RESOURCE_8_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_8_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_8_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_8_LEN      4
#define CMDLST_HW_LINK_CHANNEL_8_OFFSET   0

#define CMDLST_HW_PRIORITY_9_LEN          1
#define CMDLST_HW_PRIORITY_9_OFFSET       31
#define CMDLST_HW_RESOURCE_9_LEN          23
#define CMDLST_HW_RESOURCE_9_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_9_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_9_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_9_LEN      4
#define CMDLST_HW_LINK_CHANNEL_9_OFFSET   0

#define CMDLST_HW_PRIORITY_10_LEN          1
#define CMDLST_HW_PRIORITY_10_OFFSET       31
#define CMDLST_HW_RESOURCE_10_LEN          23
#define CMDLST_HW_RESOURCE_10_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_10_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_10_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_10_LEN      4
#define CMDLST_HW_LINK_CHANNEL_10_OFFSET   0

#define CMDLST_HW_PRIORITY_11_LEN          1
#define CMDLST_HW_PRIORITY_11_OFFSET       31
#define CMDLST_HW_RESOURCE_11_LEN          23
#define CMDLST_HW_RESOURCE_11_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_11_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_11_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_11_LEN      4
#define CMDLST_HW_LINK_CHANNEL_11_OFFSET   0

#define CMDLST_HW_PRIORITY_12_LEN          1
#define CMDLST_HW_PRIORITY_12_OFFSET       31
#define CMDLST_HW_RESOURCE_12_LEN          23
#define CMDLST_HW_RESOURCE_12_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_12_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_12_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_12_LEN      4
#define CMDLST_HW_LINK_CHANNEL_12_OFFSET   0

#define CMDLST_HW_PRIORITY_13_LEN          1
#define CMDLST_HW_PRIORITY_13_OFFSET       31
#define CMDLST_HW_RESOURCE_13_LEN          23
#define CMDLST_HW_RESOURCE_13_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_13_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_13_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_13_LEN      4
#define CMDLST_HW_LINK_CHANNEL_13_OFFSET   0

#define CMDLST_HW_PRIORITY_14_LEN          1
#define CMDLST_HW_PRIORITY_14_OFFSET       31
#define CMDLST_HW_RESOURCE_14_LEN          23
#define CMDLST_HW_RESOURCE_14_OFFSET       8
#define CMDLST_HW_LINK_TOKEN_NBR_14_LEN    4
#define CMDLST_HW_LINK_TOKEN_NBR_14_OFFSET 4
#define CMDLST_HW_LINK_CHANNEL_14_LEN      4
#define CMDLST_HW_LINK_CHANNEL_14_OFFSET   0

#define CMDLST_RESERVED_HW_2_0_LEN         6
#define CMDLST_RESERVED_HW_2_0_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_0_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_0_OFFSET    24
#define CMDLST_RESERVED_HW_1_0_LEN         3
#define CMDLST_RESERVED_HW_1_0_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_0_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_0_OFFSET 2
#define CMDLST_RESERVED_HW_0_0_LEN         2
#define CMDLST_RESERVED_HW_0_0_OFFSET      0

#define CMDLST_RESERVED_HW_2_1_LEN         6
#define CMDLST_RESERVED_HW_2_1_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_1_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_1_OFFSET    24
#define CMDLST_RESERVED_HW_1_1_LEN         3
#define CMDLST_RESERVED_HW_1_1_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_1_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_1_OFFSET 2
#define CMDLST_RESERVED_HW_0_1_LEN         2
#define CMDLST_RESERVED_HW_0_1_OFFSET      0

#define CMDLST_RESERVED_HW_2_2_LEN         6
#define CMDLST_RESERVED_HW_2_2_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_2_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_2_OFFSET    24
#define CMDLST_RESERVED_HW_1_2_LEN         3
#define CMDLST_RESERVED_HW_1_2_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_2_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_2_OFFSET 2
#define CMDLST_RESERVED_HW_0_2_LEN         2
#define CMDLST_RESERVED_HW_0_2_OFFSET      0

#define CMDLST_RESERVED_HW_2_3_LEN         6
#define CMDLST_RESERVED_HW_2_3_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_3_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_3_OFFSET    24
#define CMDLST_RESERVED_HW_1_3_LEN         3
#define CMDLST_RESERVED_HW_1_3_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_3_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_3_OFFSET 2
#define CMDLST_RESERVED_HW_0_3_LEN         2
#define CMDLST_RESERVED_HW_0_3_OFFSET      0

#define CMDLST_RESERVED_HW_2_4_LEN         6
#define CMDLST_RESERVED_HW_2_4_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_4_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_4_OFFSET    24
#define CMDLST_RESERVED_HW_1_4_LEN         3
#define CMDLST_RESERVED_HW_1_4_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_4_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_4_OFFSET 2
#define CMDLST_RESERVED_HW_0_4_LEN         2
#define CMDLST_RESERVED_HW_0_4_OFFSET      0

#define CMDLST_RESERVED_HW_2_5_LEN         6
#define CMDLST_RESERVED_HW_2_5_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_5_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_5_OFFSET    24
#define CMDLST_RESERVED_HW_1_5_LEN         3
#define CMDLST_RESERVED_HW_1_5_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_5_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_5_OFFSET 2
#define CMDLST_RESERVED_HW_0_5_LEN         2
#define CMDLST_RESERVED_HW_0_5_OFFSET      0

#define CMDLST_RESERVED_HW_2_6_LEN         6
#define CMDLST_RESERVED_HW_2_6_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_6_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_6_OFFSET    24
#define CMDLST_RESERVED_HW_1_6_LEN         3
#define CMDLST_RESERVED_HW_1_6_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_6_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_6_OFFSET 2
#define CMDLST_RESERVED_HW_0_6_LEN         2
#define CMDLST_RESERVED_HW_0_6_OFFSET      0

#define CMDLST_RESERVED_HW_2_7_LEN         6
#define CMDLST_RESERVED_HW_2_7_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_7_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_7_OFFSET    24
#define CMDLST_RESERVED_HW_1_7_LEN         3
#define CMDLST_RESERVED_HW_1_7_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_7_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_7_OFFSET 2
#define CMDLST_RESERVED_HW_0_7_LEN         2
#define CMDLST_RESERVED_HW_0_7_OFFSET      0

#define CMDLST_RESERVED_HW_2_8_LEN         6
#define CMDLST_RESERVED_HW_2_8_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_8_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_8_OFFSET    24
#define CMDLST_RESERVED_HW_1_8_LEN         3
#define CMDLST_RESERVED_HW_1_8_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_8_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_8_OFFSET 2
#define CMDLST_RESERVED_HW_0_8_LEN         2
#define CMDLST_RESERVED_HW_0_8_OFFSET      0

#define CMDLST_RESERVED_HW_2_9_LEN         6
#define CMDLST_RESERVED_HW_2_9_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_9_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_9_OFFSET    24
#define CMDLST_RESERVED_HW_1_9_LEN         3
#define CMDLST_RESERVED_HW_1_9_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_9_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_9_OFFSET 2
#define CMDLST_RESERVED_HW_0_9_LEN         2
#define CMDLST_RESERVED_HW_0_9_OFFSET      0

#define CMDLST_RESERVED_HW_2_10_LEN         6
#define CMDLST_RESERVED_HW_2_10_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_10_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_10_OFFSET    24
#define CMDLST_RESERVED_HW_1_10_LEN         3
#define CMDLST_RESERVED_HW_1_10_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_10_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_10_OFFSET 2
#define CMDLST_RESERVED_HW_0_10_LEN         2
#define CMDLST_RESERVED_HW_0_10_OFFSET      0

#define CMDLST_RESERVED_HW_2_11_LEN         6
#define CMDLST_RESERVED_HW_2_11_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_11_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_11_OFFSET    24
#define CMDLST_RESERVED_HW_1_11_LEN         3
#define CMDLST_RESERVED_HW_1_11_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_11_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_11_OFFSET 2
#define CMDLST_RESERVED_HW_0_11_LEN         2
#define CMDLST_RESERVED_HW_0_11_OFFSET      0

#define CMDLST_RESERVED_HW_2_12_LEN         6
#define CMDLST_RESERVED_HW_2_12_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_12_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_12_OFFSET    24
#define CMDLST_RESERVED_HW_1_12_LEN         3
#define CMDLST_RESERVED_HW_1_12_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_12_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_12_OFFSET 2
#define CMDLST_RESERVED_HW_0_12_LEN         2
#define CMDLST_RESERVED_HW_0_12_OFFSET      0

#define CMDLST_RESERVED_HW_2_13_LEN         6
#define CMDLST_RESERVED_HW_2_13_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_13_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_13_OFFSET    24
#define CMDLST_RESERVED_HW_1_13_LEN         3
#define CMDLST_RESERVED_HW_1_13_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_13_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_13_OFFSET 2
#define CMDLST_RESERVED_HW_0_13_LEN         2
#define CMDLST_RESERVED_HW_0_13_OFFSET      0

#define CMDLST_RESERVED_HW_2_14_LEN         6
#define CMDLST_RESERVED_HW_2_14_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_14_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_14_OFFSET    24
#define CMDLST_RESERVED_HW_1_14_LEN         3
#define CMDLST_RESERVED_HW_1_14_OFFSET      21
#define CMDLST_HW_CVDR_RD_ADDRESS_14_LEN    19
#define CMDLST_HW_CVDR_RD_ADDRESS_14_OFFSET 2
#define CMDLST_RESERVED_HW_0_14_LEN         2
#define CMDLST_RESERVED_HW_0_14_OFFSET      0

#define CMDLST_HW_CVDR_RD_DATA_0_0_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_0_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_1_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_1_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_2_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_2_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_3_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_3_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_4_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_4_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_5_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_5_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_6_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_6_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_7_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_7_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_8_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_8_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_9_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_9_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_10_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_10_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_11_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_11_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_12_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_12_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_13_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_13_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_0_14_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_0_14_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_0_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_0_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_1_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_1_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_2_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_2_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_3_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_3_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_4_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_4_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_5_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_5_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_6_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_6_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_7_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_7_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_8_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_8_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_9_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_9_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_10_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_10_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_11_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_11_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_12_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_12_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_13_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_13_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_1_14_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_1_14_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_0_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_0_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_1_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_1_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_2_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_2_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_3_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_3_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_4_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_4_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_5_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_5_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_6_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_6_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_7_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_7_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_8_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_8_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_9_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_9_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_10_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_10_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_11_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_11_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_12_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_12_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_13_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_13_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_2_14_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_2_14_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_0_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_0_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_1_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_1_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_2_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_2_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_3_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_3_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_4_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_4_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_5_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_5_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_6_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_6_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_7_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_7_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_8_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_8_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_9_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_9_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_10_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_10_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_11_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_11_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_12_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_12_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_13_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_13_OFFSET 0

#define CMDLST_HW_CVDR_RD_DATA_3_14_LEN    32
#define CMDLST_HW_CVDR_RD_DATA_3_14_OFFSET 0

#define CMDLST_RESERVED_2_0_LEN      23
#define CMDLST_RESERVED_2_0_OFFSET   9
#define CMDLST_DBG_HW_START_0_LEN    1
#define CMDLST_DBG_HW_START_0_OFFSET 8
#define CMDLST_RESERVED_1_0_LEN      3
#define CMDLST_RESERVED_1_0_OFFSET   5
#define CMDLST_DBG_SW_START_0_LEN    1
#define CMDLST_DBG_SW_START_0_OFFSET 4
#define CMDLST_RESERVED_0_0_LEN      1
#define CMDLST_RESERVED_0_0_OFFSET   3
#define CMDLST_DBG_FSM_CH_0_LEN      3
#define CMDLST_DBG_FSM_CH_0_OFFSET   0

#define CMDLST_RESERVED_2_1_LEN      23
#define CMDLST_RESERVED_2_1_OFFSET   9
#define CMDLST_DBG_HW_START_1_LEN    1
#define CMDLST_DBG_HW_START_1_OFFSET 8
#define CMDLST_RESERVED_1_1_LEN      3
#define CMDLST_RESERVED_1_1_OFFSET   5
#define CMDLST_DBG_SW_START_1_LEN    1
#define CMDLST_DBG_SW_START_1_OFFSET 4
#define CMDLST_RESERVED_0_1_LEN      1
#define CMDLST_RESERVED_0_1_OFFSET   3
#define CMDLST_DBG_FSM_CH_1_LEN      3
#define CMDLST_DBG_FSM_CH_1_OFFSET   0

#define CMDLST_RESERVED_2_2_LEN      23
#define CMDLST_RESERVED_2_2_OFFSET   9
#define CMDLST_DBG_HW_START_2_LEN    1
#define CMDLST_DBG_HW_START_2_OFFSET 8
#define CMDLST_RESERVED_1_2_LEN      3
#define CMDLST_RESERVED_1_2_OFFSET   5
#define CMDLST_DBG_SW_START_2_LEN    1
#define CMDLST_DBG_SW_START_2_OFFSET 4
#define CMDLST_RESERVED_0_2_LEN      1
#define CMDLST_RESERVED_0_2_OFFSET   3
#define CMDLST_DBG_FSM_CH_2_LEN      3
#define CMDLST_DBG_FSM_CH_2_OFFSET   0

#define CMDLST_RESERVED_2_3_LEN      23
#define CMDLST_RESERVED_2_3_OFFSET   9
#define CMDLST_DBG_HW_START_3_LEN    1
#define CMDLST_DBG_HW_START_3_OFFSET 8
#define CMDLST_RESERVED_1_3_LEN      3
#define CMDLST_RESERVED_1_3_OFFSET   5
#define CMDLST_DBG_SW_START_3_LEN    1
#define CMDLST_DBG_SW_START_3_OFFSET 4
#define CMDLST_RESERVED_0_3_LEN      1
#define CMDLST_RESERVED_0_3_OFFSET   3
#define CMDLST_DBG_FSM_CH_3_LEN      3
#define CMDLST_DBG_FSM_CH_3_OFFSET   0

#define CMDLST_RESERVED_2_4_LEN      23
#define CMDLST_RESERVED_2_4_OFFSET   9
#define CMDLST_DBG_HW_START_4_LEN    1
#define CMDLST_DBG_HW_START_4_OFFSET 8
#define CMDLST_RESERVED_1_4_LEN      3
#define CMDLST_RESERVED_1_4_OFFSET   5
#define CMDLST_DBG_SW_START_4_LEN    1
#define CMDLST_DBG_SW_START_4_OFFSET 4
#define CMDLST_RESERVED_0_4_LEN      1
#define CMDLST_RESERVED_0_4_OFFSET   3
#define CMDLST_DBG_FSM_CH_4_LEN      3
#define CMDLST_DBG_FSM_CH_4_OFFSET   0

#define CMDLST_RESERVED_2_5_LEN      23
#define CMDLST_RESERVED_2_5_OFFSET   9
#define CMDLST_DBG_HW_START_5_LEN    1
#define CMDLST_DBG_HW_START_5_OFFSET 8
#define CMDLST_RESERVED_1_5_LEN      3
#define CMDLST_RESERVED_1_5_OFFSET   5
#define CMDLST_DBG_SW_START_5_LEN    1
#define CMDLST_DBG_SW_START_5_OFFSET 4
#define CMDLST_RESERVED_0_5_LEN      1
#define CMDLST_RESERVED_0_5_OFFSET   3
#define CMDLST_DBG_FSM_CH_5_LEN      3
#define CMDLST_DBG_FSM_CH_5_OFFSET   0

#define CMDLST_RESERVED_2_6_LEN      23
#define CMDLST_RESERVED_2_6_OFFSET   9
#define CMDLST_DBG_HW_START_6_LEN    1
#define CMDLST_DBG_HW_START_6_OFFSET 8
#define CMDLST_RESERVED_1_6_LEN      3
#define CMDLST_RESERVED_1_6_OFFSET   5
#define CMDLST_DBG_SW_START_6_LEN    1
#define CMDLST_DBG_SW_START_6_OFFSET 4
#define CMDLST_RESERVED_0_6_LEN      1
#define CMDLST_RESERVED_0_6_OFFSET   3
#define CMDLST_DBG_FSM_CH_6_LEN      3
#define CMDLST_DBG_FSM_CH_6_OFFSET   0

#define CMDLST_RESERVED_2_7_LEN      23
#define CMDLST_RESERVED_2_7_OFFSET   9
#define CMDLST_DBG_HW_START_7_LEN    1
#define CMDLST_DBG_HW_START_7_OFFSET 8
#define CMDLST_RESERVED_1_7_LEN      3
#define CMDLST_RESERVED_1_7_OFFSET   5
#define CMDLST_DBG_SW_START_7_LEN    1
#define CMDLST_DBG_SW_START_7_OFFSET 4
#define CMDLST_RESERVED_0_7_LEN      1
#define CMDLST_RESERVED_0_7_OFFSET   3
#define CMDLST_DBG_FSM_CH_7_LEN      3
#define CMDLST_DBG_FSM_CH_7_OFFSET   0

#define CMDLST_RESERVED_2_8_LEN      23
#define CMDLST_RESERVED_2_8_OFFSET   9
#define CMDLST_DBG_HW_START_8_LEN    1
#define CMDLST_DBG_HW_START_8_OFFSET 8
#define CMDLST_RESERVED_1_8_LEN      3
#define CMDLST_RESERVED_1_8_OFFSET   5
#define CMDLST_DBG_SW_START_8_LEN    1
#define CMDLST_DBG_SW_START_8_OFFSET 4
#define CMDLST_RESERVED_0_8_LEN      1
#define CMDLST_RESERVED_0_8_OFFSET   3
#define CMDLST_DBG_FSM_CH_8_LEN      3
#define CMDLST_DBG_FSM_CH_8_OFFSET   0

#define CMDLST_RESERVED_2_9_LEN      23
#define CMDLST_RESERVED_2_9_OFFSET   9
#define CMDLST_DBG_HW_START_9_LEN    1
#define CMDLST_DBG_HW_START_9_OFFSET 8
#define CMDLST_RESERVED_1_9_LEN      3
#define CMDLST_RESERVED_1_9_OFFSET   5
#define CMDLST_DBG_SW_START_9_LEN    1
#define CMDLST_DBG_SW_START_9_OFFSET 4
#define CMDLST_RESERVED_0_9_LEN      1
#define CMDLST_RESERVED_0_9_OFFSET   3
#define CMDLST_DBG_FSM_CH_9_LEN      3
#define CMDLST_DBG_FSM_CH_9_OFFSET   0

#define CMDLST_RESERVED_2_10_LEN      23
#define CMDLST_RESERVED_2_10_OFFSET   9
#define CMDLST_DBG_HW_START_10_LEN    1
#define CMDLST_DBG_HW_START_10_OFFSET 8
#define CMDLST_RESERVED_1_10_LEN      3
#define CMDLST_RESERVED_1_10_OFFSET   5
#define CMDLST_DBG_SW_START_10_LEN    1
#define CMDLST_DBG_SW_START_10_OFFSET 4
#define CMDLST_RESERVED_0_10_LEN      1
#define CMDLST_RESERVED_0_10_OFFSET   3
#define CMDLST_DBG_FSM_CH_10_LEN      3
#define CMDLST_DBG_FSM_CH_10_OFFSET   0

#define CMDLST_RESERVED_2_11_LEN      23
#define CMDLST_RESERVED_2_11_OFFSET   9
#define CMDLST_DBG_HW_START_11_LEN    1
#define CMDLST_DBG_HW_START_11_OFFSET 8
#define CMDLST_RESERVED_1_11_LEN      3
#define CMDLST_RESERVED_1_11_OFFSET   5
#define CMDLST_DBG_SW_START_11_LEN    1
#define CMDLST_DBG_SW_START_11_OFFSET 4
#define CMDLST_RESERVED_0_11_LEN      1
#define CMDLST_RESERVED_0_11_OFFSET   3
#define CMDLST_DBG_FSM_CH_11_LEN      3
#define CMDLST_DBG_FSM_CH_11_OFFSET   0

#define CMDLST_RESERVED_2_12_LEN      23
#define CMDLST_RESERVED_2_12_OFFSET   9
#define CMDLST_DBG_HW_START_12_LEN    1
#define CMDLST_DBG_HW_START_12_OFFSET 8
#define CMDLST_RESERVED_1_12_LEN      3
#define CMDLST_RESERVED_1_12_OFFSET   5
#define CMDLST_DBG_SW_START_12_LEN    1
#define CMDLST_DBG_SW_START_12_OFFSET 4
#define CMDLST_RESERVED_0_12_LEN      1
#define CMDLST_RESERVED_0_12_OFFSET   3
#define CMDLST_DBG_FSM_CH_12_LEN      3
#define CMDLST_DBG_FSM_CH_12_OFFSET   0

#define CMDLST_RESERVED_2_13_LEN      23
#define CMDLST_RESERVED_2_13_OFFSET   9
#define CMDLST_DBG_HW_START_13_LEN    1
#define CMDLST_DBG_HW_START_13_OFFSET 8
#define CMDLST_RESERVED_1_13_LEN      3
#define CMDLST_RESERVED_1_13_OFFSET   5
#define CMDLST_DBG_SW_START_13_LEN    1
#define CMDLST_DBG_SW_START_13_OFFSET 4
#define CMDLST_RESERVED_0_13_LEN      1
#define CMDLST_RESERVED_0_13_OFFSET   3
#define CMDLST_DBG_FSM_CH_13_LEN      3
#define CMDLST_DBG_FSM_CH_13_OFFSET   0

#define CMDLST_RESERVED_2_14_LEN      23
#define CMDLST_RESERVED_2_14_OFFSET   9
#define CMDLST_DBG_HW_START_14_LEN    1
#define CMDLST_DBG_HW_START_14_OFFSET 8
#define CMDLST_RESERVED_1_14_LEN      3
#define CMDLST_RESERVED_1_14_OFFSET   5
#define CMDLST_DBG_SW_START_14_LEN    1
#define CMDLST_DBG_SW_START_14_OFFSET 4
#define CMDLST_RESERVED_0_14_LEN      1
#define CMDLST_RESERVED_0_14_OFFSET   3
#define CMDLST_DBG_FSM_CH_14_LEN      3
#define CMDLST_DBG_FSM_CH_14_OFFSET   0

#endif // __CMDLST_REG_OFFSET_FIELD_CS_H__
