ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hisp
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

EXTRA_CFLAGS += -DHISP210_CAMERA
obj-y += hisp210.o
