NPU_ARCH_VERSION=npu_v200
CONFIG_NPU_PCR_ENABLED=y
CONFIG_NPU_AUTOFS=y
CONFIG_NPU_SYSCACHE=y
CONFIG_NPU_SDMA=y
export NPU_ARCH_VERSION CONFIG_NPU_PCR_ENABLED CONFIG_NPU_AUTOFS CONFIG_NPU_SYSCACHE CONFIG_NPU_SDMA

NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_PCR_ENABLED
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_MMAP

NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SYSCACHE
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_AUTOFS
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_NOC