#ifndef MNTN_SUBTYPE_EXCEPTION_GENERAL_SEE_H
#define MNTN_SUBTYPE_EXCEPTION_GENERAL_SEE_H 
enum general_see_module_id {
 MODID_GENERAL_SEE_START = (unsigned int)DFX_BB_MOD_GENERAL_SEE_START,
 MODID_GENERAL_SEE_EXC_SENSOR_CTRL = MODID_GENERAL_SEE_START,
 MODID_GENERAL_SEE_EXC_SIC,
 MODID_GENERAL_SEE_EXC_MED_ROM,
 MODID_GENERAL_SEE_EXC_MED_RAM,
 MODID_GENERAL_SEE_EXC_OTPC,
 MODID_GENERAL_SEE_EXC_HARD,
 MODID_GENERAL_SEE_EXC_IPC_MAILBOX,
 MODID_GENERAL_SEE_EXC_MPU,
 MODID_GENERAL_SEE_EXC_BUS,
 MODID_GENERAL_SEE_EXC_SSP,
 MODID_GENERAL_SEE_EXC_SEC_EXTERN,
 MODID_GENERAL_SEE_EXC_WDG,
 MODID_GENERAL_SEE_EXC_SYSALARM,
 MODID_GENERAL_SEE_EXC_NV_COUNTER,
 MODID_GENERAL_SEE_EXC_SWP,
 MODID_GENERAL_SEE_EXC_COS,
 MODID_GENERAL_SEE_EXC_BB,
 MODID_GENERAL_SEE_EXC_MNTN_COS,
 MODID_GENERAL_SEE_EXC_MNTN_COS_RESET,
 MODID_GENERAL_SEE_EXC_LIBC,
 MODID_GENERAL_SEE_EXC_NVM,
 MODID_GENERAL_SEE_EXC_SECENG_TRNG,
 MODID_GENERAL_SEE_EXC_SECENG_TRIM,
 MODID_GENERAL_SEE_EXC_SECENG_SCE,
 MODID_GENERAL_SEE_EXC_SECENG_RSA,
 MODID_GENERAL_SEE_EXC_SECENG_SM2,
 MODID_GENERAL_SEE_EXC_SECENG_KM,
 MODID_GENERAL_SEE_EXC_SECENG_SCRAMBLING,
 MODID_GENERAL_SEE_EXC_DCS,
 MODID_GENERAL_SEE_EXC_BOTTOM,
 MODID_GENERAL_SEE_EXC_UNKNOWN = MODID_GENERAL_SEE_START + 0xFFFF,
 MODID_GENERAL_SEE_EXC_ALARM0 = MODID_GENERAL_SEE_START + 0x20000,
 MODID_GENERAL_SEE_EXC_ALARM1,
 MODID_GENERAL_SEE_EXC_AS2AP_IRQ,
 MODID_GENERAL_SEE_EXC_DS2AP_IRQ,
 MODID_GENERAL_SEE_EXC_SENC2AP_IRQ,
 MODID_GENERAL_SEE_EXC_SENC2AP_IRQ0,
 MODID_GENERAL_SEE_EXC_SENC2AP_IRQ1,
 MODID_GENERAL_SEE_EXC_LOCKUP,
 MODID_GENERAL_SEE_EXC_EH2H_SLV,
 MODID_GENERAL_SEE_EXC_TSENSOR1,
 MODID_GENERAL_SEE_EXC_RST,
 MODID_SIMULATE_EXC_RPMB_KO = MODID_GENERAL_SEE_START + 0x30000,
 MODID_GENERAL_SEE_EXC_END = DFX_BB_MOD_GENERAL_SEE_END
};
#define GENERAL_SEE_EXCEPTIONE_INFO(modid,subtype,desc) { \
 .e_modid = (u32)(modid), \
 .e_modid_end = (u32)(modid), \
 .e_process_priority = RDR_ERR, \
 .e_reboot_priority = RDR_REBOOT_NO, \
 .e_notify_core_mask = RDR_GENERAL_SEE, \
 .e_reset_core_mask = RDR_GENERAL_SEE, \
 .e_from_core = RDR_GENERAL_SEE, \
 .e_reentrant = (u32)RDR_REENTRANT_DISALLOW, \
 .e_exce_type = GENERAL_SEE_S_EXCEPTION, \
 .e_exce_subtype = (subtype), \
 .e_upload_flag = (u32)RDR_UPLOAD_YES, \
 .e_save_log_flags = RDR_SAVE_BL31_LOG, \
 .e_from_module = (desc), \
 .e_desc = "GENERAL_SEE", \
}
#define GENERAL_SEE_EXCEPTIONE_INFO_MAP { \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SENSOR_CTRL, \
         EXC_SENSOR_CTRL, "GENERAL_SEE SENSOR"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SIC, \
         EXC_SIC, "GENERAL_SEE SIC"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_MED_ROM, \
         EXC_MED_ROM, "GENERAL_SEE ROM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_MED_RAM, \
         EXC_MED_RAM, "GENERAL_SEE RAM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_OTPC, \
         EXC_OTPC, "GENERAL_SEE OTPC"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_HARD, \
         EXC_HARD, "GENERAL_SEE HARD"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_IPC_MAILBOX, \
         EXC_IPC_MAILBOX, "GENERAL_SEE IPC MAILBOX"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_MPU, \
         EXC_MPU, "GENERAL_SEE MPU"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_BUS, \
         EXC_BUS, "GENERAL_SEE RPMB"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SSP, \
         EXC_SSP, "GENERAL_SEE SSP"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SEC_EXTERN, \
         EXC_SEC_EXTERN, "GENERAL_SEE SEC EXTERN"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_WDG, \
         EXC_WDG, "GENERAL_SEE WDG"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SYSALARM, \
         EXC_SYSALARM, "GENERAL_SEE SYSALARM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_NV_COUNTER, \
         EXC_NV_COUNTER, "GENERAL_SEE NV_COUNTER"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SWP, \
         EXC_SWP, "GENERAL_SEE SWP"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_COS, \
         EXC_COS, "GENERAL_SEE COS"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_BB, \
         EXC_BB, "GENERAL_SEE BB"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_MNTN_COS, \
         EXC_MNTN_COS, "GENERAL_SEE MNTN_COS"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_MNTN_COS_RESET, \
         EXC_MNTN_COS_RESET, "GENERAL_SEE NORMAL RESET"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_LIBC, \
         EXC_LIBC, "GENERAL_SEE LIBC"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_NVM, \
         EXC_NVM, "GENERAL_SEE NVM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_TRNG, \
         EXC_SECENG_TRNG, "GENERAL_SEE SECENG TRNG"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_TRIM, \
         EXC_SECENG_TRIM, "GENERAL_SEE SECENG TRIM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_SCE, \
         EXC_SECENG_SCE, "GENERAL_SEE SECENG SCE"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_RSA, \
         EXC_SECENG_RSA, "GENERAL_SEE SECENG RSA"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_SM2, \
         EXC_SECENG_SM2, "GENERAL_SEE SECENG SM2"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_KM, \
         EXC_SECENG_KM, "GENERAL_SEE SECENG KM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SECENG_SCRAMBLING, \
         EXC_SECENG_SCRAMBLING, "GENERAL_SEE SECENG SCRAM"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_DCS, \
         EXC_DCS, "GENERAL_SEE DCS"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_ALARM0, \
         EXC_ALARM0, "GENERAL_SEE ALARM0"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_ALARM1, \
         EXC_ALARM1, "GENERAL_SEE ALARM1"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_AS2AP_IRQ, \
         EXC_AS2AP_IRQ, "GENERAL_SEE AS2AP IRQ"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_DS2AP_IRQ, \
         EXC_DS2AP_IRQ, "GENERAL_SEE DS2AP IRQ"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SENC2AP_IRQ, \
         EXC_SENC2AP_IRQ, "GENERAL_SEE SENC2AP IRQ"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SENC2AP_IRQ0, \
         EXC_SENC2AP_IRQ0, "GENERAL_SEE SENC2AP IRQ0"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_SENC2AP_IRQ1, \
         EXC_SENC2AP_IRQ1, "GENERAL_SEE SENC2AP IRQ1"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_LOCKUP, \
         EXC_LOCKUP, "GENERAL_SEE LOCKUP"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_EH2H_SLV, \
         EXC_EH2H_SLV, "GENERAL_SEE EH2H SLV"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_TSENSOR1, \
         EXC_TSENSOR1, "GENERAL_SEE TSENSOR1"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_RST, \
         EXC_RST, "GENERAL_SEE RST"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_SIMULATE_EXC_RPMB_KO, \
         SIMULATE_EXC_RPMB_KO, "FAIL TO RESET RPMB"), \
 GENERAL_SEE_EXCEPTIONE_INFO(MODID_GENERAL_SEE_EXC_UNKNOWN, \
         EXC_UNKNOWN, "GENERAL_SEE UNKNOWN"), \
}
#endif
