# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_KEYBOARD_CORE)                += keypad.o
obj-$(CONFIG_KEYBOARD_GPIO_VOLUME_KEY)     += keypad_gpio.o
obj-$(CONFIG_KEYBOARD_GPIO_FUNC_KEY)       += keypad_func.o
obj-$(CONFIG_KEYBOARD_PMIC_VOLUME_KEY)     += keypad_pmic.o
obj-$(CONFIG_KEYBOARD_PMIC_VOLUME_KEY)     += keypad_pmic_event.o
