// *********************************************************
// Copyright     :  Copyright (C) 2019, Hisilicon Technologies Co. Ltd.
// File name     :  ipp_top_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Version       :  1.0
// Date          :  2019/01/02
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.1
// **********************************************************

#ifndef __IPP_TOP_REG_OFFSET_FIELD_H__
#define __IPP_TOP_REG_OFFSET_FIELD_H__

#define IPP_TOP_MST_PRIORITY_PAC1_LEN                   2
#define IPP_TOP_MST_PRIORITY_PAC1_OFFSET                21
#define IPP_TOP_MST_PRIORITY_PAC0_LEN                   2
#define IPP_TOP_MST_PRIORITY_PAC0_OFFSET                19
#define IPP_TOP_MST_PRIORITY_CVDR_LEN                   2
#define IPP_TOP_MST_PRIORITY_CVDR_OFFSET                17
#define IPP_TOP_CONTROL_DISABLE_AXI_DATA_PACKING_LEN    1
#define IPP_TOP_CONTROL_DISABLE_AXI_DATA_PACKING_OFFSET 16
#define IPP_TOP_JPG_DW_AXI_GATEDCLOCK_EN_LEN            1
#define IPP_TOP_JPG_DW_AXI_GATEDCLOCK_EN_OFFSET         0

#define IPP_TOP_DPM_CLKEN_LEN         1
#define IPP_TOP_DPM_CLKEN_OFFSET      4
#define IPP_TOP_CMDLST_CLKEN_LEN      1
#define IPP_TOP_CMDLST_CLKEN_OFFSET   3
#define IPP_TOP_TBU_CVDR_CLKEN_LEN    1
#define IPP_TOP_TBU_CVDR_CLKEN_OFFSET 1
#define IPP_TOP_CVDR_CLKEN_LEN        1
#define IPP_TOP_CVDR_CLKEN_OFFSET     0

#define IPP_TOP_DPM_SOFT_RST_LEN         1
#define IPP_TOP_DPM_SOFT_RST_OFFSET      4
#define IPP_TOP_CMDLST_SOFT_RST_LEN      1
#define IPP_TOP_CMDLST_SOFT_RST_OFFSET   3
#define IPP_TOP_TBU_CVDR_SOFT_RST_LEN    1
#define IPP_TOP_TBU_CVDR_SOFT_RST_OFFSET 1
#define IPP_TOP_CVDR_SOFT_RST_LEN        1
#define IPP_TOP_CVDR_SOFT_RST_OFFSET     0

#define IPP_TOP_CVDR_IRQ_CLR_LEN    8
#define IPP_TOP_CVDR_IRQ_CLR_OFFSET 0

#define IPP_TOP_CVDR_IRQ_MASK_LEN    8
#define IPP_TOP_CVDR_IRQ_MASK_OFFSET 0

#define IPP_TOP_CVDR_IRQ_STATE_RAW_LEN     8
#define IPP_TOP_CVDR_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_CVDR_IRQ_STATE_MASK_LEN    8
#define IPP_TOP_CVDR_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_MEM_CTRL_SP_LEN         29
#define IPP_TOP_MEM_CTRL_SP_OFFSET      3
#define IPP_TOP_CVDR_MEM_CTRL_SP_LEN    3
#define IPP_TOP_CVDR_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_MEM_CTRL_TP_LEN    29
#define IPP_TOP_MEM_CTRL_TP_OFFSET 3

#define IPP_TOP_DPM_FREQ_SEL_LEN    3
#define IPP_TOP_DPM_FREQ_SEL_OFFSET 0

#define IPP_TOP_RESERVED_EC_LEN    32
#define IPP_TOP_RESERVED_EC_OFFSET 0

#define IPP_TOP_FLUX_CTRL0_CVDR_R_LEN    32
#define IPP_TOP_FLUX_CTRL0_CVDR_R_OFFSET 0

#define IPP_TOP_FLUX_CTRL1_CVDR_R_LEN    32
#define IPP_TOP_FLUX_CTRL1_CVDR_R_OFFSET 0

#define IPP_TOP_FLUX_CTRL0_CVDR_W_LEN    32
#define IPP_TOP_FLUX_CTRL0_CVDR_W_OFFSET 0

#define IPP_TOP_FLUX_CTRL1_CVDR_W_LEN    32
#define IPP_TOP_FLUX_CTRL1_CVDR_W_OFFSET 0

#define IPP_TOP_JPG_BWC_CFG_LEN    32
#define IPP_TOP_JPG_BWC_CFG_OFFSET 0

#define IPP_TOP_JPG_AXI_DLOCK_ID_LEN     8
#define IPP_TOP_JPG_AXI_DLOCK_ID_OFFSET  20
#define IPP_TOP_JPG_AXI_DLOCK_MST_LEN    1
#define IPP_TOP_JPG_AXI_DLOCK_MST_OFFSET 19
#define IPP_TOP_JPG_AXI_DLOCK_SLV_LEN    1
#define IPP_TOP_JPG_AXI_DLOCK_SLV_OFFSET 18
#define IPP_TOP_JPG_AXI_DLOCK_WR_LEN     1
#define IPP_TOP_JPG_AXI_DLOCK_WR_OFFSET  17
#define IPP_TOP_JPG_AXI_DLOCK_IRQ_LEN    1
#define IPP_TOP_JPG_AXI_DLOCK_IRQ_OFFSET 16

#define IPP_TOP_JPGENC_FORCE_CLK_ON_LEN    1
#define IPP_TOP_JPGENC_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_JPGENC_CLKEN_LEN           1
#define IPP_TOP_JPGENC_CLKEN_OFFSET        0

#define IPP_TOP_JPGENC_SOFT_RST_LEN    1
#define IPP_TOP_JPGENC_SOFT_RST_OFFSET 0

#define IPP_TOP_JPGENC_MEM_CTRL_SP_LEN    3
#define IPP_TOP_JPGENC_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_CLR_LEN    5
#define IPP_TOP_JPGENC_IRQ_CLR_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_MASK_LEN    5
#define IPP_TOP_JPGENC_IRQ_MASK_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_STATE_RAW_LEN     5
#define IPP_TOP_JPGENC_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_JPGENC_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_JPGENC_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_JPGDEC_FORCE_CLK_ON_LEN    1
#define IPP_TOP_JPGDEC_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_JPGDEC_CLKEN_LEN           1
#define IPP_TOP_JPGDEC_CLKEN_OFFSET        0

#define IPP_TOP_JPGDEC_SOFT_RST_LEN    1
#define IPP_TOP_JPGDEC_SOFT_RST_OFFSET 0

#define IPP_TOP_JPGDEC_MEM_CTRL_TP_LEN    3
#define IPP_TOP_JPGDEC_MEM_CTRL_TP_OFFSET 4
#define IPP_TOP_JPGDEC_MEM_CTRL_SP_LEN    3
#define IPP_TOP_JPGDEC_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_CLR_LEN    4
#define IPP_TOP_JPGDEC_IRQ_CLR_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_MASK_LEN    4
#define IPP_TOP_JPGDEC_IRQ_MASK_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_STATE_RAW_LEN     4
#define IPP_TOP_JPGDEC_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_JPGDEC_IRQ_STATE_MASK_LEN    4
#define IPP_TOP_JPGDEC_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_GF_FORCE_CLK_ON_LEN    1
#define IPP_TOP_GF_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_GF_CLKEN_LEN           1
#define IPP_TOP_GF_CLKEN_OFFSET        0

#define IPP_TOP_GF_SOFT_RST_LEN    1
#define IPP_TOP_GF_SOFT_RST_OFFSET 0

#define IPP_TOP_GF_MEM_CTRL_SP_LEN    3
#define IPP_TOP_GF_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_GF_IRQ_CLR_LEN    13
#define IPP_TOP_GF_IRQ_CLR_OFFSET 0

#define IPP_TOP_GF_IRQ_OUTEN_LEN    2
#define IPP_TOP_GF_IRQ_OUTEN_OFFSET 16
#define IPP_TOP_GF_IRQ_MASK_LEN     13
#define IPP_TOP_GF_IRQ_MASK_OFFSET  0

#define IPP_TOP_GF_IRQ_STATE_MASK_LEN    13
#define IPP_TOP_GF_IRQ_STATE_MASK_OFFSET 16
#define IPP_TOP_GF_IRQ_STATE_RAW_LEN     13
#define IPP_TOP_GF_IRQ_STATE_RAW_OFFSET  0

#define IPP_TOP_ORB_FORCE_CLK_ON_LEN    1
#define IPP_TOP_ORB_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_ORB_CLKEN_LEN           1
#define IPP_TOP_ORB_CLKEN_OFFSET        0

#define IPP_TOP_ORB_SOFT_RST_LEN    1
#define IPP_TOP_ORB_SOFT_RST_OFFSET 0

#define IPP_TOP_ORB_MEM_CTRL_SP_LEN    3
#define IPP_TOP_ORB_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_ORB_IRQ_CLR_LEN    16
#define IPP_TOP_ORB_IRQ_CLR_OFFSET 0

#define IPP_TOP_ORB_IRQ_OUTEN_LEN    2
#define IPP_TOP_ORB_IRQ_OUTEN_OFFSET 16
#define IPP_TOP_ORB_IRQ_MASK_LEN     16
#define IPP_TOP_ORB_IRQ_MASK_OFFSET  0

#define IPP_TOP_ORB_IRQ_STATE_RAW_LEN     16
#define IPP_TOP_ORB_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_ORB_IRQ_STATE_MASK_LEN    16
#define IPP_TOP_ORB_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_RDR_FORCE_CLK_ON_LEN    1
#define IPP_TOP_RDR_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_RDR_CLKEN_LEN           1
#define IPP_TOP_RDR_CLKEN_OFFSET        0

#define IPP_TOP_RDR_SOFT_RST_LEN    1
#define IPP_TOP_RDR_SOFT_RST_OFFSET 0

#define IPP_TOP_RDR_MEM_CTRL_SP_LEN    3
#define IPP_TOP_RDR_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_RDR_IRQ_CLR_LEN    5
#define IPP_TOP_RDR_IRQ_CLR_OFFSET 0

#define IPP_TOP_RDR_IRQ_OUTEN_LEN    2
#define IPP_TOP_RDR_IRQ_OUTEN_OFFSET 16
#define IPP_TOP_RDR_IRQ_MASK_LEN     5
#define IPP_TOP_RDR_IRQ_MASK_OFFSET  0

#define IPP_TOP_RDR_IRQ_STATE_RAW_LEN     5
#define IPP_TOP_RDR_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_RDR_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_RDR_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_CMP_FORCE_CLK_ON_LEN    1
#define IPP_TOP_CMP_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_CMP_CLKEN_LEN           1
#define IPP_TOP_CMP_CLKEN_OFFSET        0

#define IPP_TOP_CMP_SOFT_RST_LEN    1
#define IPP_TOP_CMP_SOFT_RST_OFFSET 0

#define IPP_TOP_CMP_MEM_CTRL_SP_LEN    3
#define IPP_TOP_CMP_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_CMP_IRQ_CLR_LEN    5
#define IPP_TOP_CMP_IRQ_CLR_OFFSET 0

#define IPP_TOP_CMP_IRQ_OUTEN_LEN    2
#define IPP_TOP_CMP_IRQ_OUTEN_OFFSET 16
#define IPP_TOP_CMP_IRQ_MASK_LEN     5
#define IPP_TOP_CMP_IRQ_MASK_OFFSET  0

#define IPP_TOP_CMP_IRQ_STATE_RAW_LEN     5
#define IPP_TOP_CMP_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_CMP_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_CMP_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_ENH_FORCE_CLK_ON_LEN    1
#define IPP_TOP_ENH_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_ENH_CLKEN_LEN           1
#define IPP_TOP_ENH_CLKEN_OFFSET        0

#define IPP_TOP_ENH_SOFT_RST_LEN    1
#define IPP_TOP_ENH_SOFT_RST_OFFSET 0

#define IPP_TOP_ENH_MEM_CTRL_SP_LEN    3
#define IPP_TOP_ENH_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_ENH_VPBG_EN_LEN    2
#define IPP_TOP_ENH_VPBG_EN_OFFSET 0

#define IPP_TOP_ENH_IRQ_CLR_LEN    10
#define IPP_TOP_ENH_IRQ_CLR_OFFSET 0

#define IPP_TOP_ENH_IRQ_OUTEN_LEN    2
#define IPP_TOP_ENH_IRQ_OUTEN_OFFSET 16
#define IPP_TOP_ENH_IRQ_MASK_LEN     10
#define IPP_TOP_ENH_IRQ_MASK_OFFSET  0

#define IPP_TOP_ENH_IRQ_STATE_RAW_LEN     10
#define IPP_TOP_ENH_IRQ_STATE_RAW_OFFSET  16
#define IPP_TOP_ENH_IRQ_STATE_MASK_LEN    10
#define IPP_TOP_ENH_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_VBK_FORCE_CLK_ON_LEN    1
#define IPP_TOP_VBK_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_VBK_CLKEN_LEN           1
#define IPP_TOP_VBK_CLKEN_OFFSET        0

#define IPP_TOP_VBK_SOFT_RST_LEN    1
#define IPP_TOP_VBK_SOFT_RST_OFFSET 0

#define IPP_TOP_VBK_MEM_CTRL_SP_LEN    3
#define IPP_TOP_VBK_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_VBK_IRQ_CLR_LEN    24
#define IPP_TOP_VBK_IRQ_CLR_OFFSET 0

#define IPP_TOP_VBK_IRQ_MASK_LEN    24
#define IPP_TOP_VBK_IRQ_MASK_OFFSET 0

#define IPP_TOP_VBK_IRQ_OUTEN_LEN    2
#define IPP_TOP_VBK_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_VBK_IRQ_STATE_MASK_LEN    24
#define IPP_TOP_VBK_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_VBK_IRQ_STATE_RAW_LEN    24
#define IPP_TOP_VBK_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_ANF_FORCE_CLK_ON_LEN    1
#define IPP_TOP_ANF_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_ANF_CLKEN_LEN           1
#define IPP_TOP_ANF_CLKEN_OFFSET        0

#define IPP_TOP_ANF_SOFT_RST_LEN    1
#define IPP_TOP_ANF_SOFT_RST_OFFSET 0

#define IPP_TOP_ANF_MEM_CTRL_SP_LEN    3
#define IPP_TOP_ANF_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_ANF_IRQ_CLR_LEN    31
#define IPP_TOP_ANF_IRQ_CLR_OFFSET 0

#define IPP_TOP_ANF_IRQ_MASK_LEN    31
#define IPP_TOP_ANF_IRQ_MASK_OFFSET 0

#define IPP_TOP_ANF_IRQ_OUTEN_LEN    2
#define IPP_TOP_ANF_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_ANF_IRQ_STATE_MASK_LEN    31
#define IPP_TOP_ANF_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_ANF_IRQ_STATE_RAW_LEN    31
#define IPP_TOP_ANF_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_0_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_0_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_1_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_1_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_2_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_2_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_3_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_3_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_4_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_4_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_5_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_5_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_6_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_6_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_7_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_7_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_8_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_8_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_9_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_9_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_10_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_10_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_11_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_11_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_12_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_12_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_13_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_13_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_14_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_14_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_15_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_15_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_0_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_0_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_1_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_1_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_2_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_2_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_3_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_3_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_4_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_4_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_5_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_5_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_6_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_6_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_7_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_7_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_8_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_8_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_9_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_9_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_10_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_10_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_11_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_11_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_12_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_12_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_13_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_13_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_14_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_14_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_15_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_15_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_1_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_1_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_2_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_2_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_3_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_3_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_4_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_4_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_5_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_5_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_1_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_1_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_2_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_2_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_3_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_3_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_4_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_4_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_5_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_5_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_0_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_0_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_1_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_1_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_1_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_1_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_2_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_2_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_2_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_2_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_3_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_3_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_3_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_3_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_4_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_4_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_4_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_4_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_5_LEN     16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_5_OFFSET  16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_5_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_5_OFFSET 0

#define IPP_TOP_DEBUG_INFO_0_LEN    32
#define IPP_TOP_DEBUG_INFO_0_OFFSET 0

#define IPP_TOP_DEBUG_INFO_1_LEN    32
#define IPP_TOP_DEBUG_INFO_1_OFFSET 0

#define IPP_TOP_DEBUG_INFO_2_LEN    32
#define IPP_TOP_DEBUG_INFO_2_OFFSET 0

#define IPP_TOP_DEBUG_INFO_3_LEN    32
#define IPP_TOP_DEBUG_INFO_3_OFFSET 0

#define IPP_TOP_TOP_TZ_SECURE_N_LEN    1
#define IPP_TOP_TOP_TZ_SECURE_N_OFFSET 0

#endif // __IPP_TOP_REG_OFFSET_FIELD_H__
