# MD5: 566557b53177c475729dbcb811cc90e5
CFG_TLPHY_CSU_DATA_SAMPLE_ENABLED      := YES
CFG_TLPHY_OM_RPT_ENABLED               := YES
CFG_TL_RFD_READ_ENABLED               := YES
CFG_UPHY_DESENSITIZATION_OFF           := YES
CFG_TLPHY_ASSERT_ENABLED                := YES
