ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hisp
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

EXTRA_CFLAGS += -DHISP300_CAMERA
obj-y += hisp300.o
