# SPDX-License-Identifier: GPL-2.0
#
# Makefile for USB Host Controller Drivers
#

obj-$(CONFIG_USB_DWC3_NYET_ABNORMAL) += xhci-local-mem.o
obj-$(CONFIG_VENDOR_XHCI_EVENT_DEBUG) += xhci-debug-event.o
