/*
 * hwevext_mbhc.h
 *
 * hwevext_mbhc header file
 *
 * Copyright (c) 2021 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#ifndef _HWEVEXT_CODEC_V1_H
#define _HWEVEXT_CODEC_V1_H

/*
 * codec v1 register space
 */

/* Reset Control */
#define HWEVEXT_CODEC_V1_RESET		0x00

/* Clock Management */
#define HWEVEXT_CODEC_V1_CLKMGR_CLKSW	0x01
#define HWEVEXT_CODEC_V1_CLKMGR_CLKSEL	0x02
#define HWEVEXT_CODEC_V1_CLKMGR_ADCOSR	0x03
#define HWEVEXT_CODEC_V1_CLKMGR_ADCDIV1	0x04
#define HWEVEXT_CODEC_V1_CLKMGR_ADCDIV2	0x05
#define HWEVEXT_CODEC_V1_CLKMGR_DACDIV1	0x06
#define HWEVEXT_CODEC_V1_CLKMGR_DACDIV2	0x07
#define HWEVEXT_CODEC_V1_CLKMGR_CPDIV	0x08

/* Serial Data Port Control */
#define HWEVEXT_CODEC_V1_SERDATA1	0x09
#define HWEVEXT_CODEC_V1_SERDATA1_TRI_OFFSET 6

#define HWEVEXT_CODEC_V1_SERDATA_ADC	0x0a
#define HWEVEXT_CODEC_V1_SERDATA_ADC_SDP_MUTE_OFFSET 6

#define HWEVEXT_CODEC_V1_SERDATA_DAC	0x0b

/* System Control */
#define HWEVEXT_CODEC_V1_SYS_VMIDSEL	0x0c
#define HWEVEXT_CODEC_V1_SYS_PDN	0x0d
#define HWEVEXT_CODEC_V1_SYS_LP1	0x0e
#define HWEVEXT_CODEC_V1_SYS_LP2	0x0f
#define HWEVEXT_CODEC_V1_SYS_VMIDLOW	0x10
#define HWEVEXT_CODEC_V1_SYS_VSEL	0x11
#define HWEVEXT_CODEC_V1_SYS_REF	0x12

/* Headphone Mixer */
#define HWEVEXT_CODEC_V1_HPMIX_SEL	0x13
#define HWEVEXT_CODEC_V1_HPMIX_SWITCH	0x14
#define HWEVEXT_CODEC_V1_HPMIX_PDN	0x15
#define HWEVEXT_CODEC_V1_HPMIX_VOL	0x16

/* Charge Pump Headphone driver */
#define HWEVEXT_CODEC_V1_CPHP_OUTEN	0x17
#define HWEVEXT_CODEC_V1_CPHP_ICAL_VOL	0x18
#define HWEVEXT_CODEC_V1_CPHP_PDN1	0x19
#define HWEVEXT_CODEC_V1_CPHP_PDN2	0x1a
#define HWEVEXT_CODEC_V1_CPHP_LDOCTL	0x1b

/* Calibration */
#define HWEVEXT_CODEC_V1_CAL_TYPE	0x1c
#define HWEVEXT_CODEC_V1_CAL_SET	0x1d
#define HWEVEXT_CODEC_V1_CAL_HPLIV	0x1e
#define HWEVEXT_CODEC_V1_CAL_HPRIV	0x1f
#define HWEVEXT_CODEC_V1_CAL_HPLMV	0x20
#define HWEVEXT_CODEC_V1_CAL_HPRMV	0x21

/* ADC Control */
#define HWEVEXT_CODEC_V1_ADC_PDN_LINSEL	0x22
#define HWEVEXT_CODEC_V1_ADC_PGAGAIN	0x23
#define HWEVEXT_CODEC_V1_ADC_D2SEPGA	0x24
#define HWEVEXT_CODEC_V1_ADC_DMIC	0x25
#define HWEVEXT_CODEC_V1_ADC_MUTE	0x26
#define HWEVEXT_CODEC_V1_ADC_VOLUME	0x27
#define HWEVEXT_CODEC_V1_ADC_ALC1	0x29
#define HWEVEXT_CODEC_V1_ADC_ALC2	0x2a
#define HWEVEXT_CODEC_V1_ADC_ALC3	0x2b
#define HWEVEXT_CODEC_V1_ADC_ALC4	0x2c
#define HWEVEXT_CODEC_V1_ADC_ALC5	0x2d
#define HWEVEXT_CODEC_V1_ADC_ALC_NG	0x2e

/* DAC Control */
#define HWEVEXT_CODEC_V1_DAC_PDN	0x2f
#define HWEVEXT_CODEC_V1_DAC_SET1	0x30
#define HWEVEXT_CODEC_V1_DAC_SET2	0x31
#define HWEVEXT_CODEC_V1_DAC_SET3	0x32
#define HWEVEXT_CODEC_V1_DAC_VOLL	0x33
#define HWEVEXT_CODEC_V1_DAC_VOLR	0x34

/* GPIO */
#define HWEVEXT_CODEC_V1_GPIO_SEL	0x4d
#define HWEVEXT_CODEC_V1_GPIO_DEBOUNCE	0x4e
#define HWEVEXT_CODEC_V1_GPIO_FLAG	0x4f

/* Test mode */
#define HWEVEXT_CODEC_V1_TESTMODE	0x50
#define HWEVEXT_CODEC_V1_TEST1		0x51
#define HWEVEXT_CODEC_V1_TEST2		0x52
#define HWEVEXT_CODEC_V1_TEST3		0x53

/*
 * Field definitions
 */

/* HWEVEXT_CODEC_V1_RESET */
#define HWEVEXT_CODEC_V1_RESET_CSM_ON	0x80

/* HWEVEXT_CODEC_V1_CLKMGR_CLKSW */
#define HWEVEXT_CODEC_V1_CLKMGR_CLKSW_MCLK_ON	0x40
#define HWEVEXT_CODEC_V1_CLKMGR_CLKSW_BCLK_ON	0x20

/* HWEVEXT_CODEC_V1_SERDATA1 */
#define HWEVEXT_CODEC_V1_SERDATA1_MASTER	0x80
#define HWEVEXT_CODEC_V1_SERDATA1_BCLK_INV	0x20

/* HWEVEXT_CODEC_V1_SERDATA_ADC and _DAC */
#define HWEVEXT_CODEC_V1_SERDATA2_FMT_MASK	0x3
#define HWEVEXT_CODEC_V1_SERDATA2_FMT_I2S	0x00
#define HWEVEXT_CODEC_V1_SERDATA2_FMT_LEFTJ	0x01
#define HWEVEXT_CODEC_V1_SERDATA2_FMT_RIGHTJ	0x02
#define HWEVEXT_CODEC_V1_SERDATA2_FMT_PCM	0x03
#define HWEVEXT_CODEC_V1_SERDATA2_ADCLRP	0x20
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_MASK	0x1c
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_24	0x00
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_20	0x04
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_18	0x08
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_16	0x0c
#define HWEVEXT_CODEC_V1_SERDATA2_LEN_32	0x10

/* HWEVEXT_CODEC_V1_GPIO_DEBOUNCE	*/
#define HWEVEXT_CODEC_V1_GPIO_ENABLE_INTERRUPT	0x02

/* HWEVEXT_CODEC_V1_GPIO_FLAG */
#define HWEVEXT_CODEC_V1GPIO_FLAG_GM_NOT_SHORTED 0x02
#define HWEVEXT_CODEC_V1_GPIO_FLAG_HP_INSERTED	0x04

#endif
