
obj-$(CONFIG_ATF_KERNEL_BL2_LOG) += bl2_log/
obj-$(CONFIG_HISI_BL31_HIBERNATE) += bl31_hibernate/
obj-$(CONFIG_ATF_KERNEL_BL31_LOG) += bl31_log/
obj-$(CONFIG_VENDOR_EFUSE) += efuse/
obj-$(CONFIG_UAPP) += uapp/
obj-$(CONFIG_SECURITY_INFO) += security_info/
obj-$(CONFIG_LOAD_IMAGE) += load_image/
obj-$(CONFIG_HHEE) += hhee/
obj-$(CONFIG_GENERAL_SEE) += general_see/
obj-$(CONFIG_CRYPTO_CORE)  += crypto_core/
obj-$(CONFIG_CRYPTO_ENHANCE) += crypto_enhance/
obj-$(CONFIG_THEED) += thee/
obj-$(CONFIG_EL3_PA_TEST) += cpusec_test/
obj-$(CONFIG_KERNEL_REGION_PROTECT) += harden/
obj-$(CONFIG_HISI_KERNEL_HARDEN_DEBUG) += kernel_harden_test/
obj-$(CONFIG_SECBOOT) += secboot/
obj-y += cust_atf_shmem/


