# SPDX-License-Identifier: GPL-2.0-only

ccflags-y +=  -I$(srctree)/drivers/pinctrl

obj-$(CONFIG_PINCTRL_V500)	+= pinctrl_v500.o
obj-$(CONFIG_PINCTRL_HI6502)	+= pinctrl_hi6502.o
obj-$(CONFIG_PINCTRL_DEBUG)	+= pinctrl_debugfs.o