
ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow
# if cs and es differs, split two different directories
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hjpeg/hjpegenc

obj-y += platform_cvdr_config.o platform_jpegenc_config.o
