/*
 * audio_ddr_map.h -- audio ddr map
 *
 * Copyright (c) 2022-2022 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#ifndef __AUDIO_DDR_MAP_H__
#define __AUDIO_DDR_MAP_H__

#ifndef CONFIG_AUDIO_COMMON_IMAGE
#include "audio/asp_register.h"
#ifdef CONFIG_PRODUCT_CDC_ACE
#include <global_ddr_map_cdc_ace.h>
#else
#include <global_ddr_map.h>
#endif
#endif

#ifndef CONFIG_AUDIO_COMMON_IMAGE
#define DSP_UNSEC_BASE_ADDR    RESERVED_HIFI_DATA_PHYMEM_BASE
#else
#define DSP_UNSEC_BASE_ADDR    0
#endif
#define ASP_FAMA_PHY_ADDR_DIFF 0

#ifdef CONFIG_HIFI_IPC_3660
#ifndef CONFIG_AUDIO_COMMON_IMAGE
#define DSP_UNSEC_REGION_SIZE              RESERVED_HIFI_DATA_PHYMEM_SIZE
#else
#define DSP_UNSEC_REGION_SIZE              0
#endif
#define DSP_MUSIC_DATA_SIZE                (0x132000 + 0x32000)
#ifdef CONFIG_HIFI_MEMORY_15M
#define PCM_PLAY_BUFF_SIZE                 0x6F000
#else
#define PCM_PLAY_BUFF_SIZE                 (0x200000 - 0x32000)
#endif
#else
#define DSP_UNSEC_REGION_SIZE              0x380000
#define DSP_MUSIC_DATA_SIZE                0x132000
#define PCM_PLAY_BUFF_SIZE                 0x100000
#endif

#define PCM_PLAY_BUFF_USED_SIZE            0x100000
#define DSP_AP_NV_DATA_SIZE                0x4BC00
#define DRV_DSP_UART_TO_MEM_SIZE           0x7f000
#define DRV_DSP_UART_TO_MEM_RESERVE_SIZE   0x100
#define DRV_DSP_STACK_TO_MEM_SIZE          0x1000
#define DSP_ICC_DEBUG_SIZE                 0x11000
#define DSP_SOCP_BUFFER_SIZE               0x2000
#define DSP_FLAG_DATA_SIZE                 0x1000
#define DSP_SEC_HEAD_SIZE                  0x1000

#define DSP_AP_MAILBOX_TOTAL_SIZE          0x10000
#define CODEC_DSP_OM_DMA_BUFFER_SIZE       0xF000
#define CODEC_DSP_OM_DMA_CONFIG_SIZE       0x80
#define CODEC_DSP_SOUNDTRIGGER_TOTAL_SIZE  0xF000
#define DSP_PCM_UPLOAD_BUFFER_SIZE         0x2000
#define DSP_PARA_DOWNLOAD_BUFFER_SIZE      0x2000
#ifdef CONFIG_HUAWEI_AUDIO
#define DSP_SOUND_ENHANCE_BUFF_SIZE        0x2000
#endif
#define DSP_AUDIO_EFFECT_PARAM_BUFF_SIZE   0xC000
#ifdef CONFIG_HIFI_MEMORY_15M
#define HIFI_USB_DRIVER_SHARE_MEM_SIZE     0x0
#else
#define HIFI_USB_DRIVER_SHARE_MEM_SIZE     0x20000
#endif

#ifdef CONFIG_HIFI_IPC_3660
#ifdef CONFIG_HIFI_MEMORY_15M
#define AUDIO_DP_DATA_BUFF_SIZE       0x0
#else
#define AUDIO_DP_DATA_BUFF_SIZE       0x40000
#endif
#else
#define AUDIO_DP_DATA_BUFF_SIZE       0x0
#endif

#define AP_AUDIO_PA_BUFF_SIZE              0x4000
#ifdef CONFIG_DSP_VAD_WAKEUP
#define AP_AUDIO_WAKEUP_RINGBUFEER_SIZE    0x1D000
#define AP_AUDIO_WAKEUP_CAPTURE_SIZE       0x3000
#elif defined CONFIG_HIFI_SUPPORT_VIBRATOR
#define AP_AUDIO_WAKEUP_RINGBUFEER_SIZE    0x1E000
#define AP_AUDIO_WAKEUP_CAPTURE_SIZE       0x2000
#else
#define AP_AUDIO_WAKEUP_RINGBUFEER_SIZE    0x1E000
#define AP_AUDIO_WAKEUP_CAPTURE_SIZE       0x3000
#endif
#define AP_AUDIO_WAKEUP_MODEL_SIZE         0x1000
#define AP_AUDIO_LP_WAKEUP_RINGBUFEER_SIZE AP_AUDIO_WAKEUP_RINGBUFEER_SIZE
#define AP_AUDIO_LP_WAKEUP_CAPTURE_SIZE    AP_AUDIO_WAKEUP_CAPTURE_SIZE
#ifdef CONFIG_HUAWEI_AUDIO
#define DSP_UNSEC_RESERVE_SIZE      0x46C00
#else
#define DSP_UNSEC_RESERVE_SIZE      0x48C00
#endif
#define DSP_PCM_THREAD_DATA_SIZE           0x48
#define DRV_DSP_SCREEN_STATUS_SIZE         4
#ifdef EXTERNAL_MODEM
#define AP_MODEM_NV_SIZE  0x32c00
#define AP_OM_BUFFER_SIZE 0x50000
#define AP_MODEM_MSG_SIZE 0x200
#else
#define AP_MODEM_NV_SIZE  0x0
#define AP_OM_BUFFER_SIZE 0x0
#endif
#define AP_VIRTUAL_CALL_DOWNLINK_SIZE  0x1000
#define AP_VIRTUAL_CALL_UPLINK_SIZE    0x1000

#ifdef CONFIG_HIFI_SUPPORT_VIBRATOR
#define AP_AUDIO_VIBRATOR_DATA_SIZE  0xF000
#else
#define AP_AUDIO_VIBRATOR_DATA_SIZE  0x0
#endif

#define DSP_SOCP_BUFFER_SIZE 0x2000

#define DSP_MUSIC_DATA_LOCATION          DSP_UNSEC_BASE_ADDR
#define PCM_PLAY_BUFF_LOCATION           (DSP_MUSIC_DATA_LOCATION + DSP_MUSIC_DATA_SIZE)
#define PCM_OM_BUFF_LOCATION             (PCM_PLAY_BUFF_LOCATION + PCM_PLAY_BUFF_USED_SIZE)
#define DRV_DSP_UART_TO_MEM              (PCM_PLAY_BUFF_LOCATION + PCM_PLAY_BUFF_SIZE)
#define DRV_DSP_STACK_TO_MEM             (DRV_DSP_UART_TO_MEM + DRV_DSP_UART_TO_MEM_SIZE)
#define DSP_ICC_DEBUG_LOCATION           (DRV_DSP_STACK_TO_MEM + DRV_DSP_STACK_TO_MEM_SIZE)
#define DSP_SOCP_BUFFER_ADDR             (DSP_ICC_DEBUG_LOCATION + DSP_ICC_DEBUG_SIZE)
#define DSP_FLAG_DATA_ADDR               (DSP_SOCP_BUFFER_ADDR + DSP_SOCP_BUFFER_SIZE)
#define DSP_SEC_HEAD_BACKUP              (DSP_FLAG_DATA_ADDR + DSP_FLAG_DATA_SIZE)
#define DSP_AP_NV_DATA_ADDR              (DSP_SEC_HEAD_BACKUP + DSP_SEC_HEAD_SIZE)
#define DSP_AP_MAILBOX_BASE_ADDR         (DSP_AP_NV_DATA_ADDR + DSP_AP_NV_DATA_SIZE)
#define CODEC_DSP_OM_DMA_BUFFER_ADDR     (DSP_AP_MAILBOX_BASE_ADDR + DSP_AP_MAILBOX_TOTAL_SIZE)
#define CODEC_DSP_OM_DMA_CONFIG_ADDR     (CODEC_DSP_OM_DMA_BUFFER_ADDR + CODEC_DSP_OM_DMA_BUFFER_SIZE)
#define CODEC_DSP_SOUNDTRIGGER_BASE_ADDR (CODEC_DSP_OM_DMA_CONFIG_ADDR + CODEC_DSP_OM_DMA_CONFIG_SIZE)
#define DSP_PCM_UPLOAD_BUFFER_ADDR       (CODEC_DSP_SOUNDTRIGGER_BASE_ADDR + CODEC_DSP_SOUNDTRIGGER_TOTAL_SIZE)
#define DSP_AUDIO_EFFECT_PARAM_ADDR      (DSP_PCM_UPLOAD_BUFFER_ADDR + DSP_PCM_UPLOAD_BUFFER_SIZE)
#define HIFI_USB_DRIVER_SHARE_MEM_ADDR   (DSP_AUDIO_EFFECT_PARAM_ADDR + DSP_AUDIO_EFFECT_PARAM_BUFF_SIZE)
#define AUDIO_DP_DATA_LOCATION     (HIFI_USB_DRIVER_SHARE_MEM_ADDR + HIFI_USB_DRIVER_SHARE_MEM_SIZE)
#define AP_AUDIO_PA_ADDR           (AUDIO_DP_DATA_LOCATION + AUDIO_DP_DATA_BUFF_SIZE)
#define AP_AUDIO_WAKEUP_RINGBUFFER_ADDR (AP_AUDIO_PA_ADDR + AP_AUDIO_PA_BUFF_SIZE)
#define AP_AUDIO_WAKEUP_CAPTURE_ADDR    (AP_AUDIO_WAKEUP_RINGBUFFER_ADDR + AP_AUDIO_WAKEUP_RINGBUFEER_SIZE)
#define AP_AUDIO_WAKEUP_MODEL_ADDR         (AP_AUDIO_WAKEUP_CAPTURE_ADDR + AP_AUDIO_WAKEUP_CAPTURE_SIZE)
#define AP_AUDIO_LP_WAKEUP_RINGBUFFER_ADDR (AP_AUDIO_WAKEUP_MODEL_ADDR + AP_AUDIO_WAKEUP_MODEL_SIZE)
#define AP_AUDIO_LP_WAKEUP_CAPTURE_ADDR    (AP_AUDIO_LP_WAKEUP_RINGBUFFER_ADDR + AP_AUDIO_LP_WAKEUP_RINGBUFEER_SIZE)
#define AP_MODEM_NV_ADDR   (AP_AUDIO_LP_WAKEUP_CAPTURE_ADDR + AP_AUDIO_LP_WAKEUP_CAPTURE_SIZE)
#define AP_OM_BUFFER_ADDR  (AP_MODEM_NV_ADDR + AP_MODEM_NV_SIZE)
#define AP_VIRTUAL_CALL_DOWNLINK_ADDR (AP_OM_BUFFER_ADDR + AP_OM_BUFFER_SIZE)
#define AP_VIRTUAL_CALL_UPLINK_ADDR   (AP_VIRTUAL_CALL_DOWNLINK_ADDR + AP_VIRTUAL_CALL_DOWNLINK_SIZE)
#define AP_AUDIO_VIBRATOR_ADDR (AP_VIRTUAL_CALL_UPLINK_ADDR + AP_VIRTUAL_CALL_UPLINK_SIZE)
#define HIFI_WIRED_HEADSET_PARA_ADDR (AP_AUDIO_VIBRATOR_ADDR + AP_AUDIO_VIBRATOR_DATA_SIZE)
#ifdef CONFIG_HUAWEI_AUDIO
#define HIFI_SOUND_ENHANCE_PARA_ADDR (HIFI_WIRED_HEADSET_PARA_ADDR + DSP_PARA_DOWNLOAD_BUFFER_SIZE)
#define DSP_UNSEC_RESERVE_ADDR (HIFI_SOUND_ENHANCE_PARA_ADDR + DSP_SOUND_ENHANCE_BUFF_SIZE)
#else
#define DSP_UNSEC_RESERVE_ADDR (HIFI_WIRED_HEADSET_PARA_ADDR + DSP_PARA_DOWNLOAD_BUFFER_SIZE)
#endif

#define DSP_OM_LOG_SIZE         0xA000
#define DSP_OM_LOG_ADDR         (DRV_DSP_UART_TO_MEM - DSP_OM_LOG_SIZE)
#define DSP_DUMP_BIN_SIZE       (DSP_AP_MAILBOX_BASE_ADDR + DSP_AP_MAILBOX_TOTAL_SIZE - DSP_OM_LOG_ADDR)
#define DSP_DUMP_BIN_ADDR       DSP_OM_LOG_ADDR

#define DRV_DSP_PANIC_MARK              DSP_FLAG_DATA_ADDR
#define DRV_DSP_UART_LOG_LEVEL          (DRV_DSP_PANIC_MARK + 4)
#define DRV_DSP_UART_TO_MEM_CUR_ADDR    (DRV_DSP_UART_LOG_LEVEL + 4)
#define DRV_DSP_EXCEPTION_NO            (DRV_DSP_UART_TO_MEM_CUR_ADDR + 4)
#define DRV_DSP_IDLE_COUNT_ADDR         (DRV_DSP_EXCEPTION_NO + 4)
#define DRV_DSP_LOADED_INDICATE         (DRV_DSP_IDLE_COUNT_ADDR + 4)
#define DRV_DSP_KILLME_ADDR             (DRV_DSP_LOADED_INDICATE + 4)
#define DRV_DSP_WRITE_MEM_PRINT_ADDR    (DRV_DSP_KILLME_ADDR + 4)
#define DRV_DSP_POWER_STATUS_ADDR       (DRV_DSP_WRITE_MEM_PRINT_ADDR + 4)
#define DRV_DSP_NMI_FLAG_ADDR           (DRV_DSP_POWER_STATUS_ADDR + 4)
#define DRV_DSP_ODT_FAMA_CONFIG_ADDR    (DRV_DSP_NMI_FLAG_ADDR + 4)
#define DRV_DSP_FLAG_ALP_NOC_CHECK      (DRV_DSP_ODT_FAMA_CONFIG_ADDR + sizeof(struct drv_fama_config))
#define DRV_DSP_SLT_FLAG_ADDR           (DRV_DSP_FLAG_ALP_NOC_CHECK + 4)
#define DRV_DSP_PCM_THREAD_DATA_ADDR    (DRV_DSP_SLT_FLAG_ADDR + 4)
#define DRV_DSP_SCREEN_STATUS           (DRV_DSP_PCM_THREAD_DATA_ADDR + DSP_PCM_THREAD_DATA_SIZE)
#define DRV_DSP_FLAG_DATA_RESERVED      (DRV_DSP_SCREEN_STATUS + DRV_DSP_SCREEN_STATUS_SIZE)

#define DSP_IMAGE_OCRAMBAK_SIZE        0x30000
#define DSP_SEC_HEAD_SIZE              0x1000

#ifdef CONFIG_HIFI_IPC_3660
#define DSP_SEC_REGION_SIZE            RESERVED_HIFI_PHYMEM_SIZE
#ifdef CONFIG_HIFI_MEMORY_21M
#define DSP_RUN_SIZE                   0xF00000
#elif defined(CONFIG_2MIC_LP_WAKEUP)
#define DSP_RUN_SIZE                   0xD00000
#else
#define DSP_RUN_SIZE                   0xB00000
#endif
#define DSP_IMAGE_TCMBAK_SIZE          0x34000

#define DSP_RUN_ITCM_SIZE              0x9000
#define DSP_RUN_DTCM_SIZE              0x28000

#define DSP_SEC_BASE_ADDR              RESERVED_HIFI_PHYMEM_BASE

#define DSP_RUN_LOCATION               DSP_SEC_BASE_ADDR
#define DSP_IMAGE_OCRAMBAK_LOCATION    (DSP_RUN_LOCATION + DSP_RUN_SIZE)
#define DSP_IMAGE_TCMBAK_LOCATION      (DSP_IMAGE_OCRAMBAK_LOCATION + DSP_IMAGE_OCRAMBAK_SIZE)
#define DSP_SEC_HEAD_LOCATION          (DSP_IMAGE_TCMBAK_LOCATION + DSP_IMAGE_TCMBAK_SIZE)
#define DSP_SEC_RESERVE_ADDR           (DSP_SEC_HEAD_LOCATION + DSP_SEC_HEAD_SIZE)

#ifndef CONFIG_AUDIO_COMMON_IMAGE
#define DRV_WATCHDOG_BASE_ADDR         SOC_ACPU_ASP_WD_BASE_ADDR
#endif
#else /* CONFIG_HIFI_IPC_3660 */
#define DSP_SEC_REGION_SIZE            0xB80000
#define DSP_RUN_SIZE                   0xB00000
#define DSP_IMAGE_TCMBAK_SIZE          0x1E000
#define DSP_SEC_RESERVE_SIZE           0x31000

#define DSP_RUN_ITCM_SIZE              0x6000
#define DSP_RUN_DTCM_SIZE              0x18000

#define DSP_SEC_BASE_ADDR              (DSP_UNSEC_BASE_ADDR + DSP_UNSEC_REGION_SIZE)
#define DSP_IMAGE_OCRAMBAK_LOCATION    DSP_SEC_BASE_ADDR
#define DSP_IMAGE_TCMBAK_LOCATION      (DSP_IMAGE_OCRAMBAK_LOCATION + DSP_IMAGE_OCRAMBAK_SIZE)
#define DSP_SEC_HEAD_LOCATION          (DSP_IMAGE_TCMBAK_LOCATION + DSP_IMAGE_TCMBAK_SIZE)
#define DSP_SEC_RESERVE_ADDR           (DSP_SEC_HEAD_LOCATION + DSP_SEC_HEAD_SIZE)
#define DSP_RUN_LOCATION               (DSP_SEC_RESERVE_ADDR + DSP_SEC_RESERVE_SIZE)
#ifndef CONFIG_AUDIO_COMMON_IMAGE
#define DRV_WATCHDOG_BASE_ADDR         SOC_ACPU_ASP_Watchdog_BASE_ADDR
#endif
#endif /* CONFIG_HIFI_IPC_3660 */


#ifdef CONFIG_AUDIO_COMMON_IMAGE
#define DRV_WATCHDOG_BASE_ADDR         0
#endif

#define SIZE_PARAM_PRIV       206408 /* refer from function dsp_nv_init in dsp_soc_para_ctl.c */
#define HIFI_SYS_MEM_ADDR     DSP_RUN_LOCATION

#ifndef CONFIG_AUDIO_COMMON_IMAGE
#define SYS_TIME_STAMP_REG    (SOC_ACPU_SCTRL_BASE_ADDR + 0x534)
#else
#define SYS_TIME_STAMP_REG    0x534
#endif

#endif /* __AUDIO_DDR_MAP_H__ */
