# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the rest of the USB drivers
# (the ones that don't fit into any other categories)
#

obj-$(CONFIG_USB_DFU)			+= dfu.o
obj-$(CONFIG_USB_MODE_INIT)		+= chip_usb_mode_init.o
