/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description: protocol header file
 * Create: 2021/12/05
 */
#ifndef __TAG_H__
#define __TAG_H__

/*tag----------------------------------------------------*/
enum obj_tag {
	TAG_FLUSH_META,
	TAG_BEGIN = 0x01,
	TAG_SENSOR_BEGIN = TAG_BEGIN,
	TAG_ACCEL = TAG_SENSOR_BEGIN,
	TAG_GYRO,
	TAG_MAG,
	TAG_ALS,
	TAG_PS,/*5*/
	TAG_LINEAR_ACCEL,
	TAG_GRAVITY,
	TAG_ORIENTATION,
	TAG_ROTATION_VECTORS,
	TAG_PRESSURE,/*0x0a=10*/
	TAG_HALL,
	TAG_MAG_UNCALIBRATED,
	TAG_GAME_RV,
	TAG_GYRO_UNCALIBRATED,
	TAG_SIGNIFICANT_MOTION,/*0x0f=15*/
	TAG_STEP_DETECTOR,
	TAG_STEP_COUNTER,
	TAG_GEOMAGNETIC_RV,
	TAG_HANDPRESS,
	TAG_FINGERSENSE,/*0x14=20*/
	TAG_PHONECALL,
	TAG_GPS_4774_I2C,
	TAG_OIS,
	TAG_TILT_DETECTOR,
	TAG_RPC,/*0x19=25*///should same with modem definition
	TAG_CAP_PROX,
	TAG_MAGN_BRACKET,
	TAG_AGT,
	TAG_COLOR,
	TAG_ACCEL_UNCALIBRATED,/*0x1e = 30*/
	TAG_TOF,
	TAG_DROP,
	TAG_SENSOR_END,//sensor end should < 45
	TAG_HW_PRIVATE_APP_START = 45,/*0x2d=45*/
	TAG_AR = TAG_HW_PRIVATE_APP_START,
	TAG_MOTION,
	TAG_GPS,
	TAG_PDR,
	TAG_CA,
	TAG_FP,/*0x32=50*/
	TAG_KEY,
	TAG_AOD,
	TAG_FLP,
	TAG_ENVIRONMENT,
	TAG_LOADMONITOR,/*0x37=55*/
	TAG_APP_CHRE,
	TAG_FP_UD,
	TAG_HW_PRIVATE_APP_END,//APP_END should < 64, because power log used bitmap
	TAG_MODEM = 128,/*0x80=128*/
	TAG_TP,
	TAG_SPI,
	TAG_I2C,
	TAG_UART,
	TAG_RGBLIGHT,
	TAG_BUTTONLIGHT,/*0x86=135*/
	TAG_BACKLIGHT,
	TAG_VIBRATOR,
	TAG_SYS,
	TAG_LOG,
	TAG_LOG_BUFF,/*0x8b=140*/
	TAG_RAMDUMP,
	TAG_FAULT,
	TAG_SHAREMEM,
	TAG_SHELL_DBG,
	TAG_PD,/*0x90=145*/
	TAG_I3C,
	TAG_DATA_PLAYBACK,
	TAG_CHRE,
	TAG_SENSOR_CALI,
	TAG_CELL,
	TAG_BIG_DATA,
	TAG_END = 0xFF
};

#endif
