#
# Makefile for kernel vendor pcie.
#
ccflags-y += -I$(srctree)/drivers/pci/controller/dwc/

obj-$(CONFIG_PCIE_KPORT) += pcie-kport.o
obj-$(CONFIG_PCIE_KPORT_V1) += pcie-kport-v1.o
obj-$(CONFIG_PCIE_KPORT) += pcie-kport-common.o
obj-$(CONFIG_PCIE_KPORT_IDLE) += pcie-kport-idle.o
obj-$(CONFIG_PCIE_KPORT_PHY_XW) += pcie-kport-phy-xw.o
obj-$(CONFIG_PCIE_KPORT_PHY_KPHY) += pcie-kport-phy-kphy.o
obj-$(CONFIG_PCIE_KPORT_PHY) += pcie-kport-phy-mcu.o
obj-$(CONFIG_PCIE_KPORT_PHY) += pcie-kport-phy.o
obj-$(CONFIG_PCIE_KPORT_TEST) += pcie-kport-test.o
obj-$(CONFIG_PCIE_KPORT_MNTN) += pcie-mntn.o
obj-$(CONFIG_PCIE_KPORT_SLT) += pcie-slt.o
obj-$(CONFIG_PCIE_KPORT_FEB) += pcie-feb.o
obj-$(CONFIG_PCIE_KPORT_MAR) += pcie-mar.o
obj-$(CONFIG_PCIE_KPORT_APR) += pcie-apr.o
obj-$(CONFIG_PCIE_KPORT_MAY) += pcie-may.o
obj-$(CONFIG_PCIE_KPORT_SEP) += pcie-sep.o
obj-$(CONFIG_PCIE_KPORT_BURB) += pcie-burb.o
obj-$(CONFIG_PCIE_KPORT_JUN) += pcie-jun.o
obj-$(CONFIG_PCIE_KPORT_LEXI) += pcie-lexi.o
obj-$(CONFIG_PCIE_KPORT_NAP) += pcie-nap.o
