/*
 * pcie-kport-phy-kphy.h
 *
 * kport PHY Driver
 *
 * Copyright (c) 2020 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef _PCIE_KPORT_PHY_KPHY_H
#define _PCIE_KPORT_PHY_KPHY_H

#include <linux/bitops.h>
#include <linux/types.h>

/* MCU begin */
struct mcu_irq_info {
	uint32_t mask_reg;
	uint32_t mask_bits;
};
#define MCU_IRQ_MASK_NUM 2
#define PHY_DFX_CRG_ADDR        0x604
#define PHY_PCLK_COM_INTR_MASK_REG  0x408
#define PHY_GP_INTR3_TRIG_MASK  0x954
#define PHY_GP_INTR3_TRIG_VAL   0x958
#define PHY_GP_INTR23_TRIG_MASK_H   0x988
#define PHY_GP_INTR23_TRIG_VAL_H    0x998

/* MCU end */

/* Intr start */
#define PCS_TOP_MASK_REG	(0x4)
#define PCS_TOP_MASK_BIT	(0x1 << 0)
/* Intr end */

#define PHY_POWERON_STATUS_BIT	7
#define PHY_POWERON_TIMEOUT		70

/* Maintenance info */
#define PHY_DCC_INTR_FLAG				0x1000
#define PHY_TX_RX_TERMK_INTR_FLAG		0x404
#define PHY_PLL_GEN12_VCO_BAND			0xB30
#define PHY_PLL_GEN3_VCO_BAND			0xB38
#define PHY_DCC_CALI_RES				0x154C
#define PHY_TX_TERMK_RES				0x0A78
#define PHY_RX_TERMK_RES				0x0A88
#define PHY_DIGITAL_PLL_LOCK_RES		0xB70

#define PHY_DCC_INTR_FLAG_MASK	(0x1 << 29)
#define PHY_DCC_INTR_FLAG_OFFSET	29
#define PHY_TX_TERMK_INTR_FLAG_MASK	(0x1 << 10)
#define PHY_TX_TERMK_INTR_FLAG_OFFSET	10
#define PHY_RX_TERMK_INTR_FLAG_MASK	(0x1 << 11)
#define PHY_RX_TERMK_INTR_FLAG_OFFSET	11
#define PHY_GEN1_PLL_ICP_MASK	(0x1F << 23)
#define PHY_GEN1_PLL_ICP_SET	(0xA << 23)
#define PHY_GEN2_PLL_ICP_MASK	(0x1F << 23)
#define PHY_GEN2_PLL_ICP_SET	(0xA << 23)
#define PHY_PLL_LDO_SEL_MASK	(0xF << 4)
#define PHY_PLL_LDO_SEL_SET	(0x6 << 4)
#define PHY_RG_TX_RTERMK_V48_BIT 8

/* GEN3 related */
#define PHY_REG_VALID_DY_SEL_ADC_EN_ADDR	0x09AC
#define PHY_REG_PV_DEBUG_CFG_ADDR		0x09B0
#define PHY_REG_COM_TST_ADDR			0x09B4
#define PHY_AD_PLL_LOCK_STATUS_ADDR		0x0A00
#define PHY_TX_TERMK_WATING_TIME_ADDR	0x0A70
#define PHY_RG_TX_RTERMK_V48_ADDR		0x0A78
#define PHY_RG_BG_VREF_SEL_ADDR			0x0AC8
#define PHY_TX_TERMK_WATING_TIME1_2_ADDR 	0x0A84
#define PHY_PLL_UPDATE_CTRL_ADDR        0x0B0C
#define PHY_PLL_BANDCTRLR1_ADDR			0x0B30
#define PHY_PLL_BANDCTRLR2_ADDR			0x0B38
#define PHY_AD_PLL_LOCK_ADDR			0x0B70
#define PHY_PLL_REFCLK_SEL_ADDR			0x0B78
#define PHY_PLL_LOCK_WAIT_TIME_ADDR		0x0B90
#define PHY_ADC_CLK_DIV_ADDR			0x0E00
#define PHY_INTF_COM_SIG_CTRL_EN_REG	0x0F08
#define PHY_REG_DA_PLL_LDO_EN_ADDR		0x0F44
#define PHY_REG_DA_PLL_BIAS_EN_ADDR		0x0F48
#define PHY_PCLK_LANE_INT_SRC_REG_ADDR	0x1000
#define PHY_CRG_PER_LANE_ADDR			0x1300
#define PHY_PCS_POWER_STATUS_ADDR		0x1400
#define PHY_RG_LOCAL_LF_FS_ADDR			0x1408
#define PHY_RXOFSTSTATUS_ADDR			0x1528
#define PHY_RXUPDTCTRL_EN_ADDR			0x152C
#define PHY_RG_RX0_GAIN_VREF_ADDR		0x1530
#define PHY_RX_EQA_CTRL_ADDR			0x1534
#define PHY_RXFOMCTRL0_ADDR				0x1538
#define PHY_RXFOMCTRL1_ADDR				0x153C
#define PHY_DFE_MANUAL_EN_ADDR			0x1540
#define PHY_RG_RX0_LOS_HYS_ADDR			0x1548
#define PHY_TXDEEMPHCTRL6DB_ADDR		0x1550
#define PHY_TXDEEMPHCTRL3D5DB_ADDR		0x1554
#define PHY_TXDEEMPHCTRL0DB_ADDR		0x1558
#define PHY_RG_G2_G3_KI_FINE_ADDR		0x1564
#define PHY_RXDFECTRL0_ADDR				0x1580
#define PHY_DBG_INFO_SEL_ADDR			0x158C
#define PHY_DBG_STS_REG_ADDR			0x1594
#define PHY_DCC_WAITING_TIME_ADDR		0x15A0
#define PHY_DFE_EN_ADDR					0x15B4
#define PHY_REG_RX0_DC_TEST_SEL			0x1A04
#define PHY_DA_RX0_CDR_LDO_EN_ADDR		0x1B20
#define PHY_RG_PIPE_TXDEEMPH_CTRL_ADDR		0x1B44
#define PHY_REG_DA_RX_CDR_LDO_EN_ADDR	0x1B64
#define PHY_RG_RX0_EQ_PAT_MODE_CFG_ADDR		0x1A04
#define PHY_RG_RX0_GAIN_SEL_ADDR		0x1A18
#define PHY_PMA_RX_ATT_RG_RX0_ADDR  	0x1A1C
#define PHY_RG_G1_KI_FINE_ADDR			0x1A20
#define PHY_REG_DA_TX_EQ_CTRL_ADDR		0x1B18
#define PHY_REG_DA_DFE_CTRL_EN_ADDR		0x1B24
#define PHY_REG_DA_TX_EQ_FFE			0x1B5C
#define PHY_REG_DA_DFE_CTRL_VAL_ADDR	0x1B68
#define PHY_RG_EBUF_RD_THRD_ADDR		0x1C04

#define PHY_REG_DA_DFE_CTRL_VAL_VAL     0x0
#define PHY_PLL_UPDATE_CTRL_VAL         0x800400FF
#define PHY_PLL_REFCLK_SEL_VAL          0x0
#define PHY_RX_EQA_CTRL_SEL_C_VAL		0x201F0010
#define PHY_RX_EQA_TH_VAL				0x201F0030
#define PHY_RG_RX_CTRL_GSA_TH_VAL		0x23900060
#define PHY_RG_BG_VREF_SEL_VAL			0x10000
#define PHY_REG_DA_DFE_CTRL_EN_VAL		0x1
#define PHY_REG_DA_TX_EQ_CTRL_VAL_VAL	0xF
#define PHY_REG_DA_TX_EQ_FFE_VAL		0x600
#define PHY_RXUPDTCTRL_VAL				0xEE001F7F
#define PHY_DFE_MANUAL_EN_VAL			0xE0D1000
#define PHY_DFE_EN_VAL					0x4200
#define PHY_DFE_CTRL_VAL				0x800000
#define PHY_PMA_RX_ATT_RG_RX0_VAL		0x000000FF
#define PHY_RG_RX0_GAIN_SEL_VAL			0x00000888
#define PHY_RG_G1_KI_FINE_VAL			0x00011280
#define PHY_RG_G2_G3_KI_FINE_VAL		0x20009084
#define PHY_RG_RX0_LOS_HYS_VAL			0x00010053
#define PHY_RG_RX0_GAIN_VREF_VAL		0x23900020
#define PHY_RG_RX0_EQ_PAT_MODE_CFG_VAL 		0x1CA344
#define PHY_RG_EBUF_RD_THRD_VAL			0x00001010
#define PHY_DCC_WAITING_TIME_VAL		0x0004CCD0
#define PHY_TX_TERMK_WATING_TIME_VAL	0x00733177
#define PHY_TX_TERMK_WATING_TIME1_2_VAL	0x00013331
#define PHY_PLL_LOCK_WAIT_TIME_VAL		0x14FF
#define PHY_TXDEEMPHCTRL6DB_VAL			0x10002f00
#define PHY_TXDEEMPHCTRL3D5DB_VAL		0xb003400
#define PHY_TXDEEMPHCTRL0DB_VAL			0x3f00
#define PHY_RG_PIPE_TXDEEMPH_CTRL_VAL	0x76000
#define PHY_RG_LOCAL_LF_FS_VAL			0xf3f
#define PHY_RG_LOCAL_LF_FS_V48_VAL		0xc2f
#define PHY_PCS_STATUS_MASK				0xFFFFFF7F
#define PHY_PLL_GEN12_VCO_BAND_MASK		0xFFFFFC00
#define PHY_PLL_GEN3_VCO_BAND_MASK		0xFFFFFC00
#define PHY_DCC_CALI_RES_MASK			0xFFFFF000
#define PHY_TX_TERMK_RES_MASK			0xFFFFFE00
#define PHY_RX_TERMK_RES_MASK			0xFFFFFFE0
#define PHY_DIGITAL_PLL_LOCK_RES_MASK	0xFFFFFFFB

/* eye param */
#define QUADRANT1				0x21
#define QUADRANT2				0x2
#define QUADRANT3				0x14
#define QUADRANT4				0x38
#define GRAPH_LEN				32
#define GRAPH_WID				33
#define QUA_LEN					16
#define IMAGE_WIDTH				66
#define FOM_COUNT_MAX			255
#define PHY3_FOM_TIMEOUT	200

/* bgr trimming */
#define ADC_VALID_MAX	130
#define ADC_VALID_MIN	125
#define ADC_APPR_VALUE	131
#define TRIMMING_TIMES	16

#endif /* _PCIE_KPORT_PHY_KPHY_H */