# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FLAT_VIBRATOR)   += flat_vibrator.o
obj-$(CONFIG_LINEAR_VIBRATOR) += linear_vibrator.o
obj-$(CONFIG_POWERKEY_SPMI)   += powerkey_spmi.o
obj-$(CONFIG_POWERKEY_SPMI)   += powerkey_event.o
