ccflags-y += -Wall -Werror
ccfags-y += -I$(srctree)/drivers/platform_drivers/ap/platform/$(OBB_PRODUCT_NAME)

EXTRA_CFLAGS += -Idrivers/platform_drivers/tzdriver

obj-$(CONFIG_LPMCU_BB) += rdr_lpm3.o


