ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow
obj-$(CONFIG_ARM_MEMLAT_MON)    += arm_memlat_mon.o
obj-$(CONFIG_DEVFREQ_GOV_MEMLAT)    += governor_memlat.o
obj-$(CONFIG_DEVFREQ_DEVBW)    += devfreq_devbw.o

ccflags-y += -I$(srctree)/drivers/devfreq
