


obj-$(CONFIG_FILE_BASED_ENCRYPTO) += file_encry/
obj-y += cpumask/
obj-$(CONFIG_HW_VOTE) += hw_vote/
obj-$(CONFIG_PLATFORM_QOS) += qos/
obj-y += dpm/
obj-$(CONFIG_SR)                      += pm/
obj-y += l3cache/
obj-$(CONFIG_GPUFREQ) += gpufreq/
obj-$(CONFIG_NPU_PM) += npu_pm/
obj-$(CONFIG_ONSYS_AVS) += onsys_avs/
obj-$(CONFIG_LPM_HKADC) += adc/
obj-y += perfhub/
obj-$(CONFIG_DDR_PLATFORM_DDRC)   += ddrc/
obj-$(CONFIG_PERF_CTRL) += perf_ctrl/
obj-$(CONFIG_LPMCU_DEBUG) += lpmcu_debug/
obj-$(CONFIG_HOTPLUG_AGENT) += hotplug_agent/
obj-$(CONFIG_SOC_PG_FEATURE_DEVDRV) += soc_pg_feature_modem/
obj-y += freqdump/
obj-$(CONFIG_DFX_PERF_STAT)+= perf_stat/
obj-$(CONFIG_DFX_PERF_STAT64)+= perf_stat/
obj-$(CONFIG_BUS_MONITOR)+= bus_monitor/
obj-$(CONFIG_BUS_MONITOR_TEST)+= bus_monitor/


