/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description: initialization and save trace log of pattern trace
 * Create: 2021-10-28
 */

#ifndef _DMSSPT_REGISTERS_CHAMAELEON_H_
#define _DMSSPT_REGISTERS_CHAMAELEON_H_

#define PLATFORM_LIST \
	{.compatible = "hisilicon,chamaeleon-dmsspt",}, \
	{},\

#define DDRC_DMI_NUM	2
#define TBED_DMC0 0x40000
#define TBED_DMC1 0x41000

/* pattern trace's related registers */
#define SOC_QICE_TBED_ABNML_NS_INT_ST_STR	SOC_QICE_TBED_ABNML_NS_INT_ST_UNION
#define SOC_QICE_TBED_ABNML_NS_INT_CLR_STR	SOC_QICE_TBED_ABNML_NS_INT_CLR_UNION
#define SOC_QICE_TBED_ABNML_NS_INT_ST_PTR	SOC_QICE_TBED_ABNML_NS_INT_ST_ADDR
#define SOC_QICE_TBED_ABNML_NS_INT_CLR_PTR	SOC_QICE_TBED_ABNML_NS_INT_CLR_ADDR

#define QICE_TBED_ABNML_NS_INT_ST_PTR(base) \
	((volatile SOC_QICE_TBED_ABNML_NS_INT_ST_STR *)SOC_QICE_TBED_ABNML_NS_INT_ST_PTR(base))
#define QICE_TBED_ABNML_NS_INT_CLR_PTR(base) \
	((volatile SOC_QICE_TBED_ABNML_NS_INT_CLR_STR *)SOC_QICE_TBED_ABNML_NS_INT_CLR_PTR(base))
#define QICE_TBED_GLB_ADDR_PTR(base) \
	((volatile SOC_QICE_TBED_GLB_ADDR_CTRL_UNION *)SOC_QICE_TBED_GLB_ADDR_CTRL_ADDR(base))
#define QICE_TBED_TRACE_CTRL0_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_CTRL0_UNION *)SOC_QICE_TBED_TRACE_CTRL0_ADDR(base))
#define QICE_TBED_TRACE_CTRL1_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_CTRL1_UNION *)SOC_QICE_TBED_TRACE_CTRL1_ADDR(base))
#define QICE_TBED_TRACE_REC0_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_REC0_UNION *)SOC_QICE_TBED_TRACE_REC0_ADDR(base))
#define QICE_TBED_TRACE_REC1_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_REC1_UNION *)SOC_QICE_TBED_TRACE_REC1_ADDR(base))
#define QICE_TBED_TRACE_FILTER0_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_FILTER0_UNION *)SOC_QICE_TBED_TRACE_FILTER0_ADDR(base))
#define QICE_TBED_TRACE_FILTER1_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_FILTER1_UNION *)SOC_QICE_TBED_TRACE_FILTER1_ADDR(base))
#define QICE_TBED_TRACE_FILTER2_PTR(base, mid_grps) \
	((volatile SOC_QICE_TBED_TRACE_FILTER2_UNION *)SOC_QICE_TBED_TRACE_FILTER2_ADDR(base, mid_grps))
#define QICE_TBED_TRACE_FREQ_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_FREQ_UNION *)SOC_QICE_TBED_TRACE_FREQ_ADDR(base))
#define QICE_TBED_TRACE_INT_EN_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_INT_EN_UNION *)SOC_QICE_TBED_TRACE_INT_EN_ADDR(base))
#define QICE_TBED_TRACE_STAT0_PTR(base) \
	((volatile SOC_QICE_TBED_TRACE_STAT0_UNION *)SOC_QICE_TBED_TRACE_STAT0_ADDR(base))
#define QICE_TBED_TRACE_STAT1_PTR(base, chans) \
	((volatile SOC_QICE_TBED_TRACE_STAT1_UNION *)SOC_QICE_TBED_TRACE_STAT1_ADDR(base, chans))
#define QICE_TBED_TRACE_STAT2_PTR(base, chans) \
	((volatile SOC_QICE_TBED_TRACE_STAT2_UNION *)SOC_QICE_TBED_TRACE_STAT2_ADDR(base, chans))
#define QICE_TBED_TRACE_STAT3_PTR(base, chans) \
	((volatile SOC_QICE_TBED_TRACE_STAT3_UNION *)SOC_QICE_TBED_TRACE_STAT3_ADDR(base, chans))
#define QICE_GLB_TB_COMMON_PTR(base) \
	((volatile SOC_QICE_GLB_TB_COMMON_UNION *)SOC_QICE_GLB_TB_COMMON_ADDR(base))
#define QICE_GLB_TB_TRACE_START_PTR(base) \
	((volatile SOC_QICE_GLB_TB_TRACE_START_UNION *)SOC_QICE_GLB_TB_TRACE_START_ADDR(base))
#define QICE_GLB_TB_TRACE_STOP_PTR(base) \
	((volatile SOC_QICE_GLB_TB_TRACE_STOP_UNION *)SOC_QICE_GLB_TB_TRACE_STOP_ADDR(base))

#define INTLV_GRAN_MAX_VAL	0x3
#define INTLV_GRAN_START_VALUE0

#define CPU_ASI_NUM	6
#define DDR_SIZE_16G	0x400000000ULL
#define DDR_SIZE_16G512M	0x420000000ULL
#define DDR_SIZE_32G	0x800000000ULL
#define DDR_SIZE_32G512M	0x820000000ULL
#define ADDR_SHIFT_MODE_1_START_ADDR	DDR_SIZE_16G
#define ADDR_SHIFT_MODE_1_END_ADDR	DDR_SIZE_16G512M
#define ADDR_SHIFT_MODE_2_START_ADDR	DDR_SIZE_32G
#define ADDR_SHIFT_MODE_2_END_ADDR	DDR_SIZE_32G512M

#endif
