ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/mntn/blackbox \
             -I$(srctree)/platform_source/cee/drivers/ddrc \
             -Wall -Werror

obj-$(CONFIG_DDR_QICE_PT) += dmss_pt_drv.o dmss_pt_dump.o