#
# Makefile for kernel camera buck driver
#
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

obj-$(CONFIG_KERNEL_CAMERA_BUCK) += hw_buck.o
obj-$(CONFIG_KERNEL_CAMERA_BUCK) += fan53526.o
obj-$(CONFIG_KERNEL_CAMERA_BUCK) += rt5748b.o
obj-$(CONFIG_KERNEL_CAMERA_BUCK) += ktb8330.o
