ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2

obj-$(CONFIG_SR_MNTN_SYS_WAKE) += sys_wake/
obj-$(CONFIG_SR_MNTN_PRECHECK) += pre_check/
obj-$(CONFIG_SR_MNTN_AP_WAKE)  += ap_wake/
obj-$(CONFIG_SR_MNTN_TICKMARK) += tick_mark/
obj-$(CONFIG_SR_MNTN_UART)     += uart/
obj-$(CONFIG_SR_MNTN_CLOCK)    += clock/
obj-$(CONFIG_SR_MNTN_IO)       += io/
obj-$(CONFIG_SR_MNTN_PMU)      += pmu/
obj-$(CONFIG_SR_MNTN_WDT)      += watchdog/
