ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/csi
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/fpga
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/io

obj-$(CONFIG_KERNEL_CAMERA_USE_IMX600HYBRID) += imx600hybrid.o
obj-$(CONFIG_KERNEL_CAMERA_USE_OV9282) += ov9282.o
obj-$(CONFIG_KERNEL_CAMERA_USE_OV9282) += ov9286.o
obj-$(CONFIG_KERNEL_CAMERA_USE_OV9282) += imx580.o
obj-$(CONFIG_KERNEL_CAMERA_USE_IMX576) += imx576.o
obj-$(CONFIG_KERNEL_CAMERA_USE_IMX616) += imx616.o
obj-$(CONFIG_KERNEL_CAMERA_USE_OV8856) += ov8856.o
obj-$(CONFIG_KERNEL_CAMERA_USE_OV08A10) += ov08a10.o
obj-$(CONFIG_KERNEL_CAMERA_USE_CAMKIT) += hisensor.o
obj-$(CONFIG_KERNEL_CAMERA_USE_IMX600IMX351HYBRID) += imx600imx351hybrid.o
obj-$(CONFIG_KERNEL_CAMERA_USE_IMX600IMX350T) += imx600imx350t.o
obj-y += m25p80_norflash.o

