ccflags-y += -I$(srctree)/drivers/platform_drivers/tzdriver \
	     -I$(srctree)/platform_source/see/drivers/crypto_core

obj-$(CONFIG_FILE_BASED_ENCRYPTO) += fbex_dev.o \
	fbex_driver.o fbex_screen_handle.o fbex_preload.o
obj-$(CONFIG_FILE_BASED_ENCRYPTO_DBG) += fbex_debug.o
