ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2
obj-$(CONFIG_GPUTOP_FREQ) += gpu_top.o
obj-$(CONFIG_GPU_FHSS) += gpu_fhss.o
obj-$(CONFIG_GPUFREQ_INDEPDENT) += gpufreq.o
obj-$(CONFIG_GPUFREQ_USER_VOTE) += gpufreq_fs.o
obj-$(CONFIG_GPUFLINK) += link/

ccflags-$(CONFIG_GPUFREQ) +=
