ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV110), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV150), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV160), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV120), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV130), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV200), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV250), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV210), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV310), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV300), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV350), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_CAMERA_ISPV220), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif

ifeq ($(CONFIG_CAMERA_ISPV230), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(TARGET_BOARD_PLATFORM)
obj-y += $(TARGET_BOARD_PLATFORM)/
endif
