ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hjpeg
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -Idrivers/media/huwei/camera/hjpeg/hjpeg150
obj-y += hjpgenc150.o


