# ELAN
obj-$(CONFIG_ELAN_TS_KIT_3_0) += elan_ts.o
obj-$(CONFIG_ELAN_TS_KIT_3_0) += elan_mmi.o
EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/tzdriver
EXTRA_CFLAGS += -I$(srctree)/drivers/tzdriver
EXTRA_CFLAGS += -I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
EXTRA_CFLAGS += -I$(srctree)/drivers/devkit/tpkit/3_0
