ccflags-$(CONFIG_UAPP)          += -I$(srctree)/platform_source/see/drivers/uapp

obj-$(CONFIG_UAPP)              += uapp.o
obj-$(CONFIG_UAPP)              += uapp_file_pos.o
obj-$(CONFIG_DFX_DEBUG_FS)      += uapp_debugfs.o
