#ifndef __SOC_INTERRUPTS_APP_H__
#define __SOC_INTERRUPTS_APP_H__ 
#ifdef __cplusplus
extern "C" {
#endif
#include "soc_interrupts_comm.h"
#define INT_LVL_TIMER20 1000
#define INT_LVL_RTC 86
#define INT_LVL_SOCP0 248
#define INT_LVL_SOCP1 249
#define INT_LVL_WDT 237
#define INT_LVL_MAX 224
#define INT_LVL_UICC 39
#define INT_LVL_UPACC_BBP_I1_E 40
#define INT_LVL_UPACC_BBP_I2 41
#define INT_LVL_IPF0 250
#define INT_LVL_IPF1 251
#define INT_LVL_CICOM0_UL 51
#define INT_LVL_CICOM0_DL 52
#define INT_LVL_CICOM1_UL 53
#define INT_LVL_CICOM1_DL 54
#define INT_LVL_UPACC_ARM 55
#define INT_LVL_HDLC_FRM 56
#define INT_LVL_HDLC_DEF 57
#define INT_LVL_TDS_DRX_WAKEUP 152
#define INT_LVL_OTDOA 173
#define INT_LVL_CTU_W 174
#define INT_LVL_CTU_G1 175
#define INT_LVL_CTU_G2 176
#define INT_LVL_W_BBE16_13 177
#define INT_LVL_W_BBE16_14 178
#define INT_LVL_CTU_INT_G INT_LVL_CTU_G1
#define INT_LVL_CTU_INT_W INT_LVL_CTU_W
#define INT_LVL_INT12_G2 1000000
#define INT_LVL_UPACC_DSP 1000000
#define INT_LVL_GU_UPACC_DSP INT_LVL_UPACC_DSP
#define INT_LVL_UPACC_INTR INT_LVL_UPACC_ARM
#define INT_LVL_GU_HDLC_FRM INT_LVL_HDLC_FRM
#define INT_LVL_GU_HDLC_DEF INT_LVL_HDLC_DEF
#define INT_LVL_CICOM_DL INT_LVL_CICOM0_DL
#define INT_LVL_CICOM_UL INT_LVL_CICOM0_UL
#define INT_LVL_GU_CICOM1_DL INT_LVL_CICOM1_DL
#define INT_LVL_GU_CICOM1_UL INT_LVL_CICOM1_UL
#define INT_LVL_CTU_INT_LTE 1000000
#define INT_LVL_CTU_INT_TDS 1000000
#ifdef __cplusplus
}
#endif
#endif
