/** @file
 * Copyright (c) 2020-2020, Hisilicon Tech. Co., Ltd. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#ifndef __RX_REG_H__
#define __RX_REG_H__

/* Dis-Reset config */
#define DPRX0_CLK_GATE_OFFSET 0x10
#define DPRX0_APB_CLK_GATE_BIT BIT(10)
#define DPRX0_EDID_CLK_GATE_BIT BIT(3)
#define DPRX0_APB_BRIDGE_CLK_GATE_BIT BIT(26)
#define DPRX0_AUX_CLK_GATE_BIT BIT(12)
#define DPRX0_GTC_CLK_GATE_BIT BIT(14)

#define DPRX0_RESET_OFFSET 0x60
#define DPRX0_APB_RESET_BIT BIT(16)
#define DPRX0_CTRL_RESET_BIT BIT(7)
#define DPRX0_EDID_RESET_BIT BIT(1)
#define DPRX0_APB_BRIDGE_RESET_BIT BIT(17)

#define DPRX0_DIS_RESET_OFFSET 0x64
#define DPRX0_APB_DIS_RESET_BIT BIT(16)
#define DPRX0_CTRL_DIS_RESET_BIT BIT(7)
#define DPRX0_EDID_DIS_RESET_BIT BIT(1)
#define DPRX0_APB_BRIDGE_DIS_RESET_BIT BIT(17)

#define DPRX1_CLK_GATE_OFFSET 0x10
#define DPRX1_APB_CLK_GATE_BIT BIT(9)
#define DPRX1_EDID_CLK_GATE_BIT BIT(3)
#define DPRX1_APB_BRIDGE_CLK_GATE_BIT BIT(26)
#define DPRX1_AUX_CLK_GATE_BIT BIT(11)
#define DPRX1_GTC_CLK_GATE_BIT BIT(13)

#define DPRX1_RESET_OFFSET 0x60
#define DPRX1_APB_RESET_BIT BIT(15)
#define DPRX1_CTRL_RESET_BIT BIT(4)
#define DPRX1_EDID_RESET_BIT BIT(1)
#define DPRX1_APB_BRIDGE_RESET_BIT BIT(17)

#define DPRX1_DIS_RESET_OFFSET 0x64
#define DPRX1_APB_DIS_RESET_BIT BIT(15)
#define DPRX1_CTRL_DIS_RESET_BIT BIT(4)
#define DPRX1_EDID_DIS_RESET_BIT BIT(1)
#define DPRX1_APB_BRIDGE_DIS_RESET_BIT BIT(17)

/* DPRX MUX SEL */
#define DPRX_MUX_SEL 0x30
#define DPRX_I2S_SEL GENMASK(2, 0)
#define DPRX_DSS0_SEL GENMASK(5, 3)
#define DPRX0_DSS0_SEL_OFFSET 3
#define DPRX1_DSS1_SEL_OFFSET 7
#define DPRX0_DPTX_SEL_OFFSET 9
#define DPRX1_DPTX_SEL_OFFSET 10
#define DPRX_DSS1_SEL GENMASK(8, 6)
#define DPRX_DPTX_SEL GENMASK(11, 9)
#define DPRX0_PHY_SEL BIT(12)

/* HSDT1_SYS_CTRL: EDID Config */
#define HSDT1_EDID_BASE_ADDR_CONFIG 0x508
#define DPRX0_EDID_BASE_ADDR_CONFIG GENMASK(9, 0)
#define DPRX1_EDID_BASE_ADDR_CONFIG GENMASK(19, 10)
#define DPRX0_EDID_BASE_ADDR_CONFIG_OFFSET 0
#define DPRX1_EDID_BASE_ADDR_CONFIG_OFFSET 10
#define DPRX0_EDID_BASE_ADDR 0
#define DPRX1_EDID_BASE_ADDR 512

/* DPRX_DPCP_APB_PWR_CTL */
#define DPRX_POWER_CTRL 0x600

/* DPRX_SCTRL */

/** DPRX_SCTRL **/
#define DPRX_SCTRL_OFFSET 0x100000
#define DPRX_RESET_CTRL 0x0
#define DPRX_FEC_RESET_BIT BIT(0)
#define DPRX_CORE_RESET_BIT BIT(3)
#define DPRX_LANE_RESET_BIT BIT(4)
#define DPRX_AUX_RESET_BIT BIT(5)
#define DPRX_PSR_RESET_BIT BIT(6)
#define DPRX_ATC_RESET_BIT BIT(7)
#define DPRX_PHY_CTRL_RESET_BIT BIT(8)
#define DPRX_RX2TX_RESET_BIT BIT(9)
#define DPRX_AUDIO_LINK_RESET_BIT BIT(10)

#define DPRX_CLK_CTRL 0x4
#define DPRX_FEC_CLK_BIT BIT(0)
#define DPRX_AUX_CLK_EN_BIT BIT(3)
#define DPRX_DSS_CORE_CLK_EN_BIT BIT(4)
#define DPRX_PSR_CLK_EN_BIT BIT(5)
#define DPRX_FEC_EUC_EN_BIT BIT(8)
#define DPRX_FEC_SEARCH_EN_BIT BIT(9)
#define DPRX_RX2TX_CLK_EN_BIT BIT(10)
#define DPRX_FEC_CTRL 0x60
#define DPRX_FEC_BYPASS_BIT BIT(0)
#define DPRX_FEC_EN_BIT BIT(1)

#define DPRX_PCS_CTRL0 0x20
#define DPRX_ICFG_BS_LOCK_NUM_MASK GENMASK(19, 18)
#define DPRX_ICFG_BS_LOCK_NUM_OFFSET 18

#define DPRX_PCS_CTRL1 0x24
#define DPRX_TRAIN_LOST_SYM_ERR_MASK GENMASK(28, 17)
#define DPRX_TRAIN_LOST_SYM_ERR_OFFSET 17

#define DPRX_PCS_CTRL3 0x54
#define DPRX_ICFG_DESKEW_TIME_MASK GENMASK(7, 0)

#define DPRX_LINK_STATUS 0x380
#define DPRX_VIDEO_FMT_VALID BIT(0)
#define DPRX_IS_IDLE_PATTERN BIT(1)
#define DPRX_IS_COMPRESS_STREAM BIT(2)
#define DPRX_COLOR_SPACE_MASK GENMASK(6, 4)
#define DPRX_COLOR_SPACE_OFFSET 4
#define DPRX_BPC_NUM_MASK GENMASK(10, 8)
#define DPRX_BPC_NUM_OFFSET 8
#define DPRX_DFX_LANE_ERROR_VALID BIT(12)

#define DPRX_MSA_MVID 0x404
#define DPRX_MSA_MVID_MASK GENMASK(23, 0)
#define DPRX_MSA_NVID 0x408
#define DPRX_MSA_NVID_MASK GENMASK(23, 0)

#define DPRX_MISC 0x40C
#define DPRX_MISC0_MASK GENMASK(7, 0)
#define DPRX_MISC0_OFFSET 0
#define DPRX_MISC1_MASK GENMASK(15, 8)
#define DPRX_MISC1_OFFSET 8

#define DPRX_MSA_TIMING0 0x410
#define DPRX_MSA_VTOTAL_MASK GENMASK(15, 0)
#define DPRX_MSA_VTOTAL_OFFSET 0
#define DPRX_MSA_HTOTAL_MASK GENMASK(31, 16)
#define DPRX_MSA_HTOTAL_OFFSET 16

#define DPRX_MSA_TIMING1 0x414
#define DPRX_MSA_VSTART_MASK GENMASK(15, 0)
#define DPRX_MSA_VSTART_OFFSET 0
#define DPRX_MSA_HSTART_MASK GENMASK(31, 16)
#define DPRX_MSA_HSTART_OFFSET 16

#define DPRX_MSA_TIMING2 0x418
#define DPRX_MSA_VSW_MASK GENMASK(14, 0)
#define DPRX_MSA_VSW_OFFSET 0
#define DPRX_MSA_VSP_MASK BIT(15)
#define DPRX_MSA_VSP_OFFSET 15
#define DPRX_MSA_HSW_MASK GENMASK(30, 16)
#define DPRX_MSA_HSW_OFFSET 16
#define DPRX_MSA_HSP_MASK BIT(31)
#define DPRX_MSA_HSP_OFFSET 31

#define DPRX_MSA_TIMING3 0x41C
#define DPRX_MSA_VHEIGHT_MASK GENMASK(15, 0)
#define DPRX_MSA_VHEIGHT_OFFSET 0
#define DPRX_MSA_HWIDTH_MASK GENMASK(31, 16)
#define DPRX_MSA_HWIDTH_OFFSET 16

#define DPRX_MSA_STATUS 0x420
#define DPRX_MSA_VALID_BIT BIT(0)

#define DPRX_ATC_CTRL0 0x500
#define DPRX_ATC_EN BIT(0)
#define DPRX_ATC_WDT_EN BIT(1)
#define DPRX_ATC_CTS_WDT_EN BIT(2)
#define DPRX_ATC_MODE BIT(3)
#define DPRX_ATC_TRAIN_TO_CLR BIT(19)
#define DPRX_ATC_LT_RST_GEN_EN BIT(20)

#define DPRX_ATC_CTRL1 0x504
#define DPRX_FAST_EQ_LOOP_CNT GENMASK(11, 0)
#define DPRX_FULL_EQ_LOOP_CNT GENMASK(23, 12)
#define DPRX_FULL_EQ_LOOP_CNT_OFFSET 12

#define DPRX_HS_DET_CTRL0 0x520
#define DPRX_HS_DET_SYM_LEN GENMASK(8, 1)
#define DPRX_HS_DET_SYM_LEN_OFFSET 1
#define DPRX_HS_DET_EN BIT(0)

#define DPRX_HS_DET_CTRL1 0x524
#define DPRX_HS_DET_DLY_TIME GENMASK(19, 0)

#define DPRX_HPD_CTRL0 0x560
#define DPRX_HPD_EN BIT(0)

#define DPRX_ATC_STATUS 0x584
#define ATC_TRAIN_STATUS GENMASK(7, 4)

#define DPRX_GTC_CTRL5 0x614
#define ICFG_TX_GTC_MISS_EN BIT(10)

#define SDP_RPT_EN 0x700
#define DPRX_ALL_SDP_EN GENMASK(11, 0)
#define DRM_INFOFRAME_SDP_EN BIT(11) /* Dynamic Range and Mastering InfoFrame */
#define VBI_INFOFRAME_SDP_EN BIT(10) /* NTSC VBI InfoFrame */
#define MPEG_INFOFRAME_SDP_EN BIT(9) /* MPEG Source InfoFrame */
#define AUDIO_INFOFRAME_SDP_EN BIT(8) /* Audio InfoFrame */
#define SPD_INFOFRAME_SDP_EN BIT(7) /* Source Product Description InfoFrame */
#define AVI_INFOFRAME_SDP_EN BIT(6) /* Auxiliary Video InfoFrame */
#define VEN_SPEC_INFOFRAME_SDP_EN BIT(5) /* Vendor-Specific InfoFrame */
#define PPS_SDP_EN BIT(4) /* Picture Parameter Set SDP */
#define VSC_SDP_EN BIT(3) /* Video Stream Configuration SDP */
#define ISRC_SDP_EN BIT(2) /* ISRC SDP */
#define COPY_MANAG_SDP_EN BIT(1) /* Audio CopyManagement SDP */
#define EXT_SDP_EN BIT(0) /* Extension SDP */

#define DPRX_SDP_DB_HB_FIFO_CNT 0x704
#define DPRX_SDP_DB_LEN GENMASK(15, 0)
#define DPRX_SDP_DB_LEN_OFFSET 0
#define DPRX_SDP_HB_LEN GENMASK(31, 16)
#define DPRX_SDP_HB_LEN_OFFSET 16

#define DPRX_SDP_TYPE_STATUS 0x708
#define DRM_INFOFRAME_SDP_TYPE BIT(11) /* Dynamic Range and Mastering InfoFrame */
#define VBI_INFOFRAME_SDP_TYPE BIT(10) /* NTSC VBI InfoFrame */
#define MPEG_INFOFRAME_SDP_TYPE BIT(9) /* MPEG Source InfoFrame */
#define AUDIO_INFOFRAME_SDP_TYPE BIT(8) /* Audio InfoFrame */
#define SPD_INFOFRAME_SDP_TYPE BIT(7) /* Source Product Description InfoFrame */
#define AVI_INFOFRAME_SDP_TYPE BIT(6) /* Auxiliary Video InfoFrame */
#define VEN_SPEC_INFOFRAME_SDP_TYPE BIT(5) /* Vendor-Specific InfoFrame */
#define PPS_SDP_TYPE BIT(4) /* Picture Parameter Set SDP */
#define VSC_SDP_TYPE BIT(3) /* Video Stream Configuration SDP */
#define ISRC_SDP_TYPE BIT(2) /* ISRC SDP */
#define COPY_MANAG_SDP_TYPE BIT(1) /* Audio CopyManagement SDP */
#define EXT_SDP_TYPE BIT(0) /* Extension SDP */

#define DPRX_SDP_HB_DATA 0x70C
#define DPRX_SDP_DB_DATA 0x710

#define SDP_FIFO_CLR 0x718
#define SDP_REPORT_TIMEOUT_VALUE GENMASK(18, 3) /* timeout value, step in ms */
#define SDP_REPORT_TIMEOUT_OFFSET 3
#define SDP_REPORT_TIMER_EN BIT(2)
#define ICFG_SDP_FIFO_CLR BIT(0)

#define DPRX_VIDEO_CTRL 0x830
#define VIDEO_OUT_EN BIT(0)

#define DPRX_PHY_RST_CTRL 0x900
#define LANE_POWERDOWN_SEL GENMASK(11, 8)

#define DPRX_GTC_CTRL 0x618
#define DPRX_PHY_LANE_POWER_CTRL_SEL GENMASK(11, 8) /* 0: hw ctrl, 1: software ctrl */
#define DPRX_PHY_LANE_POWER_CTRL_SEL_OFFSET 8
#define DPRX_PHY_READY BIT(5)
#define DPRX_PHY_RESET BIT(4)
#define DPRX_PHY_LANE_RESET GENMASK(3, 0)
/* for test fpga */
#define DPRX_PHY_LANE0_RESET BIT(0)
#define DPRX_PHY_LANE1_RESET BIT(1)

#define DPRX_PHY_RWR_CTRL 0x904
#define DPRX_PHY_LANE_POWERDOWN GENMASK(15, 0)

#define DPRX_PHY_RATE_CTRL 0x908

#define DPRX_ALPM_ENABLE 0x980
#define DPRX_HW_ALPM_EN BIT(3)

/* first-level intr */
#define DPRX_INTR_ENABLE 0xC4C
#define DPRX_INTR_MASKED_STATUS 0xC50
#define DPRX_INTR_ORI_STATUS 0xC54
#define TIMING_INTR_ENABLE BIT(0)
#define TRAINING_INTR_ENABLE BIT(1)
#define LINK_CFG_INTR_ENABLE BIT(2)
#define GTC_INTR_ENABLE BIT(3)
#define PSR_INTR_ENABLE BIT(4)
#define SDP_VIDEO_FORMAT_INTR_ENABLE BIT(5)
#define AUDIO_INTR_ENABLE BIT(6)
#define ERR_INTR_ENABLE BIT(7)
#define DEBUG_INTR_ENABLE BIT(8)
#define RSV_INTR_ENABLE BIT(9)
#define AUX_RSV_INTR_ENABLE BIT(10)
#define DPRX_ALL_INTR_ENABLE GENMASK(10, 0)

/* second-level intr - timing related irq */
#define DPRX_TIMING_INTR_ENABLE 0xB00
#define DPRX_TIMING_INTR_MASKED_STATUS 0xB04
#define DPRX_TIMING_INTR_ORI_STATUS 0xB08
#define DPRX_IRQ_VSYNC BIT(0)
#define DPRX_IRQ_HSYNC BIT(1)
#define DPRX_IRQ_VBS BIT(2)
#define DPRX_IRQ_VSTART BIT(3) /* first vactive pixel */
#define DPRX_IRQ_VSYNC_TO_DSS BIT(4)
#define DPRX_IRQ_HSYNC_TO_DSS BIT(5)
#define DPRX_IRQ_VBS_TO_DSS BIT(6)
#define DPRX_IRQ_VSTART_TO_DSS BIT(7) /* first vactive pixel */
#define DPRX_IRQ_VFP BIT(8)
#define DPRX_IRQ_VACTIVE1 BIT(9)
#define DPRX_IRQ_VBS_DPRX BIT(10)
#define DPRX_IRQ_TIME_COUNT BIT(11)

/* second-level intr - training related irq */
#define DPRX_TRAINING_INTR_ENABLE 0xB0C
#define DPRX_TRAINING_INTR_MASKED_STATUS 0xB10
#define DPRX_TRAINING_INTR_ORI_STATUS 0xB14
#define DPRX_IRQ_ATC_TRAIN_TIMEOUT BIT(0)
#define DPRX_IRQ_ATC_TRAIN_DONE BIT(1)
#define DPRX_IRQ_ATC_TRAIN_LOST BIT(2)
#define DPRX_IRQ_DESKEW_DONE BIT(3)
#define DPRX_IRQ_DESKEW_TIMEOUT BIT(4)
#define DPRX_IRQ_ATC_PWR_DONE_LOST BIT(5)
#define DPRX_IRQ_AUX_WR_100 BIT(6)
#define DPRX_IRQ_AUX_WR_101 BIT(7)
#define DPRX_IRQ_AUX_WR_102 BIT(8)
#define DPRX_IRQ_AUX_WR_103 BIT(9)
#define DPRX_IRQ_AUX_WR_104 BIT(10)
#define DPRX_IRQ_AUX_WR_105 BIT(11)
#define DPRX_IRQ_AUX_WR_106 BIT(12)
#define DPRX_IRQ_AUX_WR_600 BIT(13)
#define DPRX_IRQ_MAIN_LINK_STS_DET_LOST BIT(14)
#define DPRX_IRQ_TPS234_DET BIT(15)
#define DPRX_ALL_TRAINING_INTR GENMASK(15, 0)

#define DPRX_PSR_INTR_ENABLE 0xB30
#define DPRX_ALL_PSR_INTR GENMASK(7, 0)

#define DPRX_PSR_INTR_MASKED_STATUS 0xB34
#define DPRX_PSR_ENTRY BIT(0)
#define DPRX_PSR_PRE_ENTRY BIT(1)
#define DPRX_PSR_UPDATE BIT(2)
#define DPRX_PSR_SU_UPDATE BIT(3)
#define DPRX_PSR_EXIT BIT(4)
#define DPRX_SU_INFO BIT(5)
#define DPRX_AUX_WR_00170H BIT(6)
#define DPRX_PSR_ABORT BIT(7)

#define DPRX_PSR_INTR_ORI_STATUS 0xB38

/* second-level intr - sdp/format related irq */
#define DPRX_SDP_VIDEOFORMAT_INTR_ENABLE 0xB3C
#define DPRX_SDP_VIDEOFORMAT_MASKED_STATUS 0xB40
#define DPRX_SDP_VIDEOFORMAT_ORI_STATUS 0xB44
#define DPRX_IRQ_VSYNC_REPORT_SDP BIT(0)
#define DPRX_IRQ_SDP_DB_FIFO_AFULL BIT(1) /* SDP_DB_FIFO already full */
#define DPRX_IRQ_SDP_HB_FIFO_AFULL BIT(2) /* SDP_HB_FIFO already full */
#define DPRX_IRQ_SDP_ERR BIT(3)
#define DPRX_IRQ_FORMAT_CHANGE BIT(4)
#define DPRX_IRQ_TIMING_CHANGE BIT(5)
#define DPRX_IRQ_COMP_CHANGE BIT(6) /* compress-decompress change */
#define DPRX_IRQ_VIDEO2IDLE BIT(7)
#define DPRX_IRQ_IDLE2VIDEO BIT(8)
#define DPRX_IRQ_SDP_DB_W_ERROR BIT(9)
#define DPRX_IRQ_SDP_HB_W_ERROR BIT(10)
#define DPRX_ALL_SDP_VIDEOFORMAT_INTR GENMASK(10, 0)

#define DPRX_SINKSTATUS_CTRL 0xD48
#endif
