# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33.o
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33_fw.o
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33_qi.o
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33_dts.o
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33_tx.o
