obj-$(CONFIG_PLAT_CLK)                  += clk.o
obj-$(CONFIG_PLAT_CLK)                  += plat-clk-gate.o
obj-$(CONFIG_VM_CLK)                    += ace-clk-gate.o
obj-$(CONFIG_PLAT_CLK)                  += clk-hvc.o
obj-$(CONFIG_FSM_PPLL_VOTE)             += clk_fsm_ppll.o
obj-$(CONFIG_PLAT_CLK)                  += clk-ppll.o
obj-$(CONFIG_PLAT_CLK)                  += plat-clk-div.o
obj-$(CONFIG_PLAT_CLK)                  += clk-xfreq.o
obj-$(CONFIG_PLAT_CLK)                  += clk-pmu.o
obj-$(CONFIG_PLAT_CLK)                  += clk-fast-dvfs.o

obj-$(CONFIG_PLAT_CLK)                  += platform/
obj-$(CONFIG_CLK_DEBUG)                 += debug/
obj-$(CONFIG_CLK_MAILBOX_SUPPORT)       += clk-mailbox.o
obj-$(CONFIG_MCLK_SUPPORT)              += clk-mclk.o

obj-$(CONFIG_PLAT_CLK)                  += clk-dvfs.o
obj-$(CONFIG_CLK_PM_MONITOR)            += clk-pm-monitor.o
obj-$(CONFIG_PLL_UNLOCK_DETECT)         += clk-intr.o
obj-$(CONFIG_PERI_DVFS)                 += dvfs/
obj-$(CONFIG_CKM_MODULE)                += clk-monitor.o
obj-$(CONFIG_CLK_SMC_SUPPORT)           += clk-smc.o
