# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WIRELESS_NU1619) += nu1619/
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68/
obj-$(CONFIG_WIRELESS_CPS7181) += cps7181/
obj-$(CONFIG_WIRELESS_CPS4057) += cps4057/
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88/
obj-$(CONFIG_WIRELESS_MT5735) += mt5735/
obj-$(CONFIG_WIRELESS_CPS4029) += cps4029/
obj-$(CONFIG_WIRELESS_MT5727) += mt5727/
obj-$(CONFIG_WIRELESS_STWLC33) += stwlc33/
obj-$(CONFIG_WIRELESS_CPS4067) += cps4067/
obj-$(CONFIG_WIRELESS_MT5785) += mt5785/
# idtp9415 no dev_check, must compile last
obj-$(CONFIG_WIRELESS_IDTP9415) += idtp9415/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_ic_fod.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_ic_iout.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_ic_icali.o
