# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BATTCT_NS3300) += bignum.o bignum_mod.o bignum_mont.o common.o ecc_curve.o
obj-$(CONFIG_BATTCT_NS3300) += ecc_primitive.o gf2m.o gf2m_common.o rng.o sha256.o
