ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hisp
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

EXTRA_CFLAGS += -DHISP250_CAMERA
obj-y += hisp250.o
