

#ifndef _SHENKUO_PCIE_PCS_RB_REGS_H_
#define _SHENKUO_PCIE_PCS_RB_REGS_H_


/* phy优化寄存器 */
#define SHENKUO_PA_PCIE0_PHY_BASE_ADDRESS    0x40109000
#define SHENKUO_PA_PCIE1_PHY_BASE_ADDRESS    0x4010F000

#endif
