#
# Makefile for camera vcm driver
#
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor/vcm
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -Idrivers/media/native/cci/
EXTRA_CFLAGS += -fno-pic

obj-y += hwvcm.o
