subdir-ccflags-$(CONFIG_DFX_BB)        += -Idrivers/platform_drivers/mntn/blackbox/platform_lpm3

obj-$(CONFIG_SR)    += pm.o
obj-$(CONFIG_SR_DEBUG) 				+= lpregs.o
obj-$(CONFIG_PM_LPCTRL)				+= pm_lpctrl.o
obj-$(CONFIG_SR_SYNC)					+= suspend.o


