# MD5: 05ffe96d2ee5883563d56975db8b3465
CFG_PRODUCT_CONTROL_VERSION                 :="141"
CFG_PRODUCT_HISILICON_VERSION               :=kirin990
CFG_PRODUCT_DIFF_NV_FILTER                  :=kirin990_phoenix
CFG_PRODUCT_NV_BIN_MODEM_NUNBER         :=/bin_modem_number "3"
CFG_PRODUCT_NV_XNV_PDT_VERSION            :=Kirin990
CFG_PRODUCT_COMMON_NV_FILE_FORMAT      :=/common_nv_file_format "1"
CFG_PRODUCT_XML_FOLDER_HIONE		      :=1
CFG_PRODUCT_NV_COMPRESS                        :=/compress_nv_file "1"
CFG_PRODUCT_NV_PARSE_CUSTOMIZE			:=/parse_customize "1"
CFG_PRODUCT_SPLIT_NV_BUILD                      := true
CFG_PRODUCT_COMMON_NV_INHERIT_BY_PRODUCT		:= true
CFG_PRODUCT_NCFG_DISTINGUISH_MODEM_FEATURE_ON       := YES
CFG_PRODUCT_NCFG_INDEPENDENT_FEATURE_NV             := YES
CFG_DIAG_SEC_TOOLS                 := YES
