cflags-$(CONFIG_HYPERHOLD) += -I$(srctree)/mm
obj-$(CONFIG_H_MM_SLOW_PATH_COUNT) += slowpath_count.o
obj-$(CONFIG_H_MM_PAGE_TRACE) += mem_trace.o buddy_track.o slub_track.o
obj-$(CONFIG_H_MM_PAGE_TRACE_TEST) += mem_trace_test.o
obj-$(CONFIG_MM_MEM_OFFLINE) += mem_offline.o
obj-$(CONFIG_HYPERHOLD) += memcg_control.o
obj-$(CONFIG_HYPERHOLD) += memcg_reclaim.o
obj-$(CONFIG_VM_COPY) += vm_copy.o
