obj-$(CONFIG_PLAT_CLK)                  += clk-kirin-common.o
obj-$(CONFIG_PLAT_CLK)                  += hisi-clkgate.o
obj-$(CONFIG_PLAT_CLK)                  += hisi-kirin-ppll.o
obj-$(CONFIG_PLAT_CLK)                  += hisi-kirin-fast-dvfs.o
obj-$(CONFIG_CLK_DEBUG)                 += debug/
obj-$(CONFIG_CLK_MAILBOX_SUPPORT)       += hisi-clk-mailbox.o

obj-$(CONFIG_PLAT_CLK)                  += clk-dvfs.o
obj-$(CONFIG_CLK_PM_MONITOR)            += hisi-clk-pm-monitor.o
obj-$(CONFIG_PLAT_CLK)                  += hisi-clk-intr.o

obj-$(CONFIG_PERI_DVFS)                 += dvfs/
obj-$(CONFIG_CKM_MODULE)                += hisi-clk-monitor.o
obj-$(CONFIG_CLK_SMC_SUPPORT)           += hisi-clk-smc.o
