ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2

obj-$(CONFIG_DEVFREQ_GOV_NPU_PM_QOS)    += governor_npu_pm_qos.o

ccflags-$(CONFIG_DEVFREQ_GOV_NPU_PM_QOS) += -I$(srctree)/drivers/devfreq
