#
# Makefile for kernel SPMI framework.
#
obj-$(CONFIG_SPMI_PLATFORM)	+= spmi_core.o

obj-$(CONFIG_SPMI_PLATFORM)	+= spmi_controller.o

obj-$(CONFIG_SPMI_PLATFORM)	+= of_spmi.o

obj-$(CONFIG_SPMI_PLATFORM_DEBUG_FS)	+= spmi_dbgfs.o
