#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/driver_ic/mp3336
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/driver_ic
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_KERNEL_CAMERA_DRIVER_IC_MP3336) += mp3336.o
