ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/cci
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/csi
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/io
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/pmic
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform


obj-y += sensor_common.o
obj-y += sensor/
