ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2

PM_DIR :=$(srctree)/platform_source/cee/drivers/pm/new

EXTRA_CFLAGS += -I$(PM_DIR)

obj-y += ap_wake.o
obj-y += gpio_wake.o
obj-y += ipc_wake.o
