# SPDX-License-Identifier: GPL-2.0-only
ccflags-y +=  -I$(srctree)/drivers/gpio

obj-$(CONFIG_GPIO_HI6502)		+= gpio_hi6502.o
obj-$(CONFIG_GPIO_HIV500)		+= gpio_hiv500.o
obj-$(CONFIG_GPIO_PL061_VM)		+= gpio_pl061_vm.o
obj-$(CONFIG_GPIOLIB)			+= gpio_debug.o