#ifndef __ASP_REGISTER_H__
#define __ASP_REGISTER_H__ 
#include "soc_acpu_baseaddr_interface.h"
#define HI_SOUNDWIRE_DP1_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x0)
#define HI_SOUNDWIRE_DP2_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x100)
#define HI_SOUNDWIRE_DP3_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x200)
#define HI_SOUNDWIRE_DP4_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x300)
#define HI_SOUNDWIRE_DP5_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x400)
#define HI_SOUNDWIRE_DP6_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x500)
#define HI_SOUNDWIRE_DP7_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x600)
#define HI_SOUNDWIRE_DP8_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x700)
#define HI_SOUNDWIRE_DP9_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x800)
#define HI_SOUNDWIRE_DP10_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x900)
#define HI_SOUNDWIRE_DP11_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xB00)
#define HI_SOUNDWIRE_DP12_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xC00)
#define HI_SOUNDWIRE_DP13_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xD00)
#define HI_SOUNDWIRE_DP14_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xE00)
#endif
