#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/dot/cyc8
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/dot
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_KERNEL_CAMERA_DOT_PROJECTOR_CYC8) += cyc8.o

