ccflags-y += -I$(srctree)/platform_source/smart/drivers/
ccflags-y += -I$(srctree)/platform_source/smart/drivers/channels/
ccflags-y += -I$(srctree)/platform_source/smart/drivers/channels/inputhub_as/

ccflags-y += -I$(srctree)/platform_source/smart/drivers/inputhub_as/fingerprint/

ccflags-y += -I$(srctree)/include/linux/platform_drivers/contexthub/
ccflags-y += -I$(srctree)/include/linux/platform_drivers/contexthub/inputhub_as/


obj-$(CONFIG_FINGERPRINT_CHANNEL) += fingerprint_channel.o
obj-$(CONFIG_FINGERPRINT_CHANNEL) += common_func.o
