##############################################################
#                      vfmw support config                   #
##############################################################

set(VT_SUPPORT n)
set(IPT_SUPPORT n)
set(VFMW_MMU_SUPPORT y)
set(VDH_BSP_NUM_IN_USE 2)
set(STM_DEV_NUM 2)
set(MAX_OPEN_COUNT 32)
set(SCD_UMSG_STEP 3)
set(SCD_UMSG_NUM 2048)
set(SCD_DMSG_NUM 1024)

set(VFMW_OLD_MIN_PIX_WIDTH 64)
set(VFMW_OLD_MIN_PIX_HEIGHT 64)
set(VFMW_OLD_MAX_PIX_WIDTH 1920)
set(VFMW_OLD_MAX_PIX_HEIGHT 1088)

set(VFMW_H264_SUPPORT y)
set(VFMW_H264_MIN_PIX_WIDTH 64)
set(VFMW_H264_MIN_PIX_HEIGHT 64)
set(VFMW_H264_MAX_PIX_WIDTH 8192)
set(VFMW_H264_MAX_PIX_HEIGHT 4352)
set(VFMW_H264_MAX_SLICE_NUM 136)
set(VFMW_H264_SLC_LDY_SUPPORT n)

set(VFMW_HEVC_SUPPORT y)
set(VFMW_HEVC_MIN_PIX_WIDTH 128)
set(VFMW_HEVC_MIN_PIX_HEIGHT 128)
set(VFMW_HEVC_MAX_PIX_WIDTH 8192)
set(VFMW_HEVC_MAX_PIX_HEIGHT 4352)
set(VFMW_HEVC_MAX_BIT_DEPTH 10)
set(VFMW_HEVC_MAX_SLICE_NUM 200)
set(VFMW_HEVC_SLC_LDY_SUPPORT n)

set(VFMW_VP9_SUPPORT y)
set(VFMW_VP9_MIN_PIX_WIDTH 64)
set(VFMW_VP9_MIN_PIX_HEIGHT 64)
set(VFMW_VP9_MAX_PIX_WIDTH 4096)
set(VFMW_VP9_MAX_PIX_HEIGHT 2304)

set(VFMW_AVS2_SUPPORT n)
set(VFMW_AVS2_MIN_PIX_WIDTH 64)
set(VFMW_AVS2_MIN_PIX_HEIGHT 64)
set(VFMW_AVS2_MAX_PIX_WIDTH 4096)
set(VFMW_AVS2_MAX_PIX_HEIGHT 2304)

set(VFMW_AVS3_SUPPORT n)
set(VFMW_AVS3_MIN_PIX_WIDTH 128)
set(VFMW_AVS3_MIN_PIX_HEIGHT 128)
set(VFMW_AVS3_MAX_PIX_WIDTH 8192)
set(VFMW_AVS3_MAX_PIX_HEIGHT 4352)

set(VFMW_AV1_SUPPORT n)
set(VFMW_AV1_MIN_PIX_WIDTH 64)
set(VFMW_AV1_MIN_PIX_HEIGHT 64)
set(VFMW_AV1_MAX_PIX_WIDTH 4096)
set(VFMW_AV1_MAX_PIX_HEIGHT 2304)

set(VFMW_MVC_SUPPORT n)

set(VFMW_MPEG2_SUPPORT n)
set(MPEG2_SLCHDR_HW n)

set(VFMW_MPEG4_SUPPORT n)

set(VFMW_AVS_SUPPORT n)
set(VFMW_AVSPLUS_SUPPORT n)

set(VFMW_VC1_SUPPORT n)

set(VFMW_REAL8_SUPPORT n)

set(VFMW_REAL9_SUPPORT n)

set(VFMW_VP6_SUPPORT n)

set(VFMW_VP8_SUPPORT n)

set(VFMW_DIVX3_SUPPORT n)

set(VFMW_H263_SUPPORT n)

set(VFMW_SORENSON_SUPPORT n)

set(VFMW_JPEG_SUPPORT n)

set(VFMW_RAW_SUPPORT n)

set(VFMW_MJPEG_SUPPORT n)

set(VFMW_WMV1_SUPPORT n)

set(VFMW_WMV2_SUPPORT n)

set(VFMW_WMV3_SUPPORT n)

set(VFMW_SCD_SUPPORT y)

set(VFMW_VDH_SUPPORT y)

set(VFMW_BPD_SUPPORT n)

set(VFMW_VMM_SUPPORT n)

set(VFMW_STREAM_SUPPORT y)

set(VFMW_VPP_SUPPORT n)
if ("${VT_SUPPORT}" STREQUAL "y")
    set(VFMW_VPP_SUPPORT n)
endif()

set(VFMW_FENCE_SUPPORT n)
if ("${VT_SUPPORT}" STREQUAL "y")
    set(VFMW_FENCE_SUPPORT n)
endif()

if ("${VFMW_VMM_SUPPORT}" STREQUAL "n")
    set(VFMW_MJPEG_SUPPORT n)
endif()

set(VFMW_HDR_SUPPORT n)
if ("${VFMW_HDR_SUPPORT}" STREQUAL "y")
    set(VFMW_AVS2_SLHDR_SUPPORT y)
    set(VFMW_DOLBY_VISION_HDR_SUPPORT y)
    set(VFMW_HIGH_PROFILE_MAX_BITSTREAM_SIZE 65536)
    set(VFMW_MAIN_PROFILE_MAX_BITSTREAM_SIZE 16384)
    set(VFMW_BASE_PROFILE_MAX_BITSTREAM_SIZE 4096)
endif()

set(VFMW_CHAN_SUPPORT y)
if ("${VFMW_CHAN_SUPPORT}" STREQUAL "y")
    set(VFMW_MAX_CHAN_NUM 1)
endif

set(VFMW_RAW_NUM_SUPPORT n)
if ("${VFMW_RAW_NUM_SUPPORT}" STREQUAL "y")
    set(VFMW_MAX_RAW_NUM 256)
endif

set(VFMW_SEG_NUM_SUPPORT n)
if ("${VFMW_SEG_NUM_SUPPORT}" STREQUAL "y")
    set(VFMW_MAX_SEG_NUM 256)
endif

set(VFMW_SEC_TAG_NUM 0)

set(VFMW_MODULE_LOWDLY_SUPPORT n)

set(VFMW_SYSTEM_REG_DISABLE y)

set(VFMW_DPRINT_SUPPORT y)

set(VFMW_SYSTEM_TIME_OUT y)

set(VFMW_PROC_SUPPORT n)

#default 2000
set(VFMW_SCD_TIME_OUT 800)
set(VFMW_SCD_FPGA_TIME_OUT 5000)
#default 5000
set(VFMW_VDH_TIME_OUT 800)
set(VFMW_VDH_FPGA_TIME_OUT 200000)

# per-one-frm time(us)
set(VFMW_VDH_ONE_FRM_PERF 20000)
set(VFMW_VDH_FPGA_ONE_FRM_PERF 200000)

set(VFMW_MAX_DPS_NUM 1)

set(VFMW_DDR_SCRAMBLE_ENABLE 0)
set(VFMW_DDR_SCRAMBLE_MODE g_ddr_scramble_mode)
