ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2
obj-$(CONFIG_DEVFREQ_GOV_GPU_SCENE_AWARE)    += governor_gpu_scene_aware.o

ccflags-$(CONFIG_DEVFREQ_GOV_GPU_SCENE_AWARE) += -I$(srctree)/drivers/devfreq
