obj-$(CONFIG_DRV_IP_REGULATOR) += ip_regulator.o
obj-$(CONFIG_FREQ_AUTODOWN)+= ip_regulator_autofs/

EXTRA_CFLAGS += -I$(srctree)/drivers/regulator/
obj-$(CONFIG_REGULATOR_PLATFORM) += regulator_regmap.o
obj-$(CONFIG_REGULATOR_SMARTPA) += regulator_smartpa.o
obj-$(CONFIG_REGULATOR_SUB_PMU_SPMI) += regulator_sub_pmu_spmi.o
obj-$(CONFIG_DRV_REGULATOR_DEBUG) += regulator_debug.o
