ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/hisp
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

EXTRA_CFLAGS += -DHISP150_CAMERA
obj-y += hisp150.o
