# If you want to compile into modular drive, will need to decide
# according to the following configuration to compile.
# If the CONFIG_DKMD_ENABLE is not defined, display module isn't compiled.

ifeq ($(CONFIG_DKMD_ENABLE),y)

obj-y += dksm/
obj-y += backlight/
obj-y += cmdlist/
obj-y += dpu/begonia/
obj-y += connector/
obj-y += product/

endif
