#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/driver_ic/lm3644
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/driver_ic
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -fno-pic

obj-y += lm3644.o
