ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/csi
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
obj-$(CONFIG_KERNEL_CAMERA_USE_CAMKIT) += hisensor.o
