// ******************************************************************************
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  ar_feature_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Date          :  2013/3/10
// Description   :
// Others        :  Generated automatically by nManager V4.2
// ******************************************************************************

#ifndef __AR_FEATURE_REG_OFFSET_FIELD_H__
#define __AR_FEATURE_REG_OFFSET_FIELD_H__

#define AR_FEATURE_FIRST_DETECT_LEN    1
#define AR_FEATURE_FIRST_DETECT_OFFSET 7
#define AR_FEATURE_ITER_NUM_LEN        1
#define AR_FEATURE_ITER_NUM_OFFSET     6
#define AR_FEATURE_LAYER_LEN           2
#define AR_FEATURE_LAYER_OFFSET        4
#define AR_FEATURE_ORIENT_EN_LEN       1
#define AR_FEATURE_ORIENT_EN_OFFSET    3
#define AR_FEATURE_MODE_LEN            3
#define AR_FEATURE_MODE_OFFSET         0

#define AR_FEATURE_HEIGHT_LEN    11
#define AR_FEATURE_HEIGHT_OFFSET 16
#define AR_FEATURE_WIDTH_LEN     11
#define AR_FEATURE_WIDTH_OFFSET  0

#define AR_FEATURE_BLK_H_NUM_LEN    5
#define AR_FEATURE_BLK_H_NUM_OFFSET 8
#define AR_FEATURE_BLK_V_NUM_LEN    5
#define AR_FEATURE_BLK_V_NUM_OFFSET 0

#define AR_FEATURE_BLK_H_SIZE_INV_LEN    16
#define AR_FEATURE_BLK_H_SIZE_INV_OFFSET 16
#define AR_FEATURE_BLK_V_SIZE_INV_LEN    16
#define AR_FEATURE_BLK_V_SIZE_INV_OFFSET 0

#define AR_FEATURE_CUR_KPNUM_LEN    15
#define AR_FEATURE_CUR_KPNUM_OFFSET 16
#define AR_FEATURE_MAX_KPNUM_LEN    15
#define AR_FEATURE_MAX_KPNUM_OFFSET 0

#define AR_FEATURE_SIGMA_ORI_LEN    10
#define AR_FEATURE_SIGMA_ORI_OFFSET 16
#define AR_FEATURE_SIGMA_DES_LEN    10
#define AR_FEATURE_SIGMA_DES_OFFSET 0

#define AR_FEATURE_GAUSS_ORG_3_LEN    8
#define AR_FEATURE_GAUSS_ORG_3_OFFSET 24
#define AR_FEATURE_GAUSS_ORG_2_LEN    8
#define AR_FEATURE_GAUSS_ORG_2_OFFSET 16
#define AR_FEATURE_GAUSS_ORG_1_LEN    8
#define AR_FEATURE_GAUSS_ORG_1_OFFSET 8
#define AR_FEATURE_GAUSS_ORG_0_LEN    8
#define AR_FEATURE_GAUSS_ORG_0_OFFSET 0

#define AR_FEATURE_GAUSS_1ST_2_LEN    8
#define AR_FEATURE_GAUSS_1ST_2_OFFSET 16
#define AR_FEATURE_GAUSS_1ST_1_LEN    8
#define AR_FEATURE_GAUSS_1ST_1_OFFSET 8
#define AR_FEATURE_GAUSS_1ST_0_LEN    8
#define AR_FEATURE_GAUSS_1ST_0_OFFSET 0

#define AR_FEATURE_GAUSS_2ND_3_LEN    8
#define AR_FEATURE_GAUSS_2ND_3_OFFSET 24
#define AR_FEATURE_GAUSS_2ND_2_LEN    8
#define AR_FEATURE_GAUSS_2ND_2_OFFSET 16
#define AR_FEATURE_GAUSS_2ND_1_LEN    8
#define AR_FEATURE_GAUSS_2ND_1_OFFSET 8
#define AR_FEATURE_GAUSS_2ND_0_LEN    8
#define AR_FEATURE_GAUSS_2ND_0_OFFSET 0

#define AR_FEATURE_DOG_THRESHOLD_LEN     15
#define AR_FEATURE_DOG_THRESHOLD_OFFSET  16
#define AR_FEATURE_EDGE_THRESHOLD_LEN    16
#define AR_FEATURE_EDGE_THRESHOLD_OFFSET 0

#define AR_FEATURE_MAG_THRESHOLD_LEN    8
#define AR_FEATURE_MAG_THRESHOLD_OFFSET 0

#define AR_FEATURE_VPRD_LAST_PAGE_LEN          19
#define AR_FEATURE_VPRD_LAST_PAGE_OFFSET       13
#define AR_FEATURE_VPRD_ALLOCATED_DU_LEN       5
#define AR_FEATURE_VPRD_ALLOCATED_DU_OFFSET    6
#define AR_FEATURE_VPRD_PIXEL_EXPANSION_LEN    1
#define AR_FEATURE_VPRD_PIXEL_EXPANSION_OFFSET 5
#define AR_FEATURE_VPRD_PIXEL_FORMAT_LEN       5
#define AR_FEATURE_VPRD_PIXEL_FORMAT_OFFSET    0

#define AR_FEATURE_VPRD_HORIZONTAL_BLANKING_LEN    8
#define AR_FEATURE_VPRD_HORIZONTAL_BLANKING_OFFSET 16
#define AR_FEATURE_VPRD_LINE_SIZE_LEN              15
#define AR_FEATURE_VPRD_LINE_SIZE_OFFSET           0

#define AR_FEATURE_VPRD_VERTICAL_BLANKING_LEN    8
#define AR_FEATURE_VPRD_VERTICAL_BLANKING_OFFSET 16
#define AR_FEATURE_VPRD_FRAME_SIZE_LEN           15
#define AR_FEATURE_VPRD_FRAME_SIZE_OFFSET        0

#define AR_FEATURE_VPRD_AXI_FRAME_START_LEN    30
#define AR_FEATURE_VPRD_AXI_FRAME_START_OFFSET 2

#define AR_FEATURE_VPRD_LINE_WRAP_0_LEN      14
#define AR_FEATURE_VPRD_LINE_WRAP_0_OFFSET   18
#define AR_FEATURE_VPRD_LINE_STRIDE_0_LEN    14
#define AR_FEATURE_VPRD_LINE_STRIDE_0_OFFSET 0

#define AR_FEATURE_VPRD_PREFETCH_BYPASS_LEN                      1
#define AR_FEATURE_VPRD_PREFETCH_BYPASS_OFFSET                   31
#define AR_FEATURE_VP_RD_STOP_LEN                                1
#define AR_FEATURE_VP_RD_STOP_OFFSET                             25
#define AR_FEATURE_VP_RD_STOP_OK_LEN                             1
#define AR_FEATURE_VP_RD_STOP_OK_OFFSET                          24
#define AR_FEATURE_VP_RD_STOP_ENABLE_PRESSURE_LEN                1
#define AR_FEATURE_VP_RD_STOP_ENABLE_PRESSURE_OFFSET             18
#define AR_FEATURE_VP_RD_STOP_ENABLE_FLUX_CTRL_LEN               1
#define AR_FEATURE_VP_RD_STOP_ENABLE_FLUX_CTRL_OFFSET            17
#define AR_FEATURE_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_LEN    1
#define AR_FEATURE_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_OFFSET 16

#define AR_FEATURE_PRE_VPRD_VERTICAL_BLANKING_LEN    8
#define AR_FEATURE_PRE_VPRD_VERTICAL_BLANKING_OFFSET 16
#define AR_FEATURE_PRE_VPRD_FRAME_SIZE_LEN           15
#define AR_FEATURE_PRE_VPRD_FRAME_SIZE_OFFSET        0

#define AR_FEATURE_VPWR_LAST_PAGE_LEN          19
#define AR_FEATURE_VPWR_LAST_PAGE_OFFSET       13
#define AR_FEATURE_VPWR_PIXEL_EXPANSION_LEN    1
#define AR_FEATURE_VPWR_PIXEL_EXPANSION_OFFSET 5
#define AR_FEATURE_VPWR_PIXEL_FORMAT_LEN       5
#define AR_FEATURE_VPWR_PIXEL_FORMAT_OFFSET    0

#define AR_FEATURE_VPWR_ADDRESS_FRAME_START_LEN    30
#define AR_FEATURE_VPWR_ADDRESS_FRAME_START_OFFSET 2

#define AR_FEATURE_VPWR_LINE_WRAP_LEN           14
#define AR_FEATURE_VPWR_LINE_WRAP_OFFSET        18
#define AR_FEATURE_VPWR_LINE_START_WSTRB_LEN    4
#define AR_FEATURE_VPWR_LINE_START_WSTRB_OFFSET 14
#define AR_FEATURE_VPWR_LINE_STRIDE_LEN         14
#define AR_FEATURE_VPWR_LINE_STRIDE_OFFSET      0

#define AR_FEATURE_VPWR_PREFETCH_BYPASS_LEN                      1
#define AR_FEATURE_VPWR_PREFETCH_BYPASS_OFFSET                   31
#define AR_FEATURE_VP_WR_STOP_LEN                                1
#define AR_FEATURE_VP_WR_STOP_OFFSET                             25
#define AR_FEATURE_VP_WR_STOP_OK_LEN                             1
#define AR_FEATURE_VP_WR_STOP_OK_OFFSET                          24
#define AR_FEATURE_VP_WR_STOP_ENABLE_PRESSURE_LEN                1
#define AR_FEATURE_VP_WR_STOP_ENABLE_PRESSURE_OFFSET             18
#define AR_FEATURE_VP_WR_STOP_ENABLE_FLUX_CTRL_LEN               1
#define AR_FEATURE_VP_WR_STOP_ENABLE_FLUX_CTRL_OFFSET            17
#define AR_FEATURE_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_LEN    1
#define AR_FEATURE_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_OFFSET 16

#define AR_FEATURE_PRE_VPWR_ADDRESS_FRAME_START_LEN    30
#define AR_FEATURE_PRE_VPWR_ADDRESS_FRAME_START_OFFSET 2

#define AR_FEATURE_GRID_MAX_KPNUM_0_LEN        8
#define AR_FEATURE_GRID_MAX_KPNUM_0_OFFSET     16
#define AR_FEATURE_GRID_DOG_THRESHOLD_0_LEN    16
#define AR_FEATURE_GRID_DOG_THRESHOLD_0_OFFSET 0

#define AR_FEATURE_KPT_COUNT_0_LEN    12
#define AR_FEATURE_KPT_COUNT_0_OFFSET 16
#define AR_FEATURE_MIN_SCORE_0_LEN    16
#define AR_FEATURE_MIN_SCORE_0_OFFSET 0

#define AR_FEATURE_SUM_SCORE_0_LEN    28
#define AR_FEATURE_SUM_SCORE_0_OFFSET 0

#define AR_FEATURE_KPT_NUM_0_LEN    32
#define AR_FEATURE_KPT_NUM_0_OFFSET 0

#define AR_FEATURE_TOTAL_KPT_NUM_LEN    15
#define AR_FEATURE_TOTAL_KPT_NUM_OFFSET 0

#define AR_FEATURE_DEBUG0_LEN    32
#define AR_FEATURE_DEBUG0_OFFSET 0

#define AR_FEATURE_DEBUG1_LEN    32
#define AR_FEATURE_DEBUG1_OFFSET 0

#define AR_FEATURE_DEBUG2_LEN    32
#define AR_FEATURE_DEBUG2_OFFSET 0

#define AR_FEATURE_DEBUG3_LEN    32
#define AR_FEATURE_DEBUG3_OFFSET 0

#endif // __AR_FEATURE_REG_OFFSET_FIELD_H__
