// ******************************************************************************
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  cmdlst_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2020/04/02 14:01:20 Create file
// ******************************************************************************

#ifndef __CMDLST_REG_OFFSET_FIELD_H__
#define __CMDLST_REG_OFFSET_FIELD_H__

#define CMDLST_IP_ID_LEN    32
#define CMDLST_IP_ID_OFFSET 0

#define CMDLST_IP_VERSION_LEN    32
#define CMDLST_IP_VERSION_OFFSET 0

#define CMDLST_STORE_LOAD_LEN    32
#define CMDLST_STORE_LOAD_OFFSET 0

#define CMDLST_SLOWDOWN_NRT_CHANNEL_LEN    2
#define CMDLST_SLOWDOWN_NRT_CHANNEL_OFFSET 1

#define CMDLST_START_ADDR_LEN    32
#define CMDLST_START_ADDR_OFFSET 0

#define CMDLST_END_ADDR_LEN    32
#define CMDLST_END_ADDR_OFFSET 0

#define CMDLST_CHECK_ERROR_STATUS_LEN    32
#define CMDLST_CHECK_ERROR_STATUS_OFFSET 0

#define CMDLST_VCD_OUT_SELECT_LEN    3
#define CMDLST_VCD_OUT_SELECT_OFFSET 0

#define CMDLST_DBG_ARB_FSM_LEN          1
#define CMDLST_DBG_ARB_FSM_OFFSET       12
#define CMDLST_DBG_VP_WR_FSM_LEN        2
#define CMDLST_DBG_VP_WR_FSM_OFFSET     8
#define CMDLST_DBG_LB_MASTER_FSM_LEN    4
#define CMDLST_DBG_LB_MASTER_FSM_OFFSET 4
#define CMDLST_DBG_FIFO_NB_ELEM_LEN     3
#define CMDLST_DBG_FIFO_NB_ELEM_OFFSET  0

#define CMDLST_LAST_CMD_EXEC_LEN    32
#define CMDLST_LAST_CMD_EXEC_OFFSET 0

#define CMDLST_DBG_HW_START_LEN    16
#define CMDLST_DBG_HW_START_OFFSET 16
#define CMDLST_DBG_SW_START_LEN    16
#define CMDLST_DBG_SW_START_OFFSET 0

#define CMDLST_DBG_HW_START_LEN    16
#define CMDLST_DBG_HW_START_OFFSET 16
#define CMDLST_DBG_SW_START_LEN    16
#define CMDLST_DBG_SW_START_OFFSET 0

#define CMDLST_DBG_FSM_CH_7_0_LEN    4
#define CMDLST_DBG_FSM_CH_7_0_OFFSET 28
#define CMDLST_DBG_FSM_CH_6_0_LEN    4
#define CMDLST_DBG_FSM_CH_6_0_OFFSET 24
#define CMDLST_DBG_FSM_CH_5_0_LEN    4
#define CMDLST_DBG_FSM_CH_5_0_OFFSET 20
#define CMDLST_DBG_FSM_CH_4_0_LEN    4
#define CMDLST_DBG_FSM_CH_4_0_OFFSET 16
#define CMDLST_DBG_FSM_CH_3_0_LEN    4
#define CMDLST_DBG_FSM_CH_3_0_OFFSET 12
#define CMDLST_DBG_FSM_CH_2_0_LEN    4
#define CMDLST_DBG_FSM_CH_2_0_OFFSET 8
#define CMDLST_DBG_FSM_CH_1_0_LEN    4
#define CMDLST_DBG_FSM_CH_1_0_OFFSET 4
#define CMDLST_DBG_FSM_CH_0_0_LEN    4
#define CMDLST_DBG_FSM_CH_0_0_OFFSET 0

#define CMDLST_DBG_FSM_CH_7_1_LEN    4
#define CMDLST_DBG_FSM_CH_7_1_OFFSET 28
#define CMDLST_DBG_FSM_CH_6_1_LEN    4
#define CMDLST_DBG_FSM_CH_6_1_OFFSET 24
#define CMDLST_DBG_FSM_CH_5_1_LEN    4
#define CMDLST_DBG_FSM_CH_5_1_OFFSET 20
#define CMDLST_DBG_FSM_CH_4_1_LEN    4
#define CMDLST_DBG_FSM_CH_4_1_OFFSET 16
#define CMDLST_DBG_FSM_CH_3_1_LEN    4
#define CMDLST_DBG_FSM_CH_3_1_OFFSET 12
#define CMDLST_DBG_FSM_CH_2_1_LEN    4
#define CMDLST_DBG_FSM_CH_2_1_OFFSET 8
#define CMDLST_DBG_FSM_CH_1_1_LEN    4
#define CMDLST_DBG_FSM_CH_1_1_OFFSET 4
#define CMDLST_DBG_FSM_CH_0_1_LEN    4
#define CMDLST_DBG_FSM_CH_0_1_OFFSET 0

#define CMDLST_DBG_FSM_CH_7_2_LEN    4
#define CMDLST_DBG_FSM_CH_7_2_OFFSET 28
#define CMDLST_DBG_FSM_CH_6_2_LEN    4
#define CMDLST_DBG_FSM_CH_6_2_OFFSET 24
#define CMDLST_DBG_FSM_CH_5_2_LEN    4
#define CMDLST_DBG_FSM_CH_5_2_OFFSET 20
#define CMDLST_DBG_FSM_CH_4_2_LEN    4
#define CMDLST_DBG_FSM_CH_4_2_OFFSET 16
#define CMDLST_DBG_FSM_CH_3_2_LEN    4
#define CMDLST_DBG_FSM_CH_3_2_OFFSET 12
#define CMDLST_DBG_FSM_CH_2_2_LEN    4
#define CMDLST_DBG_FSM_CH_2_2_OFFSET 8
#define CMDLST_DBG_FSM_CH_1_2_LEN    4
#define CMDLST_DBG_FSM_CH_1_2_OFFSET 4
#define CMDLST_DBG_FSM_CH_0_2_LEN    4
#define CMDLST_DBG_FSM_CH_0_2_OFFSET 0

#define CMDLST_DBG_FSM_CH_7_3_LEN    4
#define CMDLST_DBG_FSM_CH_7_3_OFFSET 28
#define CMDLST_DBG_FSM_CH_6_3_LEN    4
#define CMDLST_DBG_FSM_CH_6_3_OFFSET 24
#define CMDLST_DBG_FSM_CH_5_3_LEN    4
#define CMDLST_DBG_FSM_CH_5_3_OFFSET 20
#define CMDLST_DBG_FSM_CH_4_3_LEN    4
#define CMDLST_DBG_FSM_CH_4_3_OFFSET 16
#define CMDLST_DBG_FSM_CH_3_3_LEN    4
#define CMDLST_DBG_FSM_CH_3_3_OFFSET 12
#define CMDLST_DBG_FSM_CH_2_3_LEN    4
#define CMDLST_DBG_FSM_CH_2_3_OFFSET 8
#define CMDLST_DBG_FSM_CH_1_3_LEN    4
#define CMDLST_DBG_FSM_CH_1_3_OFFSET 4
#define CMDLST_DBG_FSM_CH_0_3_LEN    4
#define CMDLST_DBG_FSM_CH_0_3_OFFSET 0

#define CMDLST_NRT_CHANNEL_0_LEN                1
#define CMDLST_NRT_CHANNEL_0_OFFSET             8
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_0_LEN    1
#define CMDLST_ACTIVE_TOKEN_NBR_ENABLE_0_OFFSET 7
#define CMDLST_ACTIVE_TOKEN_NBR_0_LEN           7
#define CMDLST_ACTIVE_TOKEN_NBR_0_OFFSET        0

#define CMDLST_CHECK_ERROR_PTR_0_LEN    32
#define CMDLST_CHECK_ERROR_PTR_0_OFFSET 0

#define CMDLST_CHECK_ERROR_TASK_0_LEN    8
#define CMDLST_CHECK_ERROR_TASK_0_OFFSET 0

#define CMDLST_CHECK_ERROR_CMD_0_LEN    32
#define CMDLST_CHECK_ERROR_CMD_0_OFFSET 0

#define CMDLST_BRANCHING_0_LEN    1
#define CMDLST_BRANCHING_0_OFFSET 0

#define CMDLST_LAST_EXEC_PTR_0_LEN    32
#define CMDLST_LAST_EXEC_PTR_0_OFFSET 0

#define CMDLST_LAST_EXEC_TASK_0_LEN    8
#define CMDLST_LAST_EXEC_TASK_0_OFFSET 0

#define CMDLST_SW_PRIORITY_0_LEN    1
#define CMDLST_SW_PRIORITY_0_OFFSET 31
#define CMDLST_SW_RESOURCE_0_LEN    23
#define CMDLST_SW_RESOURCE_0_OFFSET 8
#define CMDLST_SW_TASK_0_LEN        8
#define CMDLST_SW_TASK_0_OFFSET     0

#define CMDLST_RESERVED_SW_2_0_LEN         6
#define CMDLST_RESERVED_SW_2_0_OFFSET      26
#define CMDLST_SW_CVDR_RD_SIZE_0_LEN       2
#define CMDLST_SW_CVDR_RD_SIZE_0_OFFSET    24
#define CMDLST_RESERVED_SW_1_0_LEN         2
#define CMDLST_RESERVED_SW_1_0_OFFSET      22
#define CMDLST_SW_CVDR_RD_ADDRESS_0_LEN    20
#define CMDLST_SW_CVDR_RD_ADDRESS_0_OFFSET 2
#define CMDLST_RESERVED_SW_0_0_LEN         2
#define CMDLST_RESERVED_SW_0_0_OFFSET      0

#define CMDLST_SW_VPRD_LAST_PAGE_0_LEN          19
#define CMDLST_SW_VPRD_LAST_PAGE_0_OFFSET       13
#define CMDLST_SW_RESERVED_0_0_LEN              1
#define CMDLST_SW_RESERVED_0_0_OFFSET           12
#define CMDLST_SW_VPRD_MONO_MODE_0_LEN          1
#define CMDLST_SW_VPRD_MONO_MODE_0_OFFSET       11
#define CMDLST_SW_VPRD_ALLOCATED_DU_0_LEN       5
#define CMDLST_SW_VPRD_ALLOCATED_DU_0_OFFSET    6
#define CMDLST_SW_VPRD_PIXEL_EXPANSION_0_LEN    1
#define CMDLST_SW_VPRD_PIXEL_EXPANSION_0_OFFSET 5
#define CMDLST_SW_VPRD_PIXEL_FORMAT_0_LEN       5
#define CMDLST_SW_VPRD_PIXEL_FORMAT_0_OFFSET    0

#define CMDLST_SW_RESERVED_1_0_LEN                  8
#define CMDLST_SW_RESERVED_1_0_OFFSET               24
#define CMDLST_SW_VPRD_HORIZONTAL_BLANKING_0_LEN    8
#define CMDLST_SW_VPRD_HORIZONTAL_BLANKING_0_OFFSET 16
#define CMDLST_SW_RESERVED_2_0_LEN                  1
#define CMDLST_SW_RESERVED_2_0_OFFSET               15
#define CMDLST_SW_VPRD_LINE_SIZE_0_LEN              15
#define CMDLST_SW_VPRD_LINE_SIZE_0_OFFSET           0

#define CMDLST_SW_RESERVED_3_0_LEN                8
#define CMDLST_SW_RESERVED_3_0_OFFSET             24
#define CMDLST_SW_VPRD_VERTICAL_BLANKING_0_LEN    8
#define CMDLST_SW_VPRD_VERTICAL_BLANKING_0_OFFSET 16
#define CMDLST_SW_RESERVED_4_0_LEN                1
#define CMDLST_SW_RESERVED_4_0_OFFSET             15
#define CMDLST_SW_VPRD_FRAME_SIZE_0_LEN           15
#define CMDLST_SW_VPRD_FRAME_SIZE_0_OFFSET        0

#define CMDLST_SW_VPRD_AXI_FRAME_START_0_LEN    30
#define CMDLST_SW_VPRD_AXI_FRAME_START_0_OFFSET 2
#define CMDLST_SW_RESERVED_5_0_LEN              2
#define CMDLST_SW_RESERVED_5_0_OFFSET           0

#define CMDLST_HW_PRIORITY_0_LEN    1
#define CMDLST_HW_PRIORITY_0_OFFSET 31
#define CMDLST_HW_RESOURCE_0_LEN    23
#define CMDLST_HW_RESOURCE_0_OFFSET 8
#define CMDLST_HW_TASK_0_LEN        8
#define CMDLST_HW_TASK_0_OFFSET     0

#define CMDLST_RESERVED_HW_2_0_LEN         6
#define CMDLST_RESERVED_HW_2_0_OFFSET      26
#define CMDLST_HW_CVDR_RD_SIZE_0_LEN       2
#define CMDLST_HW_CVDR_RD_SIZE_0_OFFSET    24
#define CMDLST_RESERVED_HW_1_0_LEN         2
#define CMDLST_RESERVED_HW_1_0_OFFSET      22
#define CMDLST_HW_CVDR_RD_ADDRESS_0_LEN    20
#define CMDLST_HW_CVDR_RD_ADDRESS_0_OFFSET 2
#define CMDLST_RESERVED_HW_0_0_LEN         2
#define CMDLST_RESERVED_HW_0_0_OFFSET      0

#define CMDLST_HW_VPRD_LAST_PAGE_0_LEN          19
#define CMDLST_HW_VPRD_LAST_PAGE_0_OFFSET       13
#define CMDLST_HW_RESERVED_0_0_LEN              1
#define CMDLST_HW_RESERVED_0_0_OFFSET           12
#define CMDLST_HW_VPRD_MONO_MODE_0_LEN          1
#define CMDLST_HW_VPRD_MONO_MODE_0_OFFSET       11
#define CMDLST_HW_VPRD_ALLOCATED_DU_0_LEN       5
#define CMDLST_HW_VPRD_ALLOCATED_DU_0_OFFSET    6
#define CMDLST_HW_VPRD_PIXEL_EXPANSION_0_LEN    1
#define CMDLST_HW_VPRD_PIXEL_EXPANSION_0_OFFSET 5
#define CMDLST_HW_VPRD_PIXEL_FORMAT_0_LEN       5
#define CMDLST_HW_VPRD_PIXEL_FORMAT_0_OFFSET    0

#define CMDLST_HW_RESERVED_1_0_LEN                  8
#define CMDLST_HW_RESERVED_1_0_OFFSET               24
#define CMDLST_HW_VPRD_HORIZONTAL_BLANKING_0_LEN    8
#define CMDLST_HW_VPRD_HORIZONTAL_BLANKING_0_OFFSET 16
#define CMDLST_HW_RESERVED_2_0_LEN                  1
#define CMDLST_HW_RESERVED_2_0_OFFSET               15
#define CMDLST_HW_VPRD_LINE_SIZE_0_LEN              15
#define CMDLST_HW_VPRD_LINE_SIZE_0_OFFSET           0

#define CMDLST_HW_RESERVED_3_0_LEN                8
#define CMDLST_HW_RESERVED_3_0_OFFSET             24
#define CMDLST_HW_VPRD_VERTICAL_BLANKING_0_LEN    8
#define CMDLST_HW_VPRD_VERTICAL_BLANKING_0_OFFSET 16
#define CMDLST_HW_RESERVED_4_0_LEN                1
#define CMDLST_HW_RESERVED_4_0_OFFSET             15
#define CMDLST_HW_VPRD_FRAME_SIZE_0_LEN           15
#define CMDLST_HW_VPRD_FRAME_SIZE_0_OFFSET        0

#define CMDLST_HW_VPRD_AXI_FRAME_START_0_LEN    30
#define CMDLST_HW_VPRD_AXI_FRAME_START_0_OFFSET 2
#define CMDLST_HW_RESERVED_5_0_LEN              2
#define CMDLST_HW_RESERVED_5_0_OFFSET           0

#define CMDLST_WAIT_EOP_0_LEN    1
#define CMDLST_WAIT_EOP_0_OFFSET 0

#define CMDLST_LINK_TOKEN_NBR_0_LEN    4
#define CMDLST_LINK_TOKEN_NBR_0_OFFSET 16
#define CMDLST_LINK_CHANNEL_0_LEN      5
#define CMDLST_LINK_CHANNEL_0_OFFSET   8
#define CMDLST_TOKEN_MODE_0_LEN        1
#define CMDLST_TOKEN_MODE_0_OFFSET     0

#define CMDLST_LINE_OVL_NBR_0_LEN    7
#define CMDLST_LINE_OVL_NBR_0_OFFSET 24
#define CMDLST_LINE_NBR_0_LEN        12
#define CMDLST_LINE_NBR_0_OFFSET     0

#define CMDLST_CHECK_ENABLE_0_LEN    1
#define CMDLST_CHECK_ENABLE_0_OFFSET 0

#define CMDLST_VP_WR_FLUSH_0_LEN    1
#define CMDLST_VP_WR_FLUSH_0_OFFSET 0

#define CMDLST_EOS_DBG_0_LEN    32
#define CMDLST_EOS_DBG_0_OFFSET 0

#define CMDLST_DBG_HW_START_0_LEN    1
#define CMDLST_DBG_HW_START_0_OFFSET 8
#define CMDLST_DBG_SW_START_0_LEN    1
#define CMDLST_DBG_SW_START_0_OFFSET 4
#define CMDLST_DBG_FSM_CH_0_LEN      4
#define CMDLST_DBG_FSM_CH_0_OFFSET   0


#endif // __CMDLST_REG_OFFSET_FIELD_H__
