// ******************************************************************************
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  cvdr_ipp_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2020/04/17 10:53:42 Create file
// ******************************************************************************

#ifndef __CVDR_IPP_REG_OFFSET_FIELD_H__
#define __CVDR_IPP_REG_OFFSET_FIELD_H__

#define CVDR_IPP_MAX_AXIWRITE_ID_LEN           6
#define CVDR_IPP_MAX_AXIWRITE_ID_OFFSET        24
#define CVDR_IPP_AXI_WR_BUFFER_BEHAVIOR_LEN    2
#define CVDR_IPP_AXI_WR_BUFFER_BEHAVIOR_OFFSET 22
#define CVDR_IPP_MAX_AXIREAD_ID_LEN            6
#define CVDR_IPP_MAX_AXIREAD_ID_OFFSET         16
#define CVDR_IPP_DU_THRESHOLD_REACHED_LEN      8
#define CVDR_IPP_DU_THRESHOLD_REACHED_OFFSET   8
#define CVDR_IPP_AXIWRITE_DU_THRESHOLD_LEN     6
#define CVDR_IPP_AXIWRITE_DU_THRESHOLD_OFFSET  0

#define CVDR_IPP_WR_QOS_SR_LEN                    2
#define CVDR_IPP_WR_QOS_SR_OFFSET                 30
#define CVDR_IPP_WR_QOS_MAX_LEN                   2
#define CVDR_IPP_WR_QOS_MAX_OFFSET                28
#define CVDR_IPP_WR_QOS_MIN_LEN                   2
#define CVDR_IPP_WR_QOS_MIN_OFFSET                26
#define CVDR_IPP_WR_QOS_THRESHOLD_11_START_LEN    4
#define CVDR_IPP_WR_QOS_THRESHOLD_11_START_OFFSET 20
#define CVDR_IPP_WR_QOS_THRESHOLD_11_STOP_LEN     4
#define CVDR_IPP_WR_QOS_THRESHOLD_11_STOP_OFFSET  16
#define CVDR_IPP_WR_QOS_THRESHOLD_10_START_LEN    4
#define CVDR_IPP_WR_QOS_THRESHOLD_10_START_OFFSET 12
#define CVDR_IPP_WR_QOS_THRESHOLD_10_STOP_LEN     4
#define CVDR_IPP_WR_QOS_THRESHOLD_10_STOP_OFFSET  8
#define CVDR_IPP_WR_QOS_THRESHOLD_01_START_LEN    4
#define CVDR_IPP_WR_QOS_THRESHOLD_01_START_OFFSET 4
#define CVDR_IPP_WR_QOS_THRESHOLD_01_STOP_LEN     4
#define CVDR_IPP_WR_QOS_THRESHOLD_01_STOP_OFFSET  0

#define CVDR_IPP_RD_QOS_SR_LEN                    2
#define CVDR_IPP_RD_QOS_SR_OFFSET                 30
#define CVDR_IPP_RD_QOS_MAX_LEN                   2
#define CVDR_IPP_RD_QOS_MAX_OFFSET                28
#define CVDR_IPP_RD_QOS_MIN_LEN                   2
#define CVDR_IPP_RD_QOS_MIN_OFFSET                26
#define CVDR_IPP_RD_QOS_THRESHOLD_11_START_LEN    4
#define CVDR_IPP_RD_QOS_THRESHOLD_11_START_OFFSET 20
#define CVDR_IPP_RD_QOS_THRESHOLD_11_STOP_LEN     4
#define CVDR_IPP_RD_QOS_THRESHOLD_11_STOP_OFFSET  16
#define CVDR_IPP_RD_QOS_THRESHOLD_10_START_LEN    4
#define CVDR_IPP_RD_QOS_THRESHOLD_10_START_OFFSET 12
#define CVDR_IPP_RD_QOS_THRESHOLD_10_STOP_LEN     4
#define CVDR_IPP_RD_QOS_THRESHOLD_10_STOP_OFFSET  8
#define CVDR_IPP_RD_QOS_THRESHOLD_01_START_LEN    4
#define CVDR_IPP_RD_QOS_THRESHOLD_01_START_OFFSET 4
#define CVDR_IPP_RD_QOS_THRESHOLD_01_STOP_LEN     4
#define CVDR_IPP_RD_QOS_THRESHOLD_01_STOP_OFFSET  0

#define CVDR_IPP_FORCE_CFG_CLK_ON_LEN       1
#define CVDR_IPP_FORCE_CFG_CLK_ON_OFFSET    8
#define CVDR_IPP_FORCE_DU_WR_CLK_ON_LEN     1
#define CVDR_IPP_FORCE_DU_WR_CLK_ON_OFFSET  7
#define CVDR_IPP_FORCE_DU_RD_CLK_ON_LEN     1
#define CVDR_IPP_FORCE_DU_RD_CLK_ON_OFFSET  6
#define CVDR_IPP_FORCE_AXI_WR_CLK_ON_LEN    1
#define CVDR_IPP_FORCE_AXI_WR_CLK_ON_OFFSET 5
#define CVDR_IPP_FORCE_AXI_RD_CLK_ON_LEN    1
#define CVDR_IPP_FORCE_AXI_RD_CLK_ON_OFFSET 4
#define CVDR_IPP_FORCE_NRWR_CLK_ON_LEN      1
#define CVDR_IPP_FORCE_NRWR_CLK_ON_OFFSET   3
#define CVDR_IPP_FORCE_NRRD_CLK_ON_LEN      1
#define CVDR_IPP_FORCE_NRRD_CLK_ON_OFFSET   2
#define CVDR_IPP_FORCE_VPWR_CLK_ON_LEN      1
#define CVDR_IPP_FORCE_VPWR_CLK_ON_OFFSET   1
#define CVDR_IPP_FORCE_VPRD_CLK_ON_LEN      1
#define CVDR_IPP_FORCE_VPRD_CLK_ON_OFFSET   0

#define CVDR_IPP_RD_PEAK_EN_LEN    1
#define CVDR_IPP_RD_PEAK_EN_OFFSET 8
#define CVDR_IPP_WR_PEAK_EN_LEN    1
#define CVDR_IPP_WR_PEAK_EN_OFFSET 0

#define CVDR_IPP_RD_PEAK_LEN    8
#define CVDR_IPP_RD_PEAK_OFFSET 8
#define CVDR_IPP_WR_PEAK_LEN    8
#define CVDR_IPP_WR_PEAK_OFFSET 0

#define CVDR_IPP_DEBUG_LEN    32
#define CVDR_IPP_DEBUG_OFFSET 0

#define CVDR_IPP_OTHER_RO_LEN    32
#define CVDR_IPP_OTHER_RO_OFFSET 0

#define CVDR_IPP_OTHER_RW_LEN    32
#define CVDR_IPP_OTHER_RW_OFFSET 0

#define CVDR_IPP_NRRD_ENABLE_2_LEN                               1
#define CVDR_IPP_NRRD_ENABLE_2_OFFSET                            31
#define CVDR_IPP_NR_RD_STOP_2_LEN                                1
#define CVDR_IPP_NR_RD_STOP_2_OFFSET                             25
#define CVDR_IPP_NR_RD_STOP_OK_2_LEN                             1
#define CVDR_IPP_NR_RD_STOP_OK_2_OFFSET                          24
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_2_LEN                1
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_2_OFFSET             18
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_2_LEN               1
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_2_OFFSET            17
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_2_LEN    1
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_2_OFFSET 16
#define CVDR_IPP_NRRD_ALLOCATED_DU_2_LEN                         5
#define CVDR_IPP_NRRD_ALLOCATED_DU_2_OFFSET                      5

#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_2_LEN    4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_2_OFFSET 24
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_2_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_2_OFFSET      12
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_2_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_2_OFFSET      8
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_2_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_2_OFFSET      4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_2_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_2_OFFSET      0

#define CVDR_IPP_NR_RD_DEBUG_2_LEN    32
#define CVDR_IPP_NR_RD_DEBUG_2_OFFSET 0

#define CVDR_IPP_NRRD_ENABLE_3_LEN                               1
#define CVDR_IPP_NRRD_ENABLE_3_OFFSET                            31
#define CVDR_IPP_NR_RD_STOP_3_LEN                                1
#define CVDR_IPP_NR_RD_STOP_3_OFFSET                             25
#define CVDR_IPP_NR_RD_STOP_OK_3_LEN                             1
#define CVDR_IPP_NR_RD_STOP_OK_3_OFFSET                          24
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_3_LEN                1
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_3_OFFSET             18
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_3_LEN               1
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_3_OFFSET            17
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_3_LEN    1
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_3_OFFSET 16
#define CVDR_IPP_NRRD_ALLOCATED_DU_3_LEN                         5
#define CVDR_IPP_NRRD_ALLOCATED_DU_3_OFFSET                      5

#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_3_LEN    4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_3_OFFSET 24
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_3_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_3_OFFSET      12
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_3_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_3_OFFSET      8
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_3_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_3_OFFSET      4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_3_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_3_OFFSET      0

#define CVDR_IPP_NR_RD_DEBUG_3_LEN    32
#define CVDR_IPP_NR_RD_DEBUG_3_OFFSET 0

#define CVDR_IPP_NRRD_ENABLE_4_LEN                               1
#define CVDR_IPP_NRRD_ENABLE_4_OFFSET                            31
#define CVDR_IPP_NR_RD_STOP_4_LEN                                1
#define CVDR_IPP_NR_RD_STOP_4_OFFSET                             25
#define CVDR_IPP_NR_RD_STOP_OK_4_LEN                             1
#define CVDR_IPP_NR_RD_STOP_OK_4_OFFSET                          24
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_4_LEN                1
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_4_OFFSET             18
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_4_LEN               1
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_4_OFFSET            17
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_LEN    1
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_4_OFFSET 16
#define CVDR_IPP_NRRD_ALLOCATED_DU_4_LEN                         5
#define CVDR_IPP_NRRD_ALLOCATED_DU_4_OFFSET                      5

#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_4_LEN    4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_4_OFFSET 24
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_4_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_4_OFFSET      12
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_4_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_4_OFFSET      8
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_4_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_4_OFFSET      4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_4_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_4_OFFSET      0

#define CVDR_IPP_NR_RD_DEBUG_4_LEN    32
#define CVDR_IPP_NR_RD_DEBUG_4_OFFSET 0

#define CVDR_IPP_NRRD_ENABLE_7_LEN                               1
#define CVDR_IPP_NRRD_ENABLE_7_OFFSET                            31
#define CVDR_IPP_NR_RD_STOP_7_LEN                                1
#define CVDR_IPP_NR_RD_STOP_7_OFFSET                             25
#define CVDR_IPP_NR_RD_STOP_OK_7_LEN                             1
#define CVDR_IPP_NR_RD_STOP_OK_7_OFFSET                          24
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_7_LEN                1
#define CVDR_IPP_NR_RD_STOP_ENABLE_PRESSURE_7_OFFSET             18
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_7_LEN               1
#define CVDR_IPP_NR_RD_STOP_ENABLE_FLUX_CTRL_7_OFFSET            17
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_7_LEN    1
#define CVDR_IPP_NR_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_7_OFFSET 16
#define CVDR_IPP_NRRD_ALLOCATED_DU_7_LEN                         5
#define CVDR_IPP_NRRD_ALLOCATED_DU_7_OFFSET                      5

#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_7_LEN    4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_RELOAD_7_OFFSET 24
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_7_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_3_7_OFFSET      12
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_7_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_2_7_OFFSET      8
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_7_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_1_7_OFFSET      4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_7_LEN         4
#define CVDR_IPP_NRRD_ACCESS_LIMITER_0_7_OFFSET      0


#define CVDR_IPP_NRWR_ENABLE_6_LEN                               1
#define CVDR_IPP_NRWR_ENABLE_6_OFFSET                            31
#define CVDR_IPP_NR_WR_STOP_6_LEN                                1
#define CVDR_IPP_NR_WR_STOP_6_OFFSET                             25
#define CVDR_IPP_NR_WR_STOP_OK_6_LEN                             1
#define CVDR_IPP_NR_WR_STOP_OK_6_OFFSET                          24
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_6_LEN                1
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_6_OFFSET             18
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_6_LEN               1
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_6_OFFSET            17
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_6_LEN    1
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_6_OFFSET 16

#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_6_LEN    4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_6_OFFSET 24
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_6_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_6_OFFSET      12
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_6_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_6_OFFSET      8
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_6_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_6_OFFSET      4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_6_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_6_OFFSET      0

#define CVDR_IPP_NRWR_ENABLE_7_LEN                               1
#define CVDR_IPP_NRWR_ENABLE_7_OFFSET                            31
#define CVDR_IPP_NR_WR_STOP_7_LEN                                1
#define CVDR_IPP_NR_WR_STOP_7_OFFSET                             25
#define CVDR_IPP_NR_WR_STOP_OK_7_LEN                             1
#define CVDR_IPP_NR_WR_STOP_OK_7_OFFSET                          24
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_7_LEN                1
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_7_OFFSET             18
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_7_LEN               1
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_7_OFFSET            17
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_7_LEN    1
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_7_OFFSET 16

#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_7_LEN    4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_7_OFFSET 24
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_7_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_7_OFFSET      12
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_7_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_7_OFFSET      8
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_7_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_7_OFFSET      4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_7_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_7_OFFSET      0

#define CVDR_IPP_NRWR_ENABLE_8_LEN                               1
#define CVDR_IPP_NRWR_ENABLE_8_OFFSET                            31
#define CVDR_IPP_NR_WR_STOP_8_LEN                                1
#define CVDR_IPP_NR_WR_STOP_8_OFFSET                             25
#define CVDR_IPP_NR_WR_STOP_OK_8_LEN                             1
#define CVDR_IPP_NR_WR_STOP_OK_8_OFFSET                          24
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_8_LEN                1
#define CVDR_IPP_NR_WR_STOP_ENABLE_PRESSURE_8_OFFSET             18
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_8_LEN               1
#define CVDR_IPP_NR_WR_STOP_ENABLE_FLUX_CTRL_8_OFFSET            17
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_8_LEN    1
#define CVDR_IPP_NR_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_8_OFFSET 16

#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_8_LEN    4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_RELOAD_8_OFFSET 24
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_8_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_3_8_OFFSET      12
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_8_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_2_8_OFFSET      8
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_8_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_1_8_OFFSET      4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_8_LEN         4
#define CVDR_IPP_NRWR_ACCESS_LIMITER_0_8_OFFSET      0


#define CVDR_IPP_VPRD_LAST_PAGE_0_LEN          19
#define CVDR_IPP_VPRD_LAST_PAGE_0_OFFSET       13
#define CVDR_IPP_VPRD_ALLOCATED_DU_0_LEN       5
#define CVDR_IPP_VPRD_ALLOCATED_DU_0_OFFSET    6
#define CVDR_IPP_VPRD_PIXEL_EXPANSION_0_LEN    1
#define CVDR_IPP_VPRD_PIXEL_EXPANSION_0_OFFSET 5
#define CVDR_IPP_VPRD_PIXEL_FORMAT_0_LEN       5
#define CVDR_IPP_VPRD_PIXEL_FORMAT_0_OFFSET    0

#define CVDR_IPP_VPRD_HORIZONTAL_BLANKING_0_LEN    8
#define CVDR_IPP_VPRD_HORIZONTAL_BLANKING_0_OFFSET 16
#define CVDR_IPP_VPRD_LINE_SIZE_0_LEN              15
#define CVDR_IPP_VPRD_LINE_SIZE_0_OFFSET           0

#define CVDR_IPP_VPRD_VERTICAL_BLANKING_0_LEN    8
#define CVDR_IPP_VPRD_VERTICAL_BLANKING_0_OFFSET 16
#define CVDR_IPP_VPRD_FRAME_SIZE_0_LEN           15
#define CVDR_IPP_VPRD_FRAME_SIZE_0_OFFSET        0

#define CVDR_IPP_VPRD_AXI_FRAME_START_0_LEN    30
#define CVDR_IPP_VPRD_AXI_FRAME_START_0_OFFSET 2

#define CVDR_IPP_VPRD_LINE_WRAP_0_LEN      14
#define CVDR_IPP_VPRD_LINE_WRAP_0_OFFSET   18
#define CVDR_IPP_VPRD_LINE_STRIDE_0_LEN    14
#define CVDR_IPP_VPRD_LINE_STRIDE_0_OFFSET 0

#define CVDR_IPP_VPRD_PREFETCH_BYPASS_0_LEN                      1
#define CVDR_IPP_VPRD_PREFETCH_BYPASS_0_OFFSET                   31
#define CVDR_IPP_VP_RD_STOP_0_LEN                                1
#define CVDR_IPP_VP_RD_STOP_0_OFFSET                             25
#define CVDR_IPP_VP_RD_STOP_OK_0_LEN                             1
#define CVDR_IPP_VP_RD_STOP_OK_0_OFFSET                          24
#define CVDR_IPP_VP_RD_STOP_ENABLE_PRESSURE_0_LEN                1
#define CVDR_IPP_VP_RD_STOP_ENABLE_PRESSURE_0_OFFSET             18
#define CVDR_IPP_VP_RD_STOP_ENABLE_FLUX_CTRL_0_LEN               1
#define CVDR_IPP_VP_RD_STOP_ENABLE_FLUX_CTRL_0_OFFSET            17
#define CVDR_IPP_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_0_LEN    1
#define CVDR_IPP_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_0_OFFSET 16

#define CVDR_IPP_VPRD_ACCESS_LIMITER_RELOAD_0_LEN    4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_RELOAD_0_OFFSET 24
#define CVDR_IPP_VPRD_ACCESS_LIMITER_3_0_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_3_0_OFFSET      12
#define CVDR_IPP_VPRD_ACCESS_LIMITER_2_0_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_2_0_OFFSET      8
#define CVDR_IPP_VPRD_ACCESS_LIMITER_1_0_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_1_0_OFFSET      4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_0_0_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_0_0_OFFSET      0

#define CVDR_IPP_VP_RD_DEBUG_0_LEN    32
#define CVDR_IPP_VP_RD_DEBUG_0_OFFSET 0

#define CVDR_IPP_VPRD_LAST_PAGE_6_LEN          19
#define CVDR_IPP_VPRD_LAST_PAGE_6_OFFSET       13
#define CVDR_IPP_VPRD_ALLOCATED_DU_6_LEN       5
#define CVDR_IPP_VPRD_ALLOCATED_DU_6_OFFSET    6
#define CVDR_IPP_VPRD_PIXEL_EXPANSION_6_LEN    1
#define CVDR_IPP_VPRD_PIXEL_EXPANSION_6_OFFSET 5
#define CVDR_IPP_VPRD_PIXEL_FORMAT_6_LEN       5
#define CVDR_IPP_VPRD_PIXEL_FORMAT_6_OFFSET    0

#define CVDR_IPP_VPRD_HORIZONTAL_BLANKING_6_LEN    8
#define CVDR_IPP_VPRD_HORIZONTAL_BLANKING_6_OFFSET 16
#define CVDR_IPP_VPRD_LINE_SIZE_6_LEN              15
#define CVDR_IPP_VPRD_LINE_SIZE_6_OFFSET           0

#define CVDR_IPP_VPRD_VERTICAL_BLANKING_6_LEN    8
#define CVDR_IPP_VPRD_VERTICAL_BLANKING_6_OFFSET 16
#define CVDR_IPP_VPRD_FRAME_SIZE_6_LEN           15
#define CVDR_IPP_VPRD_FRAME_SIZE_6_OFFSET        0

#define CVDR_IPP_VPRD_AXI_FRAME_START_6_LEN    30
#define CVDR_IPP_VPRD_AXI_FRAME_START_6_OFFSET 2

#define CVDR_IPP_VPRD_LINE_WRAP_6_LEN      14
#define CVDR_IPP_VPRD_LINE_WRAP_6_OFFSET   18
#define CVDR_IPP_VPRD_LINE_STRIDE_6_LEN    14
#define CVDR_IPP_VPRD_LINE_STRIDE_6_OFFSET 0

#define CVDR_IPP_VPRD_PREFETCH_BYPASS_6_LEN                      1
#define CVDR_IPP_VPRD_PREFETCH_BYPASS_6_OFFSET                   31
#define CVDR_IPP_VP_RD_STOP_6_LEN                                1
#define CVDR_IPP_VP_RD_STOP_6_OFFSET                             25
#define CVDR_IPP_VP_RD_STOP_OK_6_LEN                             1
#define CVDR_IPP_VP_RD_STOP_OK_6_OFFSET                          24
#define CVDR_IPP_VP_RD_STOP_ENABLE_PRESSURE_6_LEN                1
#define CVDR_IPP_VP_RD_STOP_ENABLE_PRESSURE_6_OFFSET             18
#define CVDR_IPP_VP_RD_STOP_ENABLE_FLUX_CTRL_6_LEN               1
#define CVDR_IPP_VP_RD_STOP_ENABLE_FLUX_CTRL_6_OFFSET            17
#define CVDR_IPP_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_6_LEN    1
#define CVDR_IPP_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_6_OFFSET 16

#define CVDR_IPP_VPRD_ACCESS_LIMITER_RELOAD_6_LEN    4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_RELOAD_6_OFFSET 24
#define CVDR_IPP_VPRD_ACCESS_LIMITER_3_6_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_3_6_OFFSET      12
#define CVDR_IPP_VPRD_ACCESS_LIMITER_2_6_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_2_6_OFFSET      8
#define CVDR_IPP_VPRD_ACCESS_LIMITER_1_6_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_1_6_OFFSET      4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_0_6_LEN         4
#define CVDR_IPP_VPRD_ACCESS_LIMITER_0_6_OFFSET      0

#define CVDR_IPP_VP_RD_DEBUG_6_LEN    32
#define CVDR_IPP_VP_RD_DEBUG_6_OFFSET 0

#define CVDR_IPP_VPWR_PREFETCH_BYPASS_0_LEN                      1
#define CVDR_IPP_VPWR_PREFETCH_BYPASS_0_OFFSET                   31
#define CVDR_IPP_VP_WR_STOP_0_LEN                                1
#define CVDR_IPP_VP_WR_STOP_0_OFFSET                             25
#define CVDR_IPP_VP_WR_STOP_OK_0_LEN                             1
#define CVDR_IPP_VP_WR_STOP_OK_0_OFFSET                          24
#define CVDR_IPP_VP_WR_STOP_ENABLE_PRESSURE_0_LEN                1
#define CVDR_IPP_VP_WR_STOP_ENABLE_PRESSURE_0_OFFSET             18
#define CVDR_IPP_VP_WR_STOP_ENABLE_FLUX_CTRL_0_LEN               1
#define CVDR_IPP_VP_WR_STOP_ENABLE_FLUX_CTRL_0_OFFSET            17
#define CVDR_IPP_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_0_LEN    1
#define CVDR_IPP_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_0_OFFSET 16

#define CVDR_IPP_VPWR_ACCESS_LIMITER_RELOAD_0_LEN    4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_RELOAD_0_OFFSET 24
#define CVDR_IPP_VPWR_ACCESS_LIMITER_3_0_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_3_0_OFFSET      12
#define CVDR_IPP_VPWR_ACCESS_LIMITER_2_0_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_2_0_OFFSET      8
#define CVDR_IPP_VPWR_ACCESS_LIMITER_1_0_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_1_0_OFFSET      4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_0_0_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_0_0_OFFSET      0

#define CVDR_IPP_VPWR_LINE_WRAP_SID0_0_LEN           14
#define CVDR_IPP_VPWR_LINE_WRAP_SID0_0_OFFSET        18
#define CVDR_IPP_VPWR_LINE_START_WSTRB_SID0_0_LEN    4
#define CVDR_IPP_VPWR_LINE_START_WSTRB_SID0_0_OFFSET 14
#define CVDR_IPP_VPWR_LINE_STRIDE_SID0_0_LEN         14
#define CVDR_IPP_VPWR_LINE_STRIDE_SID0_0_OFFSET      0

#define CVDR_IPP_VP_WR_STRIPE_SIZE_BYTES_SID0_0_LEN    16
#define CVDR_IPP_VP_WR_STRIPE_SIZE_BYTES_SID0_0_OFFSET 0

#define CVDR_IPP_VPWR_LAST_PAGE_SID0_0_LEN          19
#define CVDR_IPP_VPWR_LAST_PAGE_SID0_0_OFFSET       13
#define CVDR_IPP_VPWR_4PF_ENABLE_SID0_0_LEN         1
#define CVDR_IPP_VPWR_4PF_ENABLE_SID0_0_OFFSET      6
#define CVDR_IPP_VPWR_PIXEL_EXPANSION_SID0_0_LEN    1
#define CVDR_IPP_VPWR_PIXEL_EXPANSION_SID0_0_OFFSET 5
#define CVDR_IPP_VPWR_PIXEL_FORMAT_SID0_0_LEN       5
#define CVDR_IPP_VPWR_PIXEL_FORMAT_SID0_0_OFFSET    0

#define CVDR_IPP_VPWR_ADDRESS_FRAME_START_SID0_0_LEN    30
#define CVDR_IPP_VPWR_ADDRESS_FRAME_START_SID0_0_OFFSET 2

#define CVDR_IPP_VP_WR_DEBUG_SID0_0_LEN    32
#define CVDR_IPP_VP_WR_DEBUG_SID0_0_OFFSET 0

#define CVDR_IPP_VPWR_PREFETCH_BYPASS_3_LEN                      1
#define CVDR_IPP_VPWR_PREFETCH_BYPASS_3_OFFSET                   31
#define CVDR_IPP_VP_WR_STOP_3_LEN                                1
#define CVDR_IPP_VP_WR_STOP_3_OFFSET                             25
#define CVDR_IPP_VP_WR_STOP_OK_3_LEN                             1
#define CVDR_IPP_VP_WR_STOP_OK_3_OFFSET                          24
#define CVDR_IPP_VP_WR_STOP_ENABLE_PRESSURE_3_LEN                1
#define CVDR_IPP_VP_WR_STOP_ENABLE_PRESSURE_3_OFFSET             18
#define CVDR_IPP_VP_WR_STOP_ENABLE_FLUX_CTRL_3_LEN               1
#define CVDR_IPP_VP_WR_STOP_ENABLE_FLUX_CTRL_3_OFFSET            17
#define CVDR_IPP_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_3_LEN    1
#define CVDR_IPP_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_3_OFFSET 16

#define CVDR_IPP_VPWR_ACCESS_LIMITER_RELOAD_3_LEN    4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_RELOAD_3_OFFSET 24
#define CVDR_IPP_VPWR_ACCESS_LIMITER_3_3_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_3_3_OFFSET      12
#define CVDR_IPP_VPWR_ACCESS_LIMITER_2_3_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_2_3_OFFSET      8
#define CVDR_IPP_VPWR_ACCESS_LIMITER_1_3_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_1_3_OFFSET      4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_0_3_LEN         4
#define CVDR_IPP_VPWR_ACCESS_LIMITER_0_3_OFFSET      0

#define CVDR_IPP_VPWR_LINE_WRAP_SID0_3_LEN           14
#define CVDR_IPP_VPWR_LINE_WRAP_SID0_3_OFFSET        18
#define CVDR_IPP_VPWR_LINE_START_WSTRB_SID0_3_LEN    4
#define CVDR_IPP_VPWR_LINE_START_WSTRB_SID0_3_OFFSET 14
#define CVDR_IPP_VPWR_LINE_STRIDE_SID0_3_LEN         14
#define CVDR_IPP_VPWR_LINE_STRIDE_SID0_3_OFFSET      0

#define CVDR_IPP_VP_WR_STRIPE_SIZE_BYTES_SID0_3_LEN    16
#define CVDR_IPP_VP_WR_STRIPE_SIZE_BYTES_SID0_3_OFFSET 0

#define CVDR_IPP_VPWR_LAST_PAGE_SID0_3_LEN          19
#define CVDR_IPP_VPWR_LAST_PAGE_SID0_3_OFFSET       13
#define CVDR_IPP_VPWR_4PF_ENABLE_SID0_3_LEN         1
#define CVDR_IPP_VPWR_4PF_ENABLE_SID0_3_OFFSET      6
#define CVDR_IPP_VPWR_PIXEL_EXPANSION_SID0_3_LEN    1
#define CVDR_IPP_VPWR_PIXEL_EXPANSION_SID0_3_OFFSET 5
#define CVDR_IPP_VPWR_PIXEL_FORMAT_SID0_3_LEN       5
#define CVDR_IPP_VPWR_PIXEL_FORMAT_SID0_3_OFFSET    0

#define CVDR_IPP_VPWR_ADDRESS_FRAME_START_SID0_3_LEN    30
#define CVDR_IPP_VPWR_ADDRESS_FRAME_START_SID0_3_OFFSET 2

#define CVDR_IPP_VP_WR_DEBUG_SID0_3_LEN    32
#define CVDR_IPP_VP_WR_DEBUG_SID0_3_OFFSET 0

#endif // __CVDR_IPP_REG_OFFSET_FIELD_H__
