// ******************************************************************************
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  ipp_top_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2020/04/15 14:54:24 Create file
// ******************************************************************************

#ifndef __IPP_TOP_REG_OFFSET_FIELD_H__
#define __IPP_TOP_REG_OFFSET_FIELD_H__

#define IPP_TOP_DLOCK_AND_DBG_CLR_LEN    1
#define IPP_TOP_DLOCK_AND_DBG_CLR_OFFSET 16

#define IPP_TOP_DPM_CLKEN_LEN         1
#define IPP_TOP_DPM_CLKEN_OFFSET      4
#define IPP_TOP_CMDLST_CLKEN_LEN      1
#define IPP_TOP_CMDLST_CLKEN_OFFSET   3
#define IPP_TOP_TBU_CVDR_CLKEN_LEN    1
#define IPP_TOP_TBU_CVDR_CLKEN_OFFSET 1
#define IPP_TOP_CVDR_CLKEN_LEN        1
#define IPP_TOP_CVDR_CLKEN_OFFSET     0

#define IPP_TOP_DPM_SOFT_RST_LEN         1
#define IPP_TOP_DPM_SOFT_RST_OFFSET      4
#define IPP_TOP_CMDLST_SOFT_RST_LEN      1
#define IPP_TOP_CMDLST_SOFT_RST_OFFSET   3
#define IPP_TOP_TBU_CVDR_SOFT_RST_LEN    1
#define IPP_TOP_TBU_CVDR_SOFT_RST_OFFSET 1
#define IPP_TOP_CVDR_SOFT_RST_LEN        1
#define IPP_TOP_CVDR_SOFT_RST_OFFSET     0

#define IPP_TOP_CVDR_IRQ_CLR_LEN    8
#define IPP_TOP_CVDR_IRQ_CLR_OFFSET 0

#define IPP_TOP_CVDR_IRQ_MASK_LEN    8
#define IPP_TOP_CVDR_IRQ_MASK_OFFSET 0

#define IPP_TOP_CVDR_IRQ_STATE_RAW_LEN    8
#define IPP_TOP_CVDR_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_CVDR_IRQ_STATE_MASK_LEN    8
#define IPP_TOP_CVDR_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_MEM_CTRL_SP_LEN         29
#define IPP_TOP_MEM_CTRL_SP_OFFSET      3
#define IPP_TOP_CVDR_MEM_CTRL_SP_LEN    3
#define IPP_TOP_CVDR_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_MEM_CTRL_TP_LEN    29
#define IPP_TOP_MEM_CTRL_TP_OFFSET 3

#define IPP_TOP_MEM_CTRL_SPUA_LEN    29
#define IPP_TOP_MEM_CTRL_SPUA_OFFSET 3

#define IPP_TOP_RESERVED_EC_0_LEN    32
#define IPP_TOP_RESERVED_EC_0_OFFSET 0

#define IPP_TOP_RESERVED_EC_1_LEN    32
#define IPP_TOP_RESERVED_EC_1_OFFSET 0

#define IPP_TOP_RESERVED_EC_2_LEN    32
#define IPP_TOP_RESERVED_EC_2_OFFSET 0

#define IPP_TOP_RESERVED_EC_3_LEN    32
#define IPP_TOP_RESERVED_EC_3_OFFSET 0

#define IPP_TOP_RESERVED_EC_4_LEN    32
#define IPP_TOP_RESERVED_EC_4_OFFSET 0

#define IPP_TOP_RESERVED_EC_5_LEN    32
#define IPP_TOP_RESERVED_EC_5_OFFSET 0

#define IPP_TOP_RESERVED_EC_6_LEN    32
#define IPP_TOP_RESERVED_EC_6_OFFSET 0

#define IPP_TOP_RESERVED_EC_7_LEN    32
#define IPP_TOP_RESERVED_EC_7_OFFSET 0

#define IPP_TOP_RESERVED_EC_8_LEN    32
#define IPP_TOP_RESERVED_EC_8_OFFSET 0

#define IPP_TOP_RESERVED_EC_9_LEN    32
#define IPP_TOP_RESERVED_EC_9_OFFSET 0

#define IPP_TOP_RESERVED_EC_10_LEN    32
#define IPP_TOP_RESERVED_EC_10_OFFSET 0

#define IPP_TOP_RESERVED_EC_11_LEN    32
#define IPP_TOP_RESERVED_EC_11_OFFSET 0

#define IPP_TOP_RESERVED_EC_12_LEN    32
#define IPP_TOP_RESERVED_EC_12_OFFSET 0

#define IPP_TOP_RESERVED_EC_13_LEN    32
#define IPP_TOP_RESERVED_EC_13_OFFSET 0

#define IPP_TOP_RESERVED_EC_14_LEN    32
#define IPP_TOP_RESERVED_EC_14_OFFSET 0

#define IPP_TOP_RESERVED_EC_15_LEN    32
#define IPP_TOP_RESERVED_EC_15_OFFSET 0

#define IPP_TOP_FLUX_CTRL0_CVDR_R_LEN    32
#define IPP_TOP_FLUX_CTRL0_CVDR_R_OFFSET 0

#define IPP_TOP_FLUX_CTRL1_CVDR_R_LEN    32
#define IPP_TOP_FLUX_CTRL1_CVDR_R_OFFSET 0

#define IPP_TOP_FLUX_CTRL0_CVDR_W_LEN    32
#define IPP_TOP_FLUX_CTRL0_CVDR_W_OFFSET 0

#define IPP_TOP_FLUX_CTRL1_CVDR_W_LEN    32
#define IPP_TOP_FLUX_CTRL1_CVDR_W_OFFSET 0

#define IPP_TOP_JPG_BWC_CFG_LEN    32
#define IPP_TOP_JPG_BWC_CFG_OFFSET 0



#define IPP_TOP_JPGENC_FORCE_CLK_ON_LEN    1
#define IPP_TOP_JPGENC_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_JPGENC_CLKEN_LEN           1
#define IPP_TOP_JPGENC_CLKEN_OFFSET        0

#define IPP_TOP_JPGENC_SOFT_RST_LEN    1
#define IPP_TOP_JPGENC_SOFT_RST_OFFSET 0

#define IPP_TOP_JPGENC_MEM_CTRL_SP_LEN    3
#define IPP_TOP_JPGENC_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_CLR_LEN    5
#define IPP_TOP_JPGENC_IRQ_CLR_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_MASK_LEN    5
#define IPP_TOP_JPGENC_IRQ_MASK_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_STATE_RAW_LEN    5
#define IPP_TOP_JPGENC_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_JPGENC_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_JPGENC_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_JPGDEC_FORCE_CLK_ON_LEN    1
#define IPP_TOP_JPGDEC_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_JPGDEC_CLKEN_LEN           1
#define IPP_TOP_JPGDEC_CLKEN_OFFSET        0

#define IPP_TOP_JPGDEC_SOFT_RST_LEN    1
#define IPP_TOP_JPGDEC_SOFT_RST_OFFSET 0

#define IPP_TOP_JPGDEC_MEM_CTRL_TP_LEN    3
#define IPP_TOP_JPGDEC_MEM_CTRL_TP_OFFSET 4
#define IPP_TOP_JPGDEC_MEM_CTRL_SP_LEN    3
#define IPP_TOP_JPGDEC_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_CLR_LEN    4
#define IPP_TOP_JPGDEC_IRQ_CLR_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_MASK_LEN    4
#define IPP_TOP_JPGDEC_IRQ_MASK_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_STATE_RAW_LEN    4
#define IPP_TOP_JPGDEC_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_JPGDEC_IRQ_STATE_MASK_LEN    4
#define IPP_TOP_JPGDEC_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_GF_FORCE_CLK_ON_LEN    1
#define IPP_TOP_GF_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_GF_CLKEN_LEN           1
#define IPP_TOP_GF_CLKEN_OFFSET        0

#define IPP_TOP_GF_SOFT_RST_LEN    1
#define IPP_TOP_GF_SOFT_RST_OFFSET 0

#define IPP_TOP_GF_MEM_CTRL_SP_LEN    3
#define IPP_TOP_GF_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_GF_IRQ_CLR_LEN    13
#define IPP_TOP_GF_IRQ_CLR_OFFSET 0

#define IPP_TOP_GF_IRQ_OUTEN_LEN    2
#define IPP_TOP_GF_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_GF_IRQ_MASK_LEN    13
#define IPP_TOP_GF_IRQ_MASK_OFFSET 0

#define IPP_TOP_GF_IRQ_STATE_MASK_LEN    13
#define IPP_TOP_GF_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_GF_IRQ_STATE_RAW_LEN    13
#define IPP_TOP_GF_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_ARF_FORCE_CLK_ON_LEN    1
#define IPP_TOP_ARF_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_ARF_CLKEN_LEN           1
#define IPP_TOP_ARF_CLKEN_OFFSET        0

#define IPP_TOP_ARF_SOFT_RST_LEN    1
#define IPP_TOP_ARF_SOFT_RST_OFFSET 0

#define IPP_TOP_ARF_MEM_CTRL_SP_LEN    3
#define IPP_TOP_ARF_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_ARF_IRQ_CLR_LEN    30
#define IPP_TOP_ARF_IRQ_CLR_OFFSET 0

#define IPP_TOP_ARF_IRQ_OUTEN_LEN    2
#define IPP_TOP_ARF_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_ARF_IRQ_MASK_LEN    30
#define IPP_TOP_ARF_IRQ_MASK_OFFSET 0

#define IPP_TOP_ARF_IRQ_STATE_RAW_LEN    30
#define IPP_TOP_ARF_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_ARF_IRQ_STATE_MASK_LEN    30
#define IPP_TOP_ARF_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_RDR_FORCE_CLK_ON_LEN    1
#define IPP_TOP_RDR_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_RDR_CLKEN_LEN           1
#define IPP_TOP_RDR_CLKEN_OFFSET        0

#define IPP_TOP_RDR_SOFT_RST_LEN    1
#define IPP_TOP_RDR_SOFT_RST_OFFSET 0

#define IPP_TOP_RDR_MEM_CTRL_SP_LEN    3
#define IPP_TOP_RDR_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_RDR_IRQ_CLR_LEN    5
#define IPP_TOP_RDR_IRQ_CLR_OFFSET 0

#define IPP_TOP_RDR_IRQ_OUTEN_LEN    2
#define IPP_TOP_RDR_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_RDR_IRQ_MASK_LEN    5
#define IPP_TOP_RDR_IRQ_MASK_OFFSET 0

#define IPP_TOP_RDR_IRQ_STATE_RAW_LEN    5
#define IPP_TOP_RDR_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_RDR_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_RDR_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_CMP_FORCE_CLK_ON_LEN    1
#define IPP_TOP_CMP_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_CMP_CLKEN_LEN           1
#define IPP_TOP_CMP_CLKEN_OFFSET        0

#define IPP_TOP_CMP_SOFT_RST_LEN    1
#define IPP_TOP_CMP_SOFT_RST_OFFSET 0

#define IPP_TOP_CMP_MEM_CTRL_SP_LEN    3
#define IPP_TOP_CMP_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_CMP_IRQ_CLR_LEN    5
#define IPP_TOP_CMP_IRQ_CLR_OFFSET 0

#define IPP_TOP_CMP_IRQ_OUTEN_LEN    2
#define IPP_TOP_CMP_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_CMP_IRQ_MASK_LEN    5
#define IPP_TOP_CMP_IRQ_MASK_OFFSET 0

#define IPP_TOP_CMP_IRQ_STATE_RAW_LEN    5
#define IPP_TOP_CMP_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_CMP_IRQ_STATE_MASK_LEN    5
#define IPP_TOP_CMP_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_ENH_FORCE_CLK_ON_LEN    1
#define IPP_TOP_ENH_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_ENH_CLKEN_LEN           1
#define IPP_TOP_ENH_CLKEN_OFFSET        0

#define IPP_TOP_ENH_SOFT_RST_LEN    1
#define IPP_TOP_ENH_SOFT_RST_OFFSET 0

#define IPP_TOP_ENH_MEM_CTRL_SP_LEN    3
#define IPP_TOP_ENH_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_ENH_VPBG_EN_LEN    2
#define IPP_TOP_ENH_VPBG_EN_OFFSET 0

#define IPP_TOP_ENH_IRQ_CLR_LEN    10
#define IPP_TOP_ENH_IRQ_CLR_OFFSET 0

#define IPP_TOP_ENH_IRQ_OUTEN_LEN    2
#define IPP_TOP_ENH_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_ENH_IRQ_MASK_LEN    10
#define IPP_TOP_ENH_IRQ_MASK_OFFSET 0

#define IPP_TOP_ENH_IRQ_STATE_RAW_LEN    10
#define IPP_TOP_ENH_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_ENH_IRQ_STATE_MASK_LEN    10
#define IPP_TOP_ENH_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_HIOF_FORCE_CLK_ON_LEN    1
#define IPP_TOP_HIOF_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_HIOF_CLKEN_LEN           1
#define IPP_TOP_HIOF_CLKEN_OFFSET        0

#define IPP_TOP_HIOF_SOFT_RST_LEN    1
#define IPP_TOP_HIOF_SOFT_RST_OFFSET 0

#define IPP_TOP_HIOF_MEM_CTRL_SP_LEN    3
#define IPP_TOP_HIOF_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_HIOF_IRQ_CLR_LEN    13
#define IPP_TOP_HIOF_IRQ_CLR_OFFSET 0

#define IPP_TOP_HIOF_IRQ_MASK_LEN    24
#define IPP_TOP_HIOF_IRQ_MASK_OFFSET 0

#define IPP_TOP_HIOF_IRQ_OUTEN_LEN    2
#define IPP_TOP_HIOF_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_HIOF_IRQ_STATE_MASK_LEN    24
#define IPP_TOP_HIOF_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_HIOF_IRQ_STATE_RAW_LEN    24
#define IPP_TOP_HIOF_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_0_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_0_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_1_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_1_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_2_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_2_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_3_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_3_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_4_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_4_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_5_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_5_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_6_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_6_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_7_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_7_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_8_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_8_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_9_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_9_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_10_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_10_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_11_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_11_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_12_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_12_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_13_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_13_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_14_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_14_OFFSET 0

#define IPP_TOP_CMDLST_CTRL_CHN_15_LEN    4
#define IPP_TOP_CMDLST_CTRL_CHN_15_OFFSET 0

#define IPP_TOP_CMDLST_POST_MASK_0_LEN    2
#define IPP_TOP_CMDLST_POST_MASK_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_CLR_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_CLR_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_MASK_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_MASK_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_RAW_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_RAW_0_OFFSET 0

#define IPP_TOP_CMDLST_IRQ_STATE_MASK_0_LEN    16
#define IPP_TOP_CMDLST_IRQ_STATE_MASK_0_OFFSET 0

#define IPP_TOP_MC_FORCE_CLK_ON_LEN    1
#define IPP_TOP_MC_FORCE_CLK_ON_OFFSET 16
#define IPP_TOP_MC_CLKEN_LEN           1
#define IPP_TOP_MC_CLKEN_OFFSET        0

#define IPP_TOP_MC_SOFT_RST_LEN    1
#define IPP_TOP_MC_SOFT_RST_OFFSET 0

#define IPP_TOP_MC_MEM_CTRL_SP_LEN    3
#define IPP_TOP_MC_MEM_CTRL_SP_OFFSET 0

#define IPP_TOP_MC_IRQ_CLR_LEN    3
#define IPP_TOP_MC_IRQ_CLR_OFFSET 0

#define IPP_TOP_MC_IRQ_MASK_LEN    3
#define IPP_TOP_MC_IRQ_MASK_OFFSET 0

#define IPP_TOP_MC_IRQ_OUTEN_LEN    2
#define IPP_TOP_MC_IRQ_OUTEN_OFFSET 0

#define IPP_TOP_MC_IRQ_STATE_MASK_LEN    3
#define IPP_TOP_MC_IRQ_STATE_MASK_OFFSET 0

#define IPP_TOP_MC_IRQ_STATE_RAW_LEN    3
#define IPP_TOP_MC_IRQ_STATE_RAW_OFFSET 0

#define IPP_TOP_DEBUG_INFO_0_LEN    32
#define IPP_TOP_DEBUG_INFO_0_OFFSET 0

#define IPP_TOP_DEBUG_INFO_1_LEN    32
#define IPP_TOP_DEBUG_INFO_1_OFFSET 0

#define IPP_TOP_DEBUG_INFO_2_LEN    32
#define IPP_TOP_DEBUG_INFO_2_OFFSET 0

#define IPP_TOP_DEBUG_INFO_3_LEN    32
#define IPP_TOP_DEBUG_INFO_3_OFFSET 0

#define IPP_TOP_TOP_TZ_SECURE_N_LEN    1
#define IPP_TOP_TOP_TZ_SECURE_N_OFFSET 0

#endif // __IPP_TOP_REG_OFFSET_FIELD_H__
