// ******************************************************************************
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  slam_reorder_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Date          :  2020/04/10
// Description   :
// Others        :  Generated automatically by nManager V4.2
// ******************************************************************************

#ifndef __SLAM_REORDER_REG_OFFSET_FIELD_H__
#define __SLAM_REORDER_REG_OFFSET_FIELD_H__

#define SLAM_REORDER_REORDER_EN_LEN    1
#define SLAM_REORDER_REORDER_EN_OFFSET 0

#define SLAM_REORDER_BLK_NUM_LEN      10
#define SLAM_REORDER_BLK_NUM_OFFSET   16
#define SLAM_REORDER_BLK_H_NUM_LEN    5
#define SLAM_REORDER_BLK_H_NUM_OFFSET 8
#define SLAM_REORDER_BLK_V_NUM_LEN    5
#define SLAM_REORDER_BLK_V_NUM_OFFSET 0

#define SLAM_REORDER_TOTAL_KPT_NUM_LEN    15
#define SLAM_REORDER_TOTAL_KPT_NUM_OFFSET 0

#define SLAM_REORDER_PREFETCH_ENABLE_LEN    1
#define SLAM_REORDER_PREFETCH_ENABLE_OFFSET 24
#define SLAM_REORDER_FIRST_4K_PAGE_LEN      24
#define SLAM_REORDER_FIRST_4K_PAGE_OFFSET   0

#define SLAM_REORDER_DEBUG_0_LEN    32
#define SLAM_REORDER_DEBUG_0_OFFSET 0

#define SLAM_REORDER_DEBUG_1_LEN    32
#define SLAM_REORDER_DEBUG_1_OFFSET 0

#define SLAM_REORDER_EC_0_LEN    32
#define SLAM_REORDER_EC_0_OFFSET 0

#define SLAM_REORDER_EC_1_LEN    32
#define SLAM_REORDER_EC_1_OFFSET 0

#define SLAM_REORDER_KPT_NUM_0_LEN    32
#define SLAM_REORDER_KPT_NUM_0_OFFSET 0

#define SLAM_REORDER_KPT_NUM_1_LEN    32
#define SLAM_REORDER_KPT_NUM_1_OFFSET 0

#define SLAM_REORDER_KPT_NUM_2_LEN    32
#define SLAM_REORDER_KPT_NUM_2_OFFSET 0

#define SLAM_REORDER_KPT_NUM_3_LEN    32
#define SLAM_REORDER_KPT_NUM_3_OFFSET 0

#define SLAM_REORDER_KPT_NUM_4_LEN    32
#define SLAM_REORDER_KPT_NUM_4_OFFSET 0

#define SLAM_REORDER_KPT_NUM_5_LEN    32
#define SLAM_REORDER_KPT_NUM_5_OFFSET 0

#define SLAM_REORDER_KPT_NUM_6_LEN    32
#define SLAM_REORDER_KPT_NUM_6_OFFSET 0

#define SLAM_REORDER_KPT_NUM_7_LEN    32
#define SLAM_REORDER_KPT_NUM_7_OFFSET 0

#define SLAM_REORDER_KPT_NUM_8_LEN    32
#define SLAM_REORDER_KPT_NUM_8_OFFSET 0

#define SLAM_REORDER_KPT_NUM_9_LEN    32
#define SLAM_REORDER_KPT_NUM_9_OFFSET 0

#define SLAM_REORDER_KPT_NUM_10_LEN    32
#define SLAM_REORDER_KPT_NUM_10_OFFSET 0

#define SLAM_REORDER_KPT_NUM_11_LEN    32
#define SLAM_REORDER_KPT_NUM_11_OFFSET 0

#define SLAM_REORDER_KPT_NUM_12_LEN    32
#define SLAM_REORDER_KPT_NUM_12_OFFSET 0

#define SLAM_REORDER_KPT_NUM_13_LEN    32
#define SLAM_REORDER_KPT_NUM_13_OFFSET 0

#define SLAM_REORDER_KPT_NUM_14_LEN    32
#define SLAM_REORDER_KPT_NUM_14_OFFSET 0

#define SLAM_REORDER_KPT_NUM_15_LEN    32
#define SLAM_REORDER_KPT_NUM_15_OFFSET 0

#define SLAM_REORDER_KPT_NUM_16_LEN    32
#define SLAM_REORDER_KPT_NUM_16_OFFSET 0

#define SLAM_REORDER_KPT_NUM_17_LEN    32
#define SLAM_REORDER_KPT_NUM_17_OFFSET 0

#define SLAM_REORDER_KPT_NUM_18_LEN    32
#define SLAM_REORDER_KPT_NUM_18_OFFSET 0

#define SLAM_REORDER_KPT_NUM_19_LEN    32
#define SLAM_REORDER_KPT_NUM_19_OFFSET 0

#define SLAM_REORDER_KPT_NUM_20_LEN    32
#define SLAM_REORDER_KPT_NUM_20_OFFSET 0

#define SLAM_REORDER_KPT_NUM_21_LEN    32
#define SLAM_REORDER_KPT_NUM_21_OFFSET 0

#define SLAM_REORDER_KPT_NUM_22_LEN    32
#define SLAM_REORDER_KPT_NUM_22_OFFSET 0

#define SLAM_REORDER_KPT_NUM_23_LEN    32
#define SLAM_REORDER_KPT_NUM_23_OFFSET 0

#define SLAM_REORDER_KPT_NUM_24_LEN    32
#define SLAM_REORDER_KPT_NUM_24_OFFSET 0

#define SLAM_REORDER_KPT_NUM_25_LEN    32
#define SLAM_REORDER_KPT_NUM_25_OFFSET 0

#define SLAM_REORDER_KPT_NUM_26_LEN    32
#define SLAM_REORDER_KPT_NUM_26_OFFSET 0

#define SLAM_REORDER_KPT_NUM_27_LEN    32
#define SLAM_REORDER_KPT_NUM_27_OFFSET 0

#define SLAM_REORDER_KPT_NUM_28_LEN    32
#define SLAM_REORDER_KPT_NUM_28_OFFSET 0

#define SLAM_REORDER_KPT_NUM_29_LEN    32
#define SLAM_REORDER_KPT_NUM_29_OFFSET 0

#define SLAM_REORDER_KPT_NUM_30_LEN    32
#define SLAM_REORDER_KPT_NUM_30_OFFSET 0

#define SLAM_REORDER_KPT_NUM_31_LEN    32
#define SLAM_REORDER_KPT_NUM_31_OFFSET 0

#define SLAM_REORDER_KPT_NUM_32_LEN    32
#define SLAM_REORDER_KPT_NUM_32_OFFSET 0

#define SLAM_REORDER_KPT_NUM_33_LEN    32
#define SLAM_REORDER_KPT_NUM_33_OFFSET 0

#define SLAM_REORDER_KPT_NUM_34_LEN    32
#define SLAM_REORDER_KPT_NUM_34_OFFSET 0

#define SLAM_REORDER_KPT_NUM_35_LEN    32
#define SLAM_REORDER_KPT_NUM_35_OFFSET 0

#define SLAM_REORDER_KPT_NUM_36_LEN    32
#define SLAM_REORDER_KPT_NUM_36_OFFSET 0

#define SLAM_REORDER_KPT_NUM_37_LEN    32
#define SLAM_REORDER_KPT_NUM_37_OFFSET 0

#define SLAM_REORDER_KPT_NUM_38_LEN    32
#define SLAM_REORDER_KPT_NUM_38_OFFSET 0

#define SLAM_REORDER_KPT_NUM_39_LEN    32
#define SLAM_REORDER_KPT_NUM_39_OFFSET 0

#define SLAM_REORDER_KPT_NUM_40_LEN    32
#define SLAM_REORDER_KPT_NUM_40_OFFSET 0

#define SLAM_REORDER_KPT_NUM_41_LEN    32
#define SLAM_REORDER_KPT_NUM_41_OFFSET 0

#define SLAM_REORDER_KPT_NUM_42_LEN    32
#define SLAM_REORDER_KPT_NUM_42_OFFSET 0

#define SLAM_REORDER_KPT_NUM_43_LEN    32
#define SLAM_REORDER_KPT_NUM_43_OFFSET 0

#define SLAM_REORDER_KPT_NUM_44_LEN    32
#define SLAM_REORDER_KPT_NUM_44_OFFSET 0

#define SLAM_REORDER_KPT_NUM_45_LEN    32
#define SLAM_REORDER_KPT_NUM_45_OFFSET 0

#define SLAM_REORDER_KPT_NUM_46_LEN    32
#define SLAM_REORDER_KPT_NUM_46_OFFSET 0

#define SLAM_REORDER_KPT_NUM_47_LEN    32
#define SLAM_REORDER_KPT_NUM_47_OFFSET 0

#define SLAM_REORDER_KPT_NUM_48_LEN    32
#define SLAM_REORDER_KPT_NUM_48_OFFSET 0

#define SLAM_REORDER_KPT_NUM_49_LEN    32
#define SLAM_REORDER_KPT_NUM_49_OFFSET 0

#define SLAM_REORDER_KPT_NUM_50_LEN    32
#define SLAM_REORDER_KPT_NUM_50_OFFSET 0

#define SLAM_REORDER_KPT_NUM_51_LEN    32
#define SLAM_REORDER_KPT_NUM_51_OFFSET 0

#define SLAM_REORDER_KPT_NUM_52_LEN    32
#define SLAM_REORDER_KPT_NUM_52_OFFSET 0

#define SLAM_REORDER_KPT_NUM_53_LEN    32
#define SLAM_REORDER_KPT_NUM_53_OFFSET 0

#define SLAM_REORDER_KPT_NUM_54_LEN    32
#define SLAM_REORDER_KPT_NUM_54_OFFSET 0

#define SLAM_REORDER_KPT_NUM_55_LEN    32
#define SLAM_REORDER_KPT_NUM_55_OFFSET 0

#define SLAM_REORDER_KPT_NUM_56_LEN    32
#define SLAM_REORDER_KPT_NUM_56_OFFSET 0

#define SLAM_REORDER_KPT_NUM_57_LEN    32
#define SLAM_REORDER_KPT_NUM_57_OFFSET 0

#define SLAM_REORDER_KPT_NUM_58_LEN    32
#define SLAM_REORDER_KPT_NUM_58_OFFSET 0

#define SLAM_REORDER_KPT_NUM_59_LEN    32
#define SLAM_REORDER_KPT_NUM_59_OFFSET 0

#define SLAM_REORDER_KPT_NUM_60_LEN    32
#define SLAM_REORDER_KPT_NUM_60_OFFSET 0

#define SLAM_REORDER_KPT_NUM_61_LEN    32
#define SLAM_REORDER_KPT_NUM_61_OFFSET 0

#define SLAM_REORDER_KPT_NUM_62_LEN    32
#define SLAM_REORDER_KPT_NUM_62_OFFSET 0

#define SLAM_REORDER_KPT_NUM_63_LEN    32
#define SLAM_REORDER_KPT_NUM_63_OFFSET 0

#define SLAM_REORDER_KPT_NUM_64_LEN    32
#define SLAM_REORDER_KPT_NUM_64_OFFSET 0

#define SLAM_REORDER_KPT_NUM_65_LEN    32
#define SLAM_REORDER_KPT_NUM_65_OFFSET 0

#define SLAM_REORDER_KPT_NUM_66_LEN    32
#define SLAM_REORDER_KPT_NUM_66_OFFSET 0

#define SLAM_REORDER_KPT_NUM_67_LEN    32
#define SLAM_REORDER_KPT_NUM_67_OFFSET 0

#define SLAM_REORDER_KPT_NUM_68_LEN    32
#define SLAM_REORDER_KPT_NUM_68_OFFSET 0

#define SLAM_REORDER_KPT_NUM_69_LEN    32
#define SLAM_REORDER_KPT_NUM_69_OFFSET 0

#define SLAM_REORDER_KPT_NUM_70_LEN    32
#define SLAM_REORDER_KPT_NUM_70_OFFSET 0

#define SLAM_REORDER_KPT_NUM_71_LEN    32
#define SLAM_REORDER_KPT_NUM_71_OFFSET 0

#define SLAM_REORDER_KPT_NUM_72_LEN    32
#define SLAM_REORDER_KPT_NUM_72_OFFSET 0

#define SLAM_REORDER_KPT_NUM_73_LEN    32
#define SLAM_REORDER_KPT_NUM_73_OFFSET 0

#define SLAM_REORDER_KPT_NUM_74_LEN    32
#define SLAM_REORDER_KPT_NUM_74_OFFSET 0

#define SLAM_REORDER_KPT_NUM_75_LEN    32
#define SLAM_REORDER_KPT_NUM_75_OFFSET 0

#define SLAM_REORDER_KPT_NUM_76_LEN    32
#define SLAM_REORDER_KPT_NUM_76_OFFSET 0

#define SLAM_REORDER_KPT_NUM_77_LEN    32
#define SLAM_REORDER_KPT_NUM_77_OFFSET 0

#define SLAM_REORDER_KPT_NUM_78_LEN    32
#define SLAM_REORDER_KPT_NUM_78_OFFSET 0

#define SLAM_REORDER_KPT_NUM_79_LEN    32
#define SLAM_REORDER_KPT_NUM_79_OFFSET 0

#define SLAM_REORDER_KPT_NUM_80_LEN    32
#define SLAM_REORDER_KPT_NUM_80_OFFSET 0

#define SLAM_REORDER_KPT_NUM_81_LEN    32
#define SLAM_REORDER_KPT_NUM_81_OFFSET 0

#define SLAM_REORDER_KPT_NUM_82_LEN    32
#define SLAM_REORDER_KPT_NUM_82_OFFSET 0

#define SLAM_REORDER_KPT_NUM_83_LEN    32
#define SLAM_REORDER_KPT_NUM_83_OFFSET 0

#define SLAM_REORDER_KPT_NUM_84_LEN    32
#define SLAM_REORDER_KPT_NUM_84_OFFSET 0

#define SLAM_REORDER_KPT_NUM_85_LEN    32
#define SLAM_REORDER_KPT_NUM_85_OFFSET 0

#define SLAM_REORDER_KPT_NUM_86_LEN    32
#define SLAM_REORDER_KPT_NUM_86_OFFSET 0

#define SLAM_REORDER_KPT_NUM_87_LEN    32
#define SLAM_REORDER_KPT_NUM_87_OFFSET 0

#define SLAM_REORDER_KPT_NUM_88_LEN    32
#define SLAM_REORDER_KPT_NUM_88_OFFSET 0

#define SLAM_REORDER_KPT_NUM_89_LEN    32
#define SLAM_REORDER_KPT_NUM_89_OFFSET 0

#define SLAM_REORDER_KPT_NUM_90_LEN    32
#define SLAM_REORDER_KPT_NUM_90_OFFSET 0

#define SLAM_REORDER_KPT_NUM_91_LEN    32
#define SLAM_REORDER_KPT_NUM_91_OFFSET 0

#define SLAM_REORDER_KPT_NUM_92_LEN    32
#define SLAM_REORDER_KPT_NUM_92_OFFSET 0

#define SLAM_REORDER_KPT_NUM_93_LEN    32
#define SLAM_REORDER_KPT_NUM_93_OFFSET 0

#endif // __SLAM_REORDER_REG_OFFSET_FIELD_H__
